### ISSUE TITLE
Core dumped while running with proxychains

### ISSUE THREAD

**Issue by Ekultek** [nmap/nmap#1012]
During a scan behind a host with an IPv6:

```
baal@baal-Aspire-5733Z:~/bin$ proxychains nmap --script dns-brute -sn <SITE> -6
ProxyChains-3.1 (http://proxychains.sf.net)

Starting Nmap 7.60SVN ( https://nmap.org ) at 2017-09-15 08:29 CDT
|DNS-request| <SITE>
|S-chain|-<>-127.0.0.1:9050-<><>-<IP>-<><>-OK
|DNS-response| <SITE> is <IP>
nmap: TargetGroup.cc:609: void NetBlockIPv6Netmask::set_addr(const sockaddr_in6*): Assertion `addr->sin6_family == AF_INET6' failed.
Aborted (core dumped)
baal@baal-Aspire-5733Z:~/bin$ 
```

**Comment by dmiller-nmap** [comment]
Proxychains works by interrupting normal system calls and changing how they work. We can't really spend time making Nmap robust against this. However, you have several odd things in your command that are causing problems, and I think you could change them:

* You are using Proxychains 3.1, which is no longer supported and has known bugs, especially in conjunction with Nmap. Use [proxychains-ng](https://github.com/rofl0r/proxychains-ng) instead.
* You are using `-6` but many SOCKS proxies do not support IPv6. Additionally, you probably don't have compelling reason to use `-6` with "dns-brute" since the queries are sent to your configured DNS servers according to their IP address family and not according to what you tell Nmap to use.
* You are using "dns-brute" with ProxyChains, but it uses UDP to send DNS queries, and many SOCKS proxies do not support UDP traffic. It is especially worth pointing out that Tor does not support UDP traffic, so this traffic will not be proxied.

Spend some time thinking about exactly what you want to do and what traffic it will result in. Then figure out the best way to do it. If what you want to do is try out a bunch of hostnames on a DNS server that is behind a proxy, then Nmap may not be the best option yet. We are continuing to improve proxy support (currently supported natively for NSE and `-sV` over TCP), but it is not capable of this yet.

**Comment by Ekultek** [comment]
Very detailed answer, and much appreciated thank you.
