### ISSUE TITLE
ssl-enum-ciphers.nse

### ISSUE THREAD

**Issue by pealtrufo** [nmap/nmap#1040]
Hi there.

I would like to understand where the source/input for 'ssl-enum-ciphers.nse' script is, I mean, what is the basis for reporting a specific cipher as weak after a scan? How that is maintained over time?

Thanks!

**Comment by nnposter** [comment]
This question is a bit too broad. The general answer is that it follows industry best practices, NIST and IETF recommendations, and takes into account community input as well.

If you want to see the gory details then take a peek at the script source code. If you have a specific concern about the cipher suite rating then feel free to elaborate here.

**Comment by dmiller-nmap** [comment]
The source is here: https://github.com/nmap/nmap/blob/master/scripts/ssl-enum-ciphers.nse

The rating system is based on Qualys SSL Labs SSL Server Rating Guide, but instead of giving an overall system score, it shows the component of the score that comes from each particular cipher suite/handshake.

**Comment by pealtrufo** [comment]
Thanks for the responses. So, irrespective of the nmap version I am using, am I right assuming that this script have to manually be updated to get the latest scores over time?
Kind regards
