### ISSUE TITLE
nmap mixes product and version in service version detection?

### ISSUE THREAD

**Issue by spacewander** [nmap/nmap#1042]
Recently, we got an interesting service version detection report after scanning with nmap.

The report shows:
```
8080/tcp  open  http          nginx 5.6.25
```

It looks like that the report mixed the product(nginx) with the version(PHP/5.6.25).

Here is one piece of the output from `nmap -sV $our_host -dd -p 8080`:
```
Starting probes against new service: $our_host:8080 (tcp)
Service scan sending probe NULL to $our_host:8080 (tcp)
Service scan sending probe GetRequest to $our_host:8080 (tcp)
Service scan match (Probe GetRequest matched with GetRequest line 10398): $our_host:8080 is http.  Version: |PHP|5.6.25||
Service scan sending probe HTTPOptions to $our_host:8080 (tcp)
Service scan sending probe RTSPRequest to $our_host:8080 (tcp)
Service scan match (Probe RTSPRequest matched with RTSPRequest line 11762): $our_host:8080 is http.  Version: |nginx|||
Completed Service scan at 14:36, 6.18s elapsed (1 service on 1 host)
```

The version detection is correct, there is a PHP application running behind Nginx(OpenResty).
But the final report is incorrect, it mixed the product and the version.

We found this behaviour with nmap 7.40, but it still could be reproducted with the one compiled from the latest code.

Here is a minimal reproduction of the behaviour:
```nginx.conf
events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        add_header X-Powered-By PHP/5.6.25;
        # more_set_headers directive is from https://github.com/openresty/headers-more-nginx-module
        more_set_headers 'Server: our customized server header';
        error_page 404 /404;
        error_page 400 /400;
        location = / {
            return 200 "OK";
        }
        location = /404 {
            return 404 "our customized 404 page";
        }
        location = /400 {
            return 400 '<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n';
        }
    }
}
```

Run commands below to start the mock server:
```
$ nginx -p .
$ nmap -sV 127.0.0.1 -dd -p 8080 2>/dev/null
```

**Comment by dmiller-nmap** [comment]
I just pushed a change to fix this particular mixup, but maybe we should change the way softmatches are allowed to fill in version details.

The trouble comes from a softmatch that fills in more details than the actual match line. This is very rare, because of the nature of softmatches: they are usually used only to fill in the service name, which is a required part of every match. In this case, the softmatch filled in the `product` and `version` fields for PHP, and then the actual match line changed the `product` to "nginx" and did not provide a version.

I think that the `version` field is the only one that ought to cause a problem like this, because it is tightly paired conceptually to the `product` field. If a match is superseding a previous softmatch *with* `version`, we can do either of 2 things:

1. Drop the version field if the product field changes, or
2. Keep the softmatched product and version if the matched product does not have a version (assume that it is less-specific.

I welcome some discussion on this topic before I go in and change something.

**Comment by spacewander** [comment]
@dmiller-nmap 
https://github.com/nmap/nmap/commit/752beebe45e9d9b529834ea5de16ed83eed6715a fixes the problem, thank you! What a quick fix!

Personally speaking, I will vote for the second approach, because it keeps more detail in the scan.
