### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by danielling23** [nmap/nmap#1048]
The install fails repeatedly. I have tested 0.93 and 0.95
I do have admin rights on my system but it seems there are some access denied errors towards the end. 

[NPFInstall.log](https://github.com/nmap/nmap/files/1414432/NPFInstall.log)

**Comment by dmiller-nmap** [comment]
Thanks for the report. I do see the access denied errors. Please also run [DiagReport](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport) and provide the output along with the `install.log` file.

**Comment by danielling23** [comment]
[DiagReport-20171027-120157.txt](https://github.com/nmap/nmap/files/1420737/DiagReport-20171027-120157.txt)
[install.log](https://github.com/nmap/nmap/files/1420738/install.log)
both files uploaded. UAC is disabled when attempting the install if it helps.

**Comment by danielling23** [comment]
@dmiller-nmap Any update on this? Let me know if you need any further logs on this.

**Comment by dmiller-nmap** [comment]
Sorry for the delay. We are trying to find out [how to get more detailed error information from this install function](https://social.msdn.microsoft.com/Forums/en-US/339c5af7-e3f4-4521-8ace-4570c540133f/how-to-diagnose-inetcfgclasssetupinstall-errors?forum=wdk) so that we can properly debug this. However, since the error is "Access denied" and you mentioned changing UAC settings, the only suggestion I can make at this point is to restore the UAC settings to normal and see if the installation succeeds.

When you say you have admin rights, do you mean that your account is a member of the Builtin Adminstrators group, or do you have a domain account with admin privileges? Anything unusual about your login session, like RDP?

**Comment by dmiller-nmap** [comment]
I noted over at #1041 that we may be able to diagnose errors in this function by examining the `C:\Windows\INF\NetCfg*.etl` event logs. Can you provide those in a zip file here or via email to dmiller@nmap.com? Thanks

**Comment by dmiller-nmap** [comment]
Since we got no further response and Npcap has had significant improvements since 0.95, I am provisionally closing this issue. If you are still experiencing the same problem with Npcap 0.99-r6 or later, please ask us to reopen this issue. If anyone else is experiencing this for the first time with Npcap 0.99-r6 or later, please open a new issue.
