### ISSUE TITLE
The signed windows installer warns me a security risk on Windows 2008 Standard

### ISSUE THREAD

**Issue by howardchn** [nmap/nmap#1084]
We are using your tool npcap installer v0.94. It seems the certification is not right on Windows 2008 standard. Would you mind to take few time to give us any idea about this?

**Comment by fyodor** [comment]
Thanks Howard.  This may be caused by issue #994, which we fixed in Npcap 0.95.  So  can you please try our latest version of Npcap (0.97) and let us know how it goes?  Since we are already discussing this on email, and since you were able to send more details there (including the screenshot), I will close this bug report for now.
