### ISSUE TITLE
After reboot, loopback adapter disappear.

### ISSUE THREAD

**Issue by GreatFireWall** [nmap/nmap#1095]
As title, when I install npcap successful, I can see loopback adapter in the "Network Connections" of Control Panel, and in the wireshark adapter list. It works well.
But after my computer reboot, it disappears from "Network Connections" and wireshark adapter list.

**Comment by gpotter2** [comment]
I'm having the very same bug

**Comment by dmiller-nmap** [comment]
Please provide (attach) DiagReport output and NPFInstall.log as described [in the Npcap Users' Guide](https://nmap.org/npcap/guide/npcap-issues.html#npcap-issues-diagreport) so we can diagnose the problem. Also let us know if previous versions have worked successfully or if anything else is unusual or has changed in your system.

**Comment by gpotter2** [comment]
Sure:
https://pastebin.com/LyRvXa6i
I'll check if older versions worked

**Comment by GreatFireWall** [comment]
I guess some game anti-cheat engine will cause this issue, because loopback adapter disappears again after I playing "MapleStory GMS".

**Comment by gpotter2** [comment]
@GreatFireWall Not my case, i've not started any of those between reboots

**Comment by dmiller-nmap** [comment]
@gpotter2 Your issue is probably related to #998 (start type of npcap service changes after windows update) and #1216 (windows update removes Npcap Loopback Adapter). I'm guessing this because you're using the Tech Preview, which probably means you're getting version upgrades more frequently. We haven't identified how to avoid these issues, but we'll be getting a guide or tool together to quickly fix installations without requiring a full reinstall.

@GreatFireWall It sounds like you've identified the problem. We can't prevent other software from removing Npcap or its Loopback Adapter, unfortunately. We will document this interaction for future reference.
