### ISSUE TITLE
Please remove unnecessary outputs

### ISSUE THREAD

**Issue by neo-expert** [nmap/nmap#1128]
After starting nmap there are so many unnecessary outputs, they drive me crazy!

Example:
```
➜  ~ nmap google.de

Starting Nmap 6.40 ( http://nmap.org ) at 2018-02-02 16:24 CET
Nmap scan report for google.de (216.58.208.35)
Host is up (0.0037s latency).
rDNS record for 216.58.208.35: fra15s12-in-f35.1e100.net
Not shown: 998 filtered ports
PORT    STATE SERVICE
80/tcp  open  http
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 4.86 seconds
➜  ~
```
* What is this empty line for, after starting nmap?
* I tipped nmap to start nmap, ok nmap says "Starting Nmap" -> that is a novum!
* why is there "--version" option in nmap when it says its version everytime I start it! 
* I know the time when I started nmap, why should it be important?
* nmap is done? ok interesting information.

Everyone like simple programs. How about this one:

```
user@host:~$ ls

Starting ls 7.01 ( https://ls.org ) at 2016-10-05 12:20 CEST

directory list report for 127.0.0.1:~/


There are no files in current directory


Service detection performed. Please report any incorrect results at https://ls.org/submit/ .

ls done: 1 IP address (1 host up) scanned in 34.68 seconds
user@host:~$
```

**Comment by aniketp** [comment]
@neo-expert `nmap` is a tool developed for network discovery and security auditing. For forensic purposes, it is necessary for nmap to produce certain information in each scan. So, the part of output which you find unnecessary might be very useful for a lots of people.

In case you use `nmap` regularly and plan to keep a record of successive scans,  you might want to have the time and duration of each scan, this can turn out to be life saver later on.

Additionally, there are lots of parameters which can give you the desired result,  so if you want to reduce the clutter, please be specific about the your purpose of scan. 

Still, if you feel there can be improvements in nmap, please send your ideas/complaints to [dev@nmap.org](mailto:dev@nmap.org)

**Comment by aniketp** [comment]
``` bash
▶ nmap --version

Nmap version 7.01 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.2.4 openssl-1.0.2g libpcre-8.38 libpcap-1.7.4 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```
`--version` gives a lot more information rather than just the nmap's version.

**Comment by neo-expert** [comment]
Yeah, but there are tools for that, for example you can do echo "Stariting Nmap". You can measure time withhin a script. You could do this output in verbose mode with "-v" option, but please do not it in normal mode. That is a violation against the Unix Philosophy: make programs as simple as posible and let programs work together.
What should a third Party programm do with that unneceserry outputs? Parse it away?

**Comment by dmiller-nmap** [comment]
@neo-expert Thanks for showing interest in Nmap! We really do value the input of our users, and I hope you feel welcome in our community. 

Nmap's output style has a long history and is derived from the traditions of hacking tools, many of which have elaborate startup banners. It does not adhere to the Unix philosophy, as it does many things (not just one) well. It is not even exclusively a Unix program: many of Nmap's users use it on Windows.

I agree that the blank line at the beginning is a bit odd, but it's been there since the very beginning (see the original source in [Phrack issue 51](https://nmap.org/p51-11.html)). I'll ask @fyodor if he has any particular attachment to it.

Including the start time and run time in the output is important to frame the output as a snapshot in time; services and hosts appear and disappear on networks with surprising frequency. Scanning can also take a while; without the initial "Starting Nmap" line, the user might be left waiting for a few minutes without knowing if anything was going on.

Your question about `--version` was already answered by @aniketp: it provides detailed version info, similar to `perl -V`.

To answer your final question about what a third-party program should do: it should use one of the machine-readable output formats, preferably [XML output](https://nmap.org/book/output-formats-xml-output.html). The normal screen output has too much variability between versions to reliably parse.

In the future, it'd be helpful if you could propose changes instead of just criticizing existing behavior. Hearing "this is bad" doesn't help us make it any better. Cheers!
