### ISSUE TITLE
Wireless adapter not supported

### ISSUE THREAD

**Issue by HassaanTauqir** [nmap/nmap#1133]
Hello,
I am trying to install npcap to work with Wireshark to use monitor mode, however, i am not getting the Wireshark monitor mode checkbox.

I checked using the wlanhelper.exe, to see if my adapter is supported, and it shows not supported

My network adapter is Dell Wireless 1704 802.11 b/g/n

Is there any way that i can get it to work with this adapter?

Also, i am using Windows 10, is it possible that the adapter might work with Linux or any other Operating System?

[NPFInstall.log](https://github.com/nmap/nmap/files/1712018/NPFInstall.log)
[DiagReport-20180209-222323.txt](https://github.com/nmap/nmap/files/1712019/DiagReport-20180209-222323.txt)
[install.log](https://github.com/nmap/nmap/files/1712020/install.log)

**Comment by dmiller-nmap** [comment]
Here's [the entry for Dell 1704](https://wikidevi.com/wiki/Dell_Wireless_1704_(DW1704)) on WikiDevi. It indicates that it uses a Broadcom chipset. Linux drivers are available, but I do not know what features they may support. You could check for an updated Windows driver to see if support has improved. Otherwise, we appreciate your input, which we will use to update our [table of device support for Npcap](https://secwiki.org/w/Npcap/WiFi_adapters).
