### ISSUE TITLE
Two feature requests 

### ISSUE THREAD

**Issue by jftuga** [nmap/nmap#1137]
Be able to use: -pall 
This would be a shortcut for -p1-65535
I looked at the code for this one but could not get my version working. This is slightly above my skill set.

----

-ls loop/stop (or another name that might fit better)

I like to continuously scan a port (or small set of ports) until the port(s) are up.  I use this when rebooting a server, network switch or firewall.

nmap -p 22,443 -ls 192.168.1.1

Here, nmap would scan both ports in parallel, once per second, until both ports were reachable.  Then it would stop scanning and send a Bell (sometimes this is ^g) to the terminal.  This way, I can be working in another window and get an audio notification that my device is finished booting.

Do these sound like good features to add into nmap?

**Comment by dmiller-nmap** [comment]
For your first suggestion, [the Nmap man page](https://nmap.org/book/man-port-specification.html) has this to say:

>  The beginning and/or end values of a range may be omitted, causing Nmap to use 1 and 65535, respectively. So you can specify -p- to scan ports from 1 through 65535.

Regarding the second, that is a major change to the central ideas of Nmap, which would require changes to output, port state tracking, and control flow, since Nmap currently only scans a port once per target. Instead, I suggest a simple shell loop:

    until nmap -p 22,443 192.168.1.1 -oG - | grep -q '22/open.*443/open'; do sleep 1; done; echo -e '\a'

This uses Nmap's [Grepable output](https://nmap.org/book/output-formats-grepable-output.html) which is usually easier for shell scripting.

**Comment by jftuga** [comment]
Thank you for your insightful reply. I really appreciate your timely response.

-John
