### ISSUE TITLE
ncat_core.c:352: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [nmap/nmap#1157]
ncat_core.c:352:48: warning: logical ‘or’ of collectively exhaustive tests is always true [-Wlogical-op]

Source code is

   if (err != SSL_ERROR_WANT_READ || err != SSL_ERROR_WANT_WRITE) {

Maybe better code:

   if (err != SSL_ERROR_WANT_READ && err != SSL_ERROR_WANT_WRITE) {

Suggest switch on gcc compiler flag -Wlogical-op to detect this kind of problem in future.

**Comment by nnposter** [comment]
There seems to be a bigger issue in the code vicinity. If `err` happens to be either `SSL_ERROR_WANT_READ` or `SSL_ERROR_WANT_WRITE` then another `SSL_read` is attempted. Notice that if this operation succeeds (i.e., `n` is non-negative) then `err` is not reset. It retains its original value so another `SSL_read` is attempted, and again, and again, until the call errors out.

This might fix the issue:
```diff
--- ncat/ncat_core.c	(revision 37216)
+++ ncat/ncat_core.c	(working copy)
@@ -339,7 +339,7 @@
 {
 #ifdef HAVE_OPENSSL
     int n;
-    int err = SSL_ERROR_NONE;
+    int err;
     if (o.ssl && fdn->ssl)
     {
         do {
@@ -347,13 +347,10 @@
             /* SSL_read returns <0 in some cases like renegotiation. In these
              * cases, SSL_get_error gives SSL_ERROR_WANT_{READ,WRITE}, and we
              * should try the SSL_read again. */
-            if (n < 0) {
-                err = SSL_get_error(fdn->ssl, n);
-                if (err != SSL_ERROR_WANT_READ || err != SSL_ERROR_WANT_WRITE) {
-                    logdebug("SSL error on %d: %s\n", fdn->fd, ERR_error_string(err, NULL));
-                }
-            }
+            err = (n < 0) ? SSL_get_error(fdn->ssl, n) : SSL_ERROR_NONE;
         } while (err == SSL_ERROR_WANT_READ || err == SSL_ERROR_WANT_WRITE);
+        if (n < 0)
+            logdebug("SSL error on %d: %s\n", fdn->fd, ERR_error_string(err, NULL));
         return n;
     }
 #endif
```

@dmiller-nmap You have better understanding of the code intent here so please let me know if you are seeing any issues with this refactoring. Otherwise I will commit it in a week or so.

**Comment by dmiller-nmap** [comment]
I am really embarrassed at these simple mistakes. I'll get a fix committed
today and maybe we'll do a bugfix release shortly.

**Comment by nnposter** [comment]
I have this patch ready in my local SVN snapshot. Let me know if I should commit it and then you follow up with whatever tweaks to it or whether I should scratch it.
