### ISSUE TITLE
Nmap crash will imply no results at all.

### ISSUE THREAD

**Issue by nikaiw** [nmap/nmap#1174]
When running a large nmap scan, if a crash occurs, says when the NSE engine is running, the nmap report will be empty (or almost empty containing only the ran command)

Would it be possible to change nmap behavior so that if you start a long scan you don't end-up losing all of the results close to the end of scan?

Nmap could by default write information in the outputs files as the scan progress or provide an argument allowing this behavior.

**Comment by dmiller-nmap** [comment]
Nmap's current design scans hosts in groups called "hostgroups." A group of hosts must go through all scan phases (host discovery, port scan, version scan, NSE, OS discovery, traceroute, etc.) before Nmap can print the results for any of them. The obvious benefit of scanning multiple targets at once is increased scanning speed, but the downside is some latency in getting the results back. Nmap usually chooses a small hostgroup size for the first hostgroup, so that you get some results back right away, but then increases the size for later hostgroups, so that the scan as a whole goes quickly.

Without a wholesale redesign of Nmap's scan engine, there are a few things you can do to obtain the behavior you want:

1. Report crashes so we can fix them. Nmap *should never crash* in such a way that you don't get finalized output. Of course, we sometimes find such crashes, so make sure you are using the latest version.
2. Reduce the size of your scans. If you don't need all features, don't use `-A`. This will speed up scanning, reduce memory footprint (in case your system is killing Nmap due to consuming too much memory), and make it more likely to finish without crashing.
3. Use the `--max-hostgroup` option to reduce the number of targets scanned at one time so that you get results more frequently. Be warned: this can slow down scanning because Nmap will spend more time waiting around for the right time to send a probe, since it can't spread its probes out across as many targets.
