### ISSUE TITLE
Bitdefender blocking NPCap 0.99-r3.exe installer

### ISSUE THREAD

**Issue by WildCard65** [nmap/nmap#1181]
Here is bitdefender's report:

```The file C:\Users\user\Downloads\npcap-0.99-r3.exe is infected with Gen:Variant.Ursu.25521. The virus has been successfully blocked and your PC is now safe.```

**Comment by dmiller-nmap** [comment]
We were made aware of this on the Nmap-dev mailing list earlier this weekend. Today I submitted false positive reports to all AV vendors that flagged it on VirusTotal. Here's a list:

- [ ] Arcabit
- [ ] BitDefender (submission acknowledged)
- [ ] Emsisoft
- [x] F-Secure (will be fixed in next database update)
- [ ] GData
- [ ] MAX (not submitted, can't find contact info)
- [ ] eScan (submission acknowledged

**Comment by WildCard65** [comment]
Bitdefender can be checked off as well now.

**Comment by WildCard65** [comment]
I think I found contact information for Cybereason: https://www.cybereason.com/ Under the "Company" tab

**Comment by WildCard65** [comment]
@dmiller-nmap All I did was find contact information for Cybereason (via Google), someone else must've done it.

**Comment by WildCard65** [comment]
@dmiller-nmap Seems they dropped off the list because the scan failed (as VirusTotal is showing an eye crossed out for it)

**Comment by WildCard65** [comment]
I found contact information for "MAX", be warned though, it looks like it might be a Korean AV software.

http://stsc.com/max.html

**Comment by dmiller-nmap** [comment]
All vendors have been contacted, and we have newer installers available. Closing this issue now.
