### ISSUE TITLE
nmap7.70 core dumped when scan service(old issue)

### ISSUE THREAD

**Issue by liteway** [nmap/nmap#1196]
Hi, the closed issue #1108 is not fixed, I can reproduce this crash with github latest version.
The core file can get from https://github.com/nmap/nmap/files/1941784/service_coredump.tar.gz

**Comment by dmiller-nmap** [comment]
Thanks for this bug report! I started looking into this further, and the issue is a little more complicated than this. First, changing the greediness of quantifiers can change how the pattern matches, and we don't have an exhaustive test suite to ensure that the database isn't corrupted by these changes. However, some patterns are standard matches for certain protocols, so those can be changed fairly easily. In fact, it was changing a lot of patterns for HTTP services that probably caused this issue.

There are a lot of cases where we want to match one particular HTTP header regardless of where it occurs in the list of headers, but without matching it in the HTTP body. The Server header is a good example from Nmap 7.70:

    match http m|^HTTP/1\.[01] \d\d\d (?:(?!\r\n\r\n).)*?\r\nServer: Icinga/[rv](\d[\w._-]*)\r\n%s p/Icinga/ v/$1/ cpe:/a:icinga:icinga:$1/

That blob in the middle, `(?:(?!\r\n\r\n).)*?`, matches any character so long as it's not the first carriage return in a CRLF CRLF which marks the end of the headers. It continues matching like that in non-greedy fashion until it reaches the Server header or the end of headers, at which point it either matches or does not match. The problem is that every time the engine enters a set of parentheses, a recursion happens, which adds another call to the stack. So we get one recursion for *every character until the Server header is found and matches*, which easily runs out of stack really fast for services that don't match.

The solution I found is to consume more than one character at a time while processing the headers. Any non-CRLF characters should be able to be consumed in one go, and a CRLF should always come at the end of a header line. With this in mind, the preceding match becomes:

    match http m|^HTTP/1\.[01] \d\d\d (?:[^\r\n]*\r\n(?!\r\n))*?\r\nServer: Icinga/[rv](\d[\w._-]*)\r\n%s p/Icinga/ v/$1/ cpe:/a:icinga:icinga:$1/

The new blob `(?:[^\r\n]*\r\n(?!\r\n))*?` means "match any number of non-CRLF characters followed by a CRLF, but not followed by 2 CRLFs in a row," and we match it non-greedy, which means it stops after consuming each header and checks whether the Server header matches. Care has to be taken to get the right number of CRLFs before and behind the blob, so in some cases we'll use a lookbehind assertion to make sure that the header we are checking for really does come at the beginning of the header, and not deep within a Set-Cookie header or something. So now we get one recursion for each *header*, not each character. We get a lot less backtracking, too, which is great.

There may be other issues with our patterns, but after I push a change for this particular one, you can let me know if it still crashes on this particular service. We can open new issues for further problems after this one is done, if they arise.

**Comment by liteway** [comment]
Thanks for your patient answer. I use the latest version test my cases, this crash no longer appears, and can get expected result, thanks for fixing this bug.
