### ISSUE TITLE
Nmap will not scan /22 orlonger mask

### ISSUE THREAD

**Issue by tgreaser** [nmap/nmap#1197]
I noticed this in 7.60 and updated to 7.70 and same results
I try and run nmap -sL 10.0.0.0/22 and get nothing back and just sits at the prompt,  but if i do /23 or 24 it works 100%

**Comment by TomSellers** [comment]
@tgreaser - The `-sL` command simply lists the IP addresses ( without sending any packets to the target ) and performs DNS name reverse resolution on them. I suspect that what you are seeing is delays due to your DNS server being overwhelmed with 1,000 near simultaneous requests. That being said, most DNS services, even on small home routers, should handle this.

You can get a better idea of what is going on by using one of the following commands:

#### Enabling debugging output
`nmap -d2 -sL 10.0.0.0/22 `

#### Tracing packets
`nmap  --packet-trace -sL 10.0.0.0/22 `

Nmap `-sL` reference: https://nmap.org/book/man-host-discovery.html

**Comment by tgreaser** [comment]
your 100% right .. I totally forgot  i set that limit up on our dns **been that long ago**.. Sorry !!!





Thanks,
Tom
Office Phone 304.293.4683
Vidyo Room: Tom Greaser  IVR dialing in by phone 304-581-1179x010013#
For current list of network alerts please visit.
http://its.hsc.wvu.edu/


________________________________

**Comment by TomSellers** [comment]
Fantastic! Can you go ahead and close this Issue? Or perhaps @bonsaiviking  can.

**Comment by tgreaser** [comment]
Like Tom posted.. DNS policing on our side .. LOL.
