### ISSUE TITLE
Is there a way to contribute to Npcap ?

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#1253]
Hello!

I am willing to contribute debugging Npcap 802.11 mode, but can't find a way to debug Npcap properly :/
The deploy installers have been completely removed from Npcap, for an unknown reason, moved to a "private repository"...

Is there a way to compile the driver and debug it?

Thanks!

**Comment by fyodor** [comment]
Hi @gpotter2. There are a couple reasons we moved the build stuff:

1) Only a few of us actually build Npcap, and it this allows us to include and depend on things specific to our build systems rather than trying to keep it 100% generalized and documented to work on anyone's systems.  Of course we would never keep the particularly sensitive things, like the signing keys, on GitHub.  They're on a hardware security token.

2) Keeping the build stuff separate makes it a little bit harder for people to build and redistribute malware or otherwise malicious or unauthorized versions of Npcap.  Or to embed Npcap within other types of spyware/adware/malware.  The Npcap license doesn't allow redistribution anyway, but black hats aren't usually so concerned with the legalize.

3) For debugging, it is often easier for people to use the builds we provide with debug symbols so you don't have to build it yourself.  We have those for our current release (0.99-r6) and our other recent releases.  Those filenames contain "DebugSymbols" and you can find them at https://nmap.org/npcap/dist/.

All that being said, there may be good reasons that people want the build stuff and we don't want to block that.  If anyone has a reason they need the files, send me an email at fyodor (at) nmap.org and I'll try to get them to you.  And if there is a lot of demand, we might be able to restructure things to move more of what people want into the main Npcap repo.  Cheers!
