### ISSUE TITLE
Nmap Grep Output FQDN Problem

### ISSUE THREAD

**Issue by gbiagomba** [nmap/nmap#1273]
Hello,

I was running nmap and I realized when outputting to a a greppable format, I noticed it skipped the FQDN or servername for every other finding. I double checked the normal nmap file  and the servernames where there for all targets. But when looking at the grep version, some where missing.

**Comment by dmiller-nmap** [comment]
The "grepable" format hasn't changed significantly since Nmap 3.50, and is considered "deprecated," which is supposed to mean that it will not change regardless of when new features are added to other output formats.

There are 2 possible names for each target: the targetname given as input to Nmap, and the hostname retrieved via reverse-DNS. Grepable always returns the hostname, since prior to Nmap 5.10BETA1 that was the only name reported by any output format.

If you want a machine-readable format that contains all the information Nmap generates, use the [XML output format](https://nmap.org/book/output-formats-xml-output.html).

**Comment by gbiagomba** [comment]
Thank you
