### ISSUE TITLE
Possible problems running Nmap/Windump right after silent installer runs

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#128]
We've received a report from a company who had basically a batch file which would run the winpcap installer and then immediately run Nmap or maybe a program similar to windump and it would fail. The problem seems to be that npf wasn't fully loaded when they start using it and then the driver is basically borked and they can't even do "net stop npf" and have to reboot.  When they added a 500ms delay after the winpcap install finished but before running their software, that workaround worked for them.  They were using Windows 2012 R2.  This is using the normal Nmap winpcap installer as shipped with Nmap 4.76.  We should try to reproduce that and, if we can, see if we can reproduce with npcap the same way.  And if so, make sure we have a fix for npcap.

**Comment by hsluoyz** [comment]
To test the bug reported by Rapid7 about winpcap-nmap-4.13.exe. I wrote a bat a couple of days ago as below:

start winpcap-nmap-4.13.exe /S
start windump -i 4
nmap -v -A -T4 192.168.0.1

Actually my bat will cause failure because winpcap-nmap-4.13.exe /S fisrtly uninstalled the software and then reinstall it. So if nmap or windump starts working after uninstallation and before resintallation, it would fail. If I manually uninstall the software first before running the bat, all things go well and no more abnormals. So we still need Rapid7's further bug reproduce procedures.

**Comment by fyodor** [comment]
I'm closing this since we haven't been using the Nmap winpcap-installer for years becuse we developed the awesome Npcap instead!
