### ISSUE TITLE
Misleading host discovery

### ISSUE THREAD

**Issue by Rourke101** [nmap/nmap#1293]
I find a bit misleading that doing a:

nmap -sn -n -T5 -PU5011 192.168.80.132 --send-ip --packet-trace -vvv

returns:

Starting Nmap 7.40 ( https://nmap.org ) at 2018-07-22 10:07 EDT
Initiating Ping Scan at 10:07
Scanning 192.168.80.132 [1 port]
SENT (0.0448s) UDP 192.168.80.131:55085 > 192.168.80.132:5011 ttl=46 id=1576 iplen=28 
SENT (0.2957s) UDP 192.168.80.131:55086 > 192.168.80.132:5011 ttl=59 id=13873 iplen=28 
Completed Ping Scan at 10:07, 0.55s elapsed (1 total hosts)
Nmap scan report for 192.168.80.132 [host down, received no-response]
Read data files from: /usr/bin/../share/nmap
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 0.58 seconds
           Raw packets sent: 2 (56B) | Rcvd: 0 (0B)

What happens is that the host does not even exist, but nmap reports "sending UDP" when the network sniff no UDP packet, only the ARP packet to find the MAC address. It would be helpful if this can be indicated somehow, since otherwise I am lead to believe that an actual UDP packet was sent.

**Comment by dmiller-nmap** [comment]
I agree that this seems misleading at first. I had to do some research to understand it myself, which I found to mostly be a reminder that "UDP offers no guarantees." This extends even to the IP layer: there are no guarantees that you will be notified of the inability to send to a particular address. This affects us by causing `sendto` with a UDP datagram on a raw socket to [never return an error](https://stackoverflow.com/questions/33208263/udp-sendto-never-fails). 

So in the end, this is intentional behavior because there's no way for us to know that the target couldn't be contacted. The end result is the same: the target is marked "down." This is one reason why UDP isn't a great choice for host discovery.

Is there a reason you're using `--send-ip` in this case? On Linux, the behavior is nearly the same as using `--disable-arp-ping`, but it could have other impacts I'm not aware of. I did find that using `--disable-arp-ping --send-eth` would end up causing Nmap to quit if it scanned a target that couldn't complete an ARP handshake. I turned that into an error instead, but it's not a wise combination of options, since it just forces a serial ARP request to be sent for each target instead of the standard parallel ARP scan. After all, we still need to do that handshake in order to build Ethernet frames with the proper destination MAC.

**Comment by Rourke101** [comment]
I see, thanks. Well, if you have knowledge that the MAC could not be retrieved then it would be good to indicate so, instead of a `SENT UDP` that was never sent. Otherwise, I think little can be done. I am not sure if your commit will indicate it (I haven't check the source).

I used `--send-ip` to specifically test the behaviour of UDP (I did not want ARP to be used), and I tried with `--disable-arp-ping` with similar results.
