### ISSUE TITLE
smb2 os.date exception on Windows 10

### ISSUE THREAD

**Issue by bbday** [nmap/nmap#1303]
I have this issue when try some smb scripts:

C:\Program Files (x86)\Nmap/nselib/smb2.lua:392: time result cannot be represented in this installation
stack traceback:
        [C]: in function 'os.date'
        C:\Program Files (x86)\Nmap/nselib/smb2.lua:392: in function 'smb2.negotiate_v2'

On Kali it work, on Windows 10 returns this error Nmap 7.70

**Comment by gvanem** [comment]
The LibLua.lib your Nmap is using is passed a time-value that goes beyond the year 2038.
`os.date()` on Windows (especially the MinGW junk), does handle that when `liblua.a`/ `liblua.lib` was compiled with an old SDK or `-D_USE_32_BIT_TIME_T` in `CFLAGS`. 

Try this with the `lua.exe` that should be bundled in Nmap (`2147483648 = LONG_MAX+1`):
```
c:\>lua.exe -e "print(os.date('%%Y-%%m-%%d %%H:%%M:%%S',2147483648))"
2038-01-19 03:14:08
```
Works fine. If you have an old `lua.exe`, try the same:
```
c:\old-junk\lua.exe: (command line):1: bad argument #2 to 'date' (time out-of-bounds)
stack traceback:
        [C]: in function 'os.date'
        (command line):1: in main chunk
        [C]: in ?```
```

> On Kali it work, 

I guess you Kali uses something like a `gmtime (const __time64_t*)`. The same as Nmap with a decent compiler should have been compiled with. I.e. `_gmtime64()` from `api-ms-win-crt-time-l1-1-0.dll`. But it depends. Try building Nmap yourself.

Also, try adding some trace-print in `smb2.lua` and see what the raw time-value is. I guess it's well beyond 2147483647.

**Comment by dmiller-nmap** [comment]
This does affect the official Windows build, but the problem is not the 2038 problem but instead a "3001" problem. The highest representable date I can obtain is 3001-01-01 07:59:59 UTC (timestamp 0x793406fff). It looks like Lua uses `localtime`, which according to [the docs on MSDN](https://msdn.microsoft.com/en-us/library/bf12f0hc.aspx) will return NULL if the date is "After 23:59:59, December 31, 3000, UTC (using _time64 and __time64_t)."

So we (Nmap) need to handle potential errors thrown by os.date in this and possibly other places in order to preserve what output we can. But we should probably file a bug with Lua upstream to see if they can extend `os.date` to work with later timestamps on Windows.

@batrick: Any thoughts on how to best approach this?

**Comment by batrick** [comment]
> @batrick: Any thoughts on how to best approach this?

Catching the error in smb seems reasonable to me with an appropriate fallback.

Asking for Lua to use some Windows specific alternative is not unreasonable but it may take a while to see the fruits of that labor. You may instead want to consider that since we need to build Lua for windows anyway, we can just carry an downstream patch in our version of Lua.

**Comment by gvanem** [comment]
> but the problem is not the 2038 problem but instead a "3001" problem.
...
> 23:59:59, December 31, 3000

Pretty close as to what Lua prints here:
```
lua -e "print(os.date('%%X, %%B %%d, %%Y', 0x793582aff))"
07:59:59, January 19, 3001
```
That hex-value is what Microsoft uses as `max_time_t = 0x793582affLL` deep inside the CoreCrt. 
With some slack for max daylight correction etc. Pretty hairy.

**Comment by dmiller-nmap** [comment]
I changed these (smb and smb2) to use `stdnse.format_timestamp` instead of `os.date` and enhanced `format_timestamp` to catch errors in `os.date`. If there's an error and the value of the timestamp is more than 0xffffffff (max 32-bit date), then we manually calculate the number of extra years, subtract them off, get the date with the smaller timestamp, add the years back, and format it as a date without a time (because the method is not accurate down to the second). For a date in 3052 this method was accurate within 4 hours, so it should be pretty good.

Fix incoming.
