### ISSUE TITLE
Ncat gives obscure message when connection attempt times out

### ISSUE THREAD

**Issue by stefanoborini** [nmap/nmap#1324]
Version: 7.70 on windows 10.

The following behaviour happens when the host/port cannot be reached (timeout, not a refused connection)

```
C:\Users\stefano.borini>ncat 192.168.1.1 12345
Ncat: .
```

As you can see, the error message is empty.

**Comment by dmiller-nmap** [comment]
This is because of lines like the following:

    loguser("%s.\n", socket_strerror(ETIMEDOUT));

`socket_strerror` calls `FormatMessageA`, but `ETIMEDOUT` is not a Winsock error (it should be `WSAETIMEDOUT`), so the message is blank. This is *supposed* to be handled in `nbase/nbase_winunix.h` by redefining the Unix code to the Winsock one, but it's not working for some reason. I'll investigate.

Another workaround might be to use Nsock's `nse_status2str` to get a status message, but that would only show "TIMEDOUT." Using `FormatMessageA` ought to give an error message in the language the user has configured.
