### ISSUE TITLE
Deal with Npcap name and version self-identification

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#134]
Right now we have our new Npcap self-installer npcap-0.01-setup.exe, but that version number 0.01 isn't anywhere in the code, and I think Npcap still thinks of itself as WinPcap 4.1.3.  We should probably find the places in the code which reference the version number and change it, and there should be an easy way to get the library name, so applications like Nmap know if they are dealing with WinPcap or Npcap.

**Comment by hsluoyz** [comment]
Commited in https://github.com/nmap/npcap/commit/49fb85ca79ae5d130017085408cb06f3f50a8054

Now, a software invoking WinPcap or NPcap can use pcap_lib_version() function to determine capture library's name and version programmatically.

There's a function pcap_lib_version() in wpcap.dll for both WinPcap and NPcap.
In WinPcap, this function will return a string like this: "WinPcap version 4.1.3 (packet.dll version 4.1.0.3001), based on libpcap version 1.0 branch 1_0_rel0b (20091008)"
While in NPcap, the string is like: "NPcap version 0.01 (packet.dll version 0.1.0.0), based on libpcap version 1.0 branch 1_0_rel0b (20091008)"

Note: the "true" version Windows only recognized is the one with four numbers like 0.1.0.0. So packet.dll version must be 0.1.0.0 instead of 0.01. We can just ignore the last two digits as they will always be zero.

**Comment by fyodor** [comment]
Great!  Let's include the WinPcap version too, like: "NPcap version 0.01 (packet.dll version 0.1.0.0), based on WinPcap version 4.1.3 (packet.dll version 4.1.0.3001), based on libpcap version 1.0 branch 1_0_rel0b (20091008)"

**Comment by hsluoyz** [comment]
Modified as you suggested, in https://github.com/nmap/npcap/commit/1fa3f03b49a5698820927f2345fbc29210bfe368
