### ISSUE TITLE
--stats-every options is not reliable on slow scans

### ISSUE THREAD

**Issue by ggabarrin** [nmap/nmap#1351]
According to the documentation, the `--stats-every <time>` option periodically prints a timing status message after each interval of <time>. The time is a specification of the kind described in the section called “Timing and Performance”; so for example, use --stats-every 10s to get a status update every 10 seconds. Updates are printed to interactive output (the screen) and XML output.

The following examples show nmap is not honoring that option in a strict manner when performing slow scans. To demonstrate this issue, a `-T1` timing template option was used in every example.

OS version: Ubuntu 18.04/Debian 8
Nmap version: 7.60

- Example 1: 

Nmap is configured to show stats every 1 second, and it started showing stats after 0:00:15 elapsed.

```
nmap <target> --stats-every 1s -T1 -Pn

Starting Nmap 7.60 ( https://nmap.org ) at 2018-10-10 10:20 -03
Stats: 0:00:15 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.00% done
Stats: 0:00:16 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:17 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:18 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:19 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:20 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:21 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
Stats: 0:00:22 elapsed; 0 hosts completed (1 up), 1 undergoing Connect Scan
Connect Scan Timing: About 0.05% done
<...>
```

Nmap showed stats at:
```
0:00:15
0:00:16
0:00:17
0:00:18
0:00:19
<...>
```

- Example 2

To slow the scan even more, the `-p-` (full port scan) option was added to nmap. This increases the overall time that the scan would take, and stats are being printed in a bigger time interval (approx. 15 seconds).

```
sudo nmap <target> -sS --stats-every 1s -T1 -p-

Starting Nmap 7.60 ( https://nmap.org ) at 2018-10-10 10:23 -03
Stats: 0:00:15 elapsed; 0 hosts completed (0 up), 1 undergoing Ping Scan
Ping Scan Timing: About 0.00% done
Stats: 0:00:15 elapsed; 0 hosts completed (0 up), 1 undergoing Ping Scan
Ping Scan Timing: About 100.00% done; ETC: 10:23 (0:00:00 remaining)
Stats: 0:00:30 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 0.00% done
Stats: 0:00:45 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 0.00% done
Stats: 0:00:46 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 0.00% done
Stats: 0:01:01 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 0.00% done
Stats: 0:01:16 elapsed; 0 hosts completed (1 up), 1 undergoing SYN Stealth Scan
SYN Stealth Scan Timing: About 0.00% done
<...>
```

Nmap showed stats at:
```
0:00:15
0:00:30
0:00:45
0:00:46
0:00:01
0:00:16
<...>
```

- Example 3

This last example is interesting, because if one adds the `-oX -` (print XML output to STDOUT) option to the command, nmap will **not show stats at all** after finishing with the ping task, at least not during the 5 minutes where the program was kept running.

```
time sudo nmap -sS <target> -T1 --stats-every 1s -p- **-oX -**

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 7.60 scan initiated Wed Oct 10 09:39:35 2018 as: nmap -sS -T1 -&#45;stats-every 1s -p- -oX - <target> -->
<nmaprun scanner="nmap" args="nmap -sS -T1 -&#45;stats-every 1s -p- -oX - <target>" start="1539178775" startstr="Wed Oct 10 09:39:35 2018" version="7.60" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="65535" services="1-65535"/>
<verbose level="0"/>
<debugging level="0"/>
<taskprogress task="Ping Scan" time="1539178790" percent="100.00" remaining="0" etc="1539178790"/>
<...>
```

The scan did not show any output at all after the ping scan task was done. After 5 minutes, the scan was terminated and the output of the “time” command shows the actual elapsed time, with no output whatsoever from nmap:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 7.60 scan initiated Wed Oct 10 09:41:41 2018 as: nmap -sS -T1 -&#45;stats-every 1s -p- -oX - <target> -->
<nmaprun scanner="nmap" args="nmap -sS -T1 -&#45;stats-every 1s -p- -oX - <target>" start="1539178901" startstr="Wed Oct 10 09:41:41 2018" version="7.60" xmloutputversion="1.04">
<scaninfo type="syn" protocol="tcp" numservices="65535" services="1-65535"/>
<verbose level="0"/>
<debugging level="0"/>
<taskprogress task="Ping Scan" time="1539178916" percent="100.00" remaining="0" etc="1539178916"/>


real	**5m6.275s**
user	0m0.110s
sys	0m0.014s
```

Thanks to @v8vito for helping with troubleshooting.

**Comment by dmiller-nmap** [comment]
Yeah, this looks like a bit of a mess, but it really does work. I did some digging, and here's what I found:

* The `--stats-every` option affects the lines beginning with "Stats:", and is only checked within the `keyWasPressed()` function from `nmap_tty.cc`.
* The `<taskprogress>` elements and the "Ping Scan progress" lines are produced by calling `printStats()` on an active `ScanProgressMeter` object.
* The scan engine (ultrascan) tells its `ScanProgressMeter` to print progress twice per loop: once at the beginning and once at the end. The one at the end depends on `keyWasPressed()` returning true, and so is triggered by the `--stats-every` interval. The one at the beginning is skipped if progress has been printed in the last 3 seconds (e.g. if the one at the end printed) or if progress is less than 0.003% (e.g. first iteration through the loop).
* When there is a send delay in effect (15 seconds in the case of `-T1`), the middle part of the loop will stall (sleep or `select()` looking for responses) until the delay expires, and key presses and stats timers will be ignored until the end of the loop.

So all of that together means that you can't get stats any faster than you send packets. If you slow packet sending down to fewer than 1 per second, `--stats-every` will not be honored more than once per second. To be fair, there won't be any progress made during that time, either, so they would just be duplicate stats.

Regarding stats not being printed to XML stream with `-T1`, the `printStats()` function only prints the percent complete, not estimated completion time, when the percent complete is less than 1%, in order to not print wild guesses at completion time. The XML `<taskprogress>` element is printed with the estimated completion, so it doesn't show up until that 1% mark, and 1% of 65535 ports is 655 ports. The `-T1` option limits Nmap to sending one probe every 15 seconds, so 655 probes would take over 2.5 hours.

As a fix action, I will add a `<taskprogress>` print without the estimated time complete to the place where progress is printed for less than 1% completion. I don't see how the rest of it can be improved.
