### ISSUE TITLE
Create EV-signed Npcap compatible with Windows 10

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#136]
For Windows 10 support, we need to sign Npcap with an EV cert instead of our current non-EV codesigning cert.  So we need to obtain such a cert, and it will probably only be available on a secure token so only one of us can do it.  And we then need to upload our EV-signed version to a Microsoft development site to get their signature.  And only then do we have an installer which Windows 10 users can run without doing the special unsafe driver mode thing (which requires a reboot, warning screens, etc.)

**Comment by hsluoyz** [comment]
I rechecked the EV cert stuff. I am surprised to find out that current NPcap driver CAN be successfully installed into Windows 10 Technical Preview 10102 x64 WITHOUT disabling "Driver Signature Enforcement". The reason turns out to be: "To ensure backwards compatibility, drivers which are properly signed by a valid cross-signing certificate that was issued before the release of Windows 10 will continue to pass signing checks on Windows 10." (see for details: http://blogs.msdn.com/b/windows_hardware_certification/archive/2015/04/01/driver-signing-changes-in-windows-10.aspx). As we already bought a one-year normal cert, it seems that we can use it for signing all-platform software currently, but we need to decide whether to buy another normal cert for several years to use, or just let the current cert expire and buy an EV cert next year. As Win10 release is coming on July 29, it left us nearly one month to make the choice.

**Comment by alagoutte** [comment]
Can be close ? (not need EV cert for Windows 10)

**Comment by hsluoyz** [comment]
Not really, EV cert is a necessity for Win 10 Anniversary, please refer to: https://github.com/nmap/nmap/issues/492

And this can be closed because Npcap 0.78 r5 is already EV-signed.
