### ISSUE TITLE
[Npcap] Compile source code of npcap, prompt error

### ISSUE THREAD

**Issue by BeiJingHaiDian12** [nmap/nmap#1380]
Hello Doctor
I use vs2015 Compile source code of npcap/packetWin7/npf, prompt error,my configuration is  Win7 Release(Winpcap Mode) and Platform is x64. I also install WinDDK，but I get error message. Please help me. Thank you.
vs2015 message：

     C2146  syntax error:missing ')' before identifier 'NDIS_HANDLE'
     C2085 'FilterModuleContext': not in formal parameter list

Sincerely,
DaiLong

**Comment by fyodor** [comment]
Thanks for your note.  If we see enough demand, we'll look into what more we can do through documentation, testing, and development to make Npcap easier to compile on more platforms, with different versions of the toolchain, etc.  Right now, almost all Npcap users use the binaries we provide because those are properly signed with Microsoft attestation, etc.

**Comment by BeiJingHaiDian12** [comment]
@fyodor     
Now I can compile it correctly，I can get npcap.sys，First I install Npcap use the binaries you provide，then I  replace the npcap.sys and reboot computer，but npcap driver can not  be registered，It`s will ok if I use your npcap.sys of package to replace again and reboot computer. 
my computer is  windows 7 X64. Platform I compiled is vs2015 in Release、X64 options. I don't know why I failed. Is it related to my compilation options?  I didn't change anything. I used the default.
can you give me some suggestion.  Thank you very much.

**Comment by BeiJingHaiDian12** [comment]
@fyodor   @majek  please  help
