### ISSUE TITLE
[Npcap] device name

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#1422]
Hello,

What is the rule behind the format of the device names ?

- According to https://github.com/nmap/npcap/blob/eb8b7221686d78c7863bd450267f14b131ce8abc/Common/WpcapNames.h#L127-L139 I believe that it should be `\\Device\\NPCAP_{...}` or `\\Device\\NPF_{...}` depending on if Winpcap mode is enabled.
- In practice, I always get `\\Device\\NPF_{...}` even with Winpcap mode is disabled, when asking `pcap_findalldevs` in the pcap_if.name, which is what is told in the docs https://nmap.org/npcap/guide/npcap-tutorial.html#npcap-tutorial-devlist
- The `Dot11Adapters` key is populated with `\\Device\{...}` (note the `NPF_` is missing), as specified by https://github.com/nmap/npcap/blob/eb8b7221686d78c7863bd450267f14b131ce8abc/packetWin7/NPFInstall/NPFInstall/WlanRecord.cpp#L313

Thanks !

**Comment by dmiller-nmap** [comment]
Thanks for the interesting question! I looked into this back in October, trying to speed up interface enumeration. Here's a rundown of what I found:

* The `NPCAP_{...}` names are devices created for Windows by the `npcap.sys` driver. The `NPF_{...}` names are created by the `npf.sys` driver (WinPcap API-compatible mode). The exact prefix strings don't matter as long as they do not conflict: two drivers cannot create separate devices with the same name.
* Some software (reportedly Wireshark) expects names returned from `pcap_findalldevs` to use the `NPF_` prefix. For this reason, Npcap in native mode translates the actual device names within Packet.DLL so that wpcap.dll (libpcap) reports the same `NPF_`-prefixed device names regardless of installation option.
* The `Dot11Adapters` key is not read by Npcap, only written. I'm not sure of the history or purpose of the key.

So that's the answer: different names at different API layers. Probably something worth documenting, but at least there's this Issue to refer to now.

**Comment by gpotter2** [comment]
Thanks for the detailed answer !

`Dot11Adapters` contains the list of raw 802.11 compatible interfaces, we use it to check an interface supports it before calling wlanhelper, it’s pretty useful. It might be worth updating it for consistency

**Comment by guyharris** [comment]
> * Some software (reportedly Wireshark) expects names returned from `pcap_findalldevs` to use the `NPF_` prefix.

There are currently places in Wireshark that assume that network adapter names, on Windows, have a `NPF_` prefix.  Should we change them to handle `NPCAP_` as well?
