### ISSUE TITLE
HTTP flag not present in output when a non standard HTTP port is scanned

### ISSUE THREAD

**Issue by vincentcox** [nmap/nmap#1426]
When NMAP finds a HTTP port it outputs `HTTP` after the port number and status (open/closed), like this:
![image](https://user-images.githubusercontent.com/9286611/50737811-9490db80-11cd-11e9-903b-1a4711dbcd4c.png)

Below is a screenshot of a HTTP service running on a very uncommon port, but it is running clearly a HTTP service:
![image](https://user-images.githubusercontent.com/9286611/50737874-ea658380-11cd-11e9-8e1c-7eade89661dd.png)
As you can see, the word `HTTP` is not present after the port and status (open/closed). 

I was wondering what the reason is why this is happening or if it's a bug in NMAP.

**Comment by dmiller-nmap** [comment]
Thanks for asking about this!

In your first example, Nmap has identified the HTTP server software as Apache 2.4. Because this is solidly a HTTP server and not something else with a HTTP-like protocol, Nmap assigns the service name `http`.

In your second example, Nmap was not able to get a solid fingerprint match. You can tell because there is nothing in the "VERSION" column of output, and the `fingerprint-strings` script has run (it only runs when Nmap fails to get a match). Instead, it pulled the `snet-sensor-mgmt` service name from the `nmap-services` database of port numbers and service names. Because it was only based on this table lookup, Nmap puts a `?` at the end.

Some services can be confidently identified as a particular protocol, even if the particular software is unknown. HTTP is not such a service: lots of other protocols are layered over HTTP or respond to HTTP requests even if that's not how they really work (MongoDB does this, for instance). So Nmap can't opportunistically identify those as `http` because that might prevent further probing which can positively identify the service.
