### ISSUE TITLE
[Feature Request] AppImage

### ISSUE THREAD

**Issue by zero77** [nmap/nmap#1429]
Can you please provide an AppImage, this is basically just a standalone portable executable for linux, that doesn't require installation.
Thanks

There are different ways to create AppImages:

    Use Open Build Service (OBS)
    Convert existing binary packages (.deb, .rpm, …)
    Bundling your Travis CI builds as AppImages
    Run linuxdeployqt on your Qt application
    Using electron-builder for Electron-based apps
    Create an AppDir manually

Documentation:
https://docs.appimage.org/packaging-guide/ways.html
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion. Nmap is primarily distributed as source code, though we provide compiled binaries for Windows and macOS because users of those systems do not tend to build their own software. For Linux, RPM packages are available with limited support, but most distributions maintain their own binary package based on Nmap source code. For containerized systems, I expect users or distributors to maintain their own packages as well, within the broad limits of the Nmap license.

**Comment by Chaz6** [comment]
I hope you will reconsider providing an AppImage for Linux users.
