### ISSUE TITLE
Travis CI: Abuse detected

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1494]
Travis CI is refusing to build nmap as new commits propagate from SVN to GitHub. The specific result is `Job rejected` with `Abuse detected`.

https://travis-ci.org/nmap/nmap/requests

Judging by build history, this issue might have first occurred on or after August 14, 2018.

https://travis-ci.org/nmap/nmap/builds

**Comment by dmiller-nmap** [comment]
I'll try to contact @travis-ci support to see if they can clue us in to why it's being flagged. Looks like they don't publicly disclose the kinds of things that trip their abuse sensors.

Unlikely to be related, but if you are making commits that don't contain things that affect the build (documentation changes, comments, etc), you can put `[ci skip]` in the commit message to [skip the build](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build). I hardly ever remember to do this, but it's probably a good idea to be courteous, since we're taking advantage of their free-for-open-source service.

**Comment by nnposter** [comment]
Am I correct that there is no value in invoking Travis if the commit is limited to `nselib` and/or `scripts`?

As an example, I have not noticed that `luac -p` gets called to assure basic syntax correctness. On the other hand, is that something that would be useful to start doing?

**Comment by fyodor** [comment]
I'm closing this since we have opened Issue #2768  for fixing Travis and/or migrating to a new CI/Testing system.
