### ISSUE TITLE
Nmap crashes on Windows 8.1 on Surface Pro 3

### ISSUE THREAD

**Issue by bonsaiviking** [nmap/nmap#15]
See http://seclists.org/nmap-dev/2014/q4/88

**Comment by rjk** [comment]
I also get nmap crashing when I run nmap on my Win 8.1 Surface Pro 3. I'm happy to test a debug build if that helps.

Event log message is: 

Faulting application name: nmap.exe, version: 6.0.2.0, time stamp: 0x53f67155
Faulting module name: wpcap.dll, version: 4.1.0.2980, time stamp: 0x51300419
Exception code: 0xc0000005
Fault offset: 0x0001b425
Faulting process id: 0x2c3c
Faulting application start time: 0x01d0364fbf81e0d9
Faulting application path: C:\Program Files (x86)\Nmap\nmap.exe
Faulting module path: C:\windows\SYSTEM32\wpcap.dll
Report Id: fd7f7c91-a242-11e4-829d-6002927a9912
Faulting package full name: 
Faulting package-relative application ID:

**Comment by dmiller-nmap** [comment]
@rjk I can give you a url to the debug build via email. Please email me: dmiller@nmap.org

**Comment by dmiller-nmap** [comment]
This is just a reminder that this issue is still open. It appears to be a problem with WinPcap, not Nmap's code, but we don't really have enough info to fully debug. Anyone looking to help can also get debugging info for WinPcap on their website:  http://www.winpcap.org/bugs.htm

**Comment by regexaurus** [comment]
Wondering if this bug was really fixed or has regressed?
I have Nmap 6.47 and WinPcap 4.1.3 on Windows 10 Pro Technical Preview (Build 10041). Nmap consistently crashes for any of the suggested commands listed in this thread:

http://seclists.org/nmap-dev/2014/q4/101

It also crashes for nmap --iflist, but not before it prints:

Starting Nmap 6.47 ( http://nmap.org ) at 2015-04-24 17:48 Eastern Daylight Time
************************INTERFACES************************
DEV  (SHORT) IP/MASK                                TYPE        UP   MTU  MAC
eth0 (eth0)  fe80::71ee:f1a9:2265:7822/64           ethernet    down 1500 00:21:6A:61:A9:FF
eth0 (eth0)  169.254.120.34/4                       ethernet    down 1500 00:21:6A:61:A9:FF
eth1 (eth1)  fe80::f16a:b24c:a705:f616/64           ethernet    up   1500 00:26:B9:D9:A6:75
eth1 (eth1)  10.1.10.3/24                           ethernet    up   1500 00:26:B9:D9:A6:75
eth2 (eth2)  fe80::8b0:27ad:a73e:9c90/64            ethernet    down 1500 00:21:6A:61:A9:FE
eth2 (eth2)  169.254.156.144/4                      ethernet    down 1500 00:21:6A:61:A9:FE
lo0  (lo0)   ::1/128                                loopback    up   -1
lo0  (lo0)   127.0.0.1/8                            loopback    up   -1
tun0 (tun0)  2001:0:9d38:6abd:1416:2c3b:f5fe:f5fc/0 point2point up   1280
tun0 (tun0)  fe80::1416:2c3b:f5fe:f5fc/0            point2point up   1280
tun1 (tun1)  fe80::5efe:a01:a03/128                 point2point down 1280

In the application event log, I see event ID 1000 entries of the sort:

Faulting application name: nmap.exe, version: 6.0.2.0, time stamp: 0x53f67155
Faulting module name: wpcap.dll, version: 4.1.0.2980, time stamp: 0x51300419
Exception code: 0xc0000005
Fault offset: 0x0001b425
Faulting process id: 0x81c
Faulting application start time: 0x01d07ed66d9892e9
Faulting application path: C:\Program Files (x86)\Nmap\nmap.exe
Faulting module path: C:\WINDOWS\SYSTEM32\wpcap.dll

**Comment by dmiller-nmap** [comment]
@regexaurus Sorry for the confusion. This bug has been fixed in development, and will be fixed in the next release. You can read more in the nmap-dev thread referenced in the fix commit: http://seclists.org/nmap-dev/2015/q1/178
