### ISSUE TITLE
chrome OS:  Is there any port open in chrome os? some way to get this OS and its version?

### ISSUE THREAD

**Issue by kbai-sti** [nmap/nmap#1500]
Hello.

I'm trying to generate a computer inventory automatically using nmap in an institute.

For windows it recovers enough information. ip, mac address, OS version, open ports, services, smb information, ...

For chrome OS nothing and neither for android, it does not find open ports.

Thank you in advance.

**Comment by dmiller-nmap** [comment]
Nmap needs to find at least 1 open port in order to have enough information to make a guess at the target operating system (network stack). By default, Nmap scans 1000 common ports to find listening network services (open ports). If none of these 1000 ports are open, you can retry your scan with more ports. For example, you could try `nmap --top-ports 10000 -O` which would scan the top ten thousand ports according to frequency of use. Or you could use `nmap -p - -O` which scans all 65535 TCP ports.

Even still, you may find some hosts that do not have any listening services. This is because they participate in the network as clients only, and not as servers. There is not much else that can be done in this case, though you may be able to gather information from other sources, such as passive observation of network traffic or correlation of MAC address with hardware manufacturer. [p0f](http://lcamtuf.coredump.cx/p0f3/) is a good passive OS fingerprinter for this type of thing.
