### ISSUE TITLE
ssh-auth-methods doesn't read port parameter

### ISSUE THREAD

**Issue by willem-tee** [nmap/nmap#1521]
If you want to launch this script against a service located in port 2222 for example, the script will be ignored and default to 22: 

`nmap -p2222 --script=ssh-auth-methods IP`

If you change line 28 of this script, from 22 to the receiving port, it does work tho. It is hardcoded as it is, would be nice to have it read the parameter given.

Tested in Kali x64 - Nmap Version 7.70

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. This is the correct and intended behavior. NSE scripts run conditionally based on the output of [the "rule" function](https://nmap.org/book/nse-script-format.html#nse-format-rules), which must return `true` in order for the script to run. In the case of `ssh-auth-methods`, the rule uses the `shortport.port_or_service()` function to indicate that it should run on port 22, or on any port identified as running the "ssh" service.

In your command, you have not given NSE any way to know that port 2222 (registered with IANA as "EtherNet/IP-1") is hosting a SSH server. There are two ways you can ensure the script is run in this case:

1. You can add the `-sV` option so that Nmap performs service and application version detection. This will change the "service" attached to the port to "ssh" and allow the script to run, or
2. You can prepend a "+" to the name of the script to force it to run on all scanned ports. For a single-port check where you know the service that is running, this is a handy shortcut. For broader scans, this is not recommended, since it will run the script against every open port regardless of whether it is SSH or not.

**Comment by willem-tee** [comment]
Well that was very enlightening :) thanks dmiller!
