### ISSUE TITLE
npcap 0.99-r9 BSOD

### ISSUE THREAD

**Issue by Oryteclin** [nmap/nmap#1533]
I've installed npcap with wireshark 3.0.0. I get BSOD everytime I try to start PPPoE connection or create the new one.

**Comment by dmiller-nmap** [comment]
Thanks for the bug report! While we've fixed a few BSODs in the 2 versions since 0.99-r9, I'm not aware of any that involve PPPoE connections. Can you follow the directions in the Npcap User's Guide for [gathering information to complete your bug report](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-issues) and include the crash minidump for debugging purposes? Thanks!

**Comment by dmiller-nmap** [comment]
Closing this issue due to no followup. If the problem persists in the latest version, please open a new issue.
