### ISSUE TITLE
Missing output / not working script smb-check-vulns

### ISSUE THREAD

**Issue by kranko** [nmap/nmap#156]
smb-check-vulns.nse is supposed to check for MS08-067.

Either it does not check, or the output is missing:

nmap --script=smb-check-vulns 192.168.19.227 -p139,445,135 --script-args=unsafe=1

Starting Nmap 6.47 ( http://nmap.org ) at 2015-06-07 19:26 CEST
Nmap scan report for 192.168.19.227
Host is up (0.095s latency).
PORT    STATE SERVICE
135/tcp open  msrpc
139/tcp open  netbios-ssn
445/tcp open  microsoft-ds
MAC Address: 00:50:56:AF:7D:E9 (VMware)

Host script results:
| smb-check-vulns: 
|   Conficker: UNKNOWN; got error SMB: ERROR: Server returned NT_STATUS_PIPE_NOT_AVAILABLE too many times; giving up.
|   regsvc DoS: NOT VULNERABLE
|   SMBv2 DoS (CVE-2009-3103): NOT VULNERABLE
|   MS06-025: NO SERVICE (the Ras RPC service is inactive)
|_  MS07-029: NO SERVICE (the Dns Server RPC service is inactive)

Nmap done: 1 IP address (1 host up) scanned in 45.59 seconds

**Comment by dmiller-nmap** [comment]
When one of the checks encounters an error (which for MS08-067 may be due to the BROWSER service being inaccessible), it will not produce output unless you are running in debugging mode with `-d`. If you believe there is a problem with the MS08-067 check, please file a separate bug report for that issue. Thanks!
