### ISSUE TITLE
Npcap 0.992 lost net connection

### ISSUE THREAD

**Issue by wsjcdp** [nmap/nmap#1578]
Hello,

I've lost network connection between WIN10 Prepar3D V4.5 and iPad ForeFlight. Been using Wireshark-win64-3.0.1 and WinPcap_4_1_3 without problem until switched to Npcap 0.992 some time ago. Uninstalling Npcap 0.992 and adding WinPcap_4_1_3 fixed the problem. Prepar3D V4.5 network connects to Foreflight OK.

Is there a way to setup Npcap 0.992 to allow network connection between Prepar3D V4.5 and Foreflight?

Regards,
Bill

**Comment by fyodor** [comment]
Hi.  I'm sorry nobody specifically addressed your issue report in the last year since it was filed, but we have made major improvements to Npcap in the meantime.  If you get a chance to try Npcap 0.9991, there is a good chance it will work for you.  And if not, please file a new bug so we can investigate further.  Thanks!
