### ISSUE TITLE
Npcap 0.995 Has Not Resolved my IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by MatahachiHoneyBun** [nmap/nmap#1598]
When attempting to install 0.995, my PC still crashes with the IRQL_NOT_LESS_OR_EQUAL error, unfortunately. 

I wish to remove Npcap entirely; uninstalling only results in a crash with the same error. I figured I would install 0.995 as it said to resolve this issue, but that does not seem to be the case - for me, at least.

**Comment by MatahachiHoneyBun** [comment]
To clarify, I essentially cannot alter the status of the Npcap Loopback Adapter in any way without my PC crashing. Disabling the driver results in a crash, attempting an update or reinstall results in a crash. Simply disabling the driver results in an unavoidable crash. 

I feel as though I'm stuck with something I no longer need or necessarily want.

**Comment by dmiller-nmap** [comment]
We saw similar behavior in one test system, but only with Driver Verifier turned on. There are no known crashes in Npcap 0.995, but previous versions may crash on driver unload. Since the old version has to be unloaded in order to install the new version, you have to take extra steps to avoid the crash when doing the upgrade:

1. Disable the Npcap driver service by running this command in an Administrator command prompt: `sc.exe config npcap start= disabled`
2. Reboot the computer. The Npcap service will not be running.
3. Install Npcap 0.995.
