### ISSUE TITLE
Please fix this npcap thing.

### ISSUE THREAD

**Issue by mikeouwen** [nmap/nmap#1621]
Today I installed Wireshark to check my wifi traffic. And Npcap comes with it. After installing, I found my VPN software, Astrill, is not working anymore. NO TRAFFIC GOING THROUGH at all. So I figured It must be the problem of Wireshark or Npcap. 

After uninstalling Wireshark, which also calls the uninstalling process for Npcap along the way, Astrill is still not working. What's even more strange and frustrating is that I can see that Npcap loopback adapter is still there, laughing at me.

So I went to Device Manager to uninstall that adapter and guess what. It gives me BSoD everytime I do it. Jesus. I was just trying to solve a single problem, which against my will introduced even more problems.

So I googled it for a long time and found someone with the same problem. He solved it by uninstalling the adapter in the Safe Mode. Luckily, this also worked out for me. But still, Astrill is still not working after the adapter is gone in the device manager. And there is something even stranger about it.

I found out that Npcap directory is still there sitting inside the default install directory, with some of its files still intact, laughing at me again. (I'll attach a screeshot later). When I tried to reinstall Wireshark, hoping that uninstalling it after would likely do a full clean-up, the installer told me that I already have Npcap installed. I'm dying slowly inside.

After that I also downloaded the seperate installer from Npcap to install it. Again even doing this will give me a BSoD. 

So this whole thing is in a state of Schrodinger's Npcap. You can't see the loopback adapter in the Device Manager. But lots of signs shows that it is still there. Trying reinstalling it gives my BSoD. And my VPN Astrill is totally paralyzed by this. 

Please show me a way to fix this mess.
![image](https://user-images.githubusercontent.com/6271251/59012478-2e86ae00-886a-11e9-9da9-107868bfcf7a.png)

**Comment by kd4pba** [comment]
I just went through the same thing about the same time you did.  

That said, you will need to go into safe mode without networking, in Windows.  

Once you are in safe mode without networking, Open device manager, and under network adapters locate "npcap loopback" and delete it.  Also delete any references of npcap in device manager. Do not do this outside of safe mode or it will BSOD again.  Make sure you uninstall wireshark as well.  

This needs to be addressed this is obviously broken, broken being an understatement.  I crashed 2 boxes due to this and had to reset one due to a trashed file system.   Never again.  I will only run Wireshark on Linux or OSX.  

Hope that helps.

**Comment by gvanem** [comment]
One could just un-check the *Install Npcap 0.995* box while running the `WireShark*.exe` installer:
![Wireshark-NPcap](https://user-images.githubusercontent.com/945271/59033700-95579780-8869-11e9-8dc5-88c22d7ec441.png)

And make sure one have installed WinPcap first (or do it afterwards?).

> Today I installed Wireshark to check my wifi traffic.

Why isn't WinPcap good enough for this?

**Comment by ThOhT** [comment]
My problem is the error message about "NMap: Failed to open device ethX". I used the npcap default (installed with zenmap) and changed later for the latest version 0.995, but it's still not working.

Now I have a greater problema with the BSoD while trying to uninstall the npcap. This error occurs when the uninstaller is trying to stop the npcap driver.

**Comment by mikeouwen** [comment]
> One could just un-check the _Install Npcap 0.995_ box while running the `WireShark*.exe` installer:
> ![Wireshark-NPcap](https://user-images.githubusercontent.com/945271/59033700-95579780-8869-11e9-8dc5-88c22d7ec441.png)
> 
> And make sure one have installed WinPcap first (or do it afterwards?).
> 
> > Today I installed Wireshark to check my wifi traffic.
> 
> Why isn't WinPcap good enough for this?

Thanks for the solution. 

Like solving any other software problems, I tried many different solutions without knowing exactly the reasoning behind them, which makes me feel that I'm doing some kind of mystical ritual sitting in front of a computer, and finally was able to remove it completely (at least that's what I think). My VPN is also working normally.

I have basically zero experience on how to sniff the traffic. So I just went with the default solution Internet gives me. Google gives me Wireshark as a default solution for analyzing traffic and Wireshark gives me Npcap as a default solution for helping it out. I guess my problem is that I just want to enjoy the benefit of this amazing software technology without wanting to understand and appreciate the nuances and downsides beneath it. 

Npcap also says itself is better in many ways than WinPcap in its official website. I think I try to learn more.

**Comment by kd4pba** [comment]
Not checking the box to install it when installing wireshark is like saying pull out instead of using a condom after the girl is pregnant.  The damage was done already.  

I went through this nightmare and eventually had to reset the box because it was trashed.  Yes I realize its free software and yes I realize things can go wrong. I think the larger issue is why is npcap causing BSOD issues in the first place.    If it causes such a serious issue why is wireshark still bundling it.  

This is not like a functionality bug where it simply does not work correctly, its screwing up systems and causing them to lock up.   Everywhere I have ever worked considered things like that a P1 situation.

**Comment by dmiller-nmap** [comment]
Npcap 0.994 and 0.995 have a pair of related bugs (#1626, #1598) that in some cases cause a crash when stopping the driver service. We have a fix for this issue in testing and hope to release it soon. The new installer will prompt you to take some extra steps to allow Npcap 0.995 or 0.994 to be safely removed before installing Npcap, which will require a reboot. We apologize for the inconvenience.

In the meantime, here is a procedure for safely removing Npcap. After it is removed, the best option is to install Npcap 0.993, which is unaffected:

1. Disable the `npcap` and `npf` driver services: In an Administrator command window, run `sc.exe config npcap start= disabled` and `sc.exe config npf start= disabled`
2. Reboot the computer. Npcap will be disabled and unavailable.
3. Uninstall Npcap via the "Add or remove programs" control panel. This ought to remove the loopback adapters, but the next step will ensure they are removed.
4. Open Device Manager (`devmgmt.msc`) and expand Network Adapters. Right-click any "Npcap Loopback Adapter" and choose "Uninstall device." Repeat for each Npcap Loopback Adapter to remove it.

Please be patient as we prepare and test the next Npcap release to address these issues.

**Comment by dmiller-nmap** [comment]
This issue is resolved in Npcap 0.996, released today. https://npcap.org/#download

Because Npcap 0.995 consistently crashes some systems, the Npcap 0.996 installer will offer to disable the `npcap` driver service on the next boot so that the installation can be reattempted. You can also manually disable it by running (as administrator) `sc.exe config npcap start= disabled`. There may be one more crash when trying to restart, unfortunately, but it will be the last one.
