### ISSUE TITLE
IRQL_NOT_LESS_OR_EQUAL error npcap loopback adapter

### ISSUE THREAD

**Issue by EmpireFall** [nmap/nmap#1632]
I installed both npcap 0.955 and nmap 7.70 (the latter comes bundled with an earlier version of npcap) that caused my computer to get bluescreen errors

this is the 21st century, I need my computer to work without getting bluescreened over the most minute operation, tried installing a network related driver > bluescreen, restart or shutdown the computer > bluescreen, attempt to reset the computer > bluescreen, you must be kidding me!

the developers npcap and nmap need to take responsibility for this catastrophic software so that other people do not get affected, it should not be accessible to your average user, this issue has caused me to lose a lot of data that I was working on and aggravation to get removed

those crooks even closed an issue prematurely as an attempt sweep the problem underneath the rug https://www.github.com/nmap/issues/589

do not install any version of this malware, it will cripple your computer

**Comment by dmiller-nmap** [comment]
I'm sorry you had a bad experience with Npcap. The majority of users have not experienced this crash, but we have identified the cause and will be releasing the fix as soon as it passes our testing procedures. The issue that you mentioned being closed "prematurely" was originally opened three years ago, and has no relation to the current issue you are experiencing. We locked that issue to avoid confusion.

If you need a solution prior to the release of Npcap 0.996, you can disable the Npcap service following the procedures at https://github.com/nmap/nmap/issues/1621#issuecomment-501056727, safely uninstall, and reinstall Npcap 0.993, which is the stable version currently being served at https://npcap.org/#download

**Comment by dmiller-nmap** [comment]
This issue is resolved in Npcap 0.996, released today. https://npcap.org/#download

Because Npcap 0.995 consistently crashes some systems, the Npcap 0.996 installer will offer to disable the `npcap` driver service on the next boot so that the installation can be reattempted. You can also manually disable it by running (as administrator) `sc.exe config npcap start= disabled`. There may be one more crash when trying to restart, unfortunately, but it will be the last one.
