### ISSUE TITLE
Npcap causes a lot of blue screens in Win 10 (unistalling)

### ISSUE THREAD

**Issue by sanadros** [nmap/nmap#1635]
I recently installed an update with wireshark and with that also Npcap Lookup Adapter (V 0.995). The I saw that my LTE Mobile is no more working correctly as it connects to my provider but I can't connect to internet (some Sierra Wireless Adapter). So I wanted to uninstall Npcap but I got a blue screen. I wanted to do a diagnosis with Windows (down on the taskbar) - blue, I wanted to to diagnosis directyl on the adapter (in network connection) - blue, I wanted to install another Ncap (V 0.993 https://nmap.org/npcap/#download) - blue, I wanted to start windows in the secured mode - blue and windwos starting normaly. How can I fix my issue?

**Comment by dmiller-nmap** [comment]
This issue has been previously reported, and is resolved in Npcap 0.996, released today. https://npcap.org/#download

Because Npcap 0.995 consistently crashes some systems, the Npcap 0.996 installer will offer to disable the `npcap` driver service on the next boot so that the installation can be reattempted. You can also manually disable it by running (as administrator) `sc.exe config npcap start= disabled`. There may be one more crash when trying to restart, unfortunately, but it will be the last one.

The issue of Npcap interfering with Sierra Wireless adapters has been previously reported: #1497.

**Comment by sanadros** [comment]
Can we open that case again? I tried to install the new Npcap driver which u linked but executing it got me a bluescreen when it tried to unistall the existing driver. Also the work arround with the Sierra Wireless adapter got me a blue screen.

**Comment by sanadros** [comment]
OK #1577 helped me to uninstall npcap.
