### ISSUE TITLE
Can't locate hosts on LAN

### ISSUE THREAD

**Issue by Al-Karid** [nmap/nmap#1646]
I just spend 45 min trying to detect open ports from another computer via mine and vise versa. Thought issue was linked to **sudo ufw allow --pnumber--** not working. It was actually nmap not seeing the open ports.. great waste of time.

I got it (**nmap**) installed tonight for the work.

**Comment by bka-dev** [comment]
Honestly, there's a lot of information missing here:

Is the network configured to disallow client-to-client communication? Are there any open ports at all of which you are aware? Are the hosts blocking ICMP and you didn't specify the -Pn parameter?

Please paste the complete command line including its output here, otherwise it's very difficult to figure out what the problem is

**Comment by fyodor** [comment]
There is not really enough information for us to go on here, and the OP has not answered @bka-dev's smart followup questions, so I'm closing the issue.
