### ISSUE TITLE
OpenSSL bignum_num_bits / bignum_num_bytes return float

### ISSUE THREAD

**Issue by nnposter** [nmap/nmap#1647]
Should not the following code in `nse_openssl.cc` be using `lua_pushinteger` instead of `lua_pushnumber`?
```c
static int l_bignum_num_bits( lua_State *L ) /** bignum_num_bits( BIGNUM bn ) */
{
  bignum_data_t * userdata = (bignum_data_t *) luaL_checkudata(L, 1, "BIGNUM");
  lua_pushnumber( L, BN_num_bits( userdata->bn) );
  return 1;
}

static int l_bignum_num_bytes( lua_State *L ) /** bignum_num_bytes( BIGNUM bn ) */
{
  bignum_data_t * userdata = (bignum_data_t *) luaL_checkudata(L, 1, "BIGNUM");
  lua_pushnumber( L, BN_num_bytes( userdata->bn) );
  return 1;
}
```
One effect of the floats is on `bits` returned by `ssh2.lua`:
```xml
<elem key="bits">2048.0</elem>
```
The alternative, sprinkling Lua code with `math.floor`, seems like a poor hack.

**Comment by dmiller-nmap** [comment]
Yes, I think so. This code predates the Lua 5.3 upgrade which added integer types, so it was probably overlooked then. Since the numbers being pushed are integers originally, this shouldn't be a problem. I'll take a look at other uses of `lua_pushnumber` in NSE libs to see if we can use integers there, too.
