### ISSUE TITLE
NPCAP - Breaks connection over mobile net adapter (DW5811a Snapdragon X7 LTE)

### ISSUE THREAD

**Issue by sgel83** [nmap/nmap#1651]
After installing Wireshark with NPCAP 0.992 on Windows 10, my mobile network adapater no longer has internet access.  

Interestingly, it gets an IP, it sets up routes, but you cannot ping even the other side of the tunnel.  Ping returns a General failure.  

Removing NPCAP and restarting the computer fixes it.

Unchecking NPCAP in the connection properties of the adapter has no affect, a full uninstall needs to happen.

What diagnostics would be usefull here?

**Comment by dmiller-nmap** [comment]
Thanks for the report! We're tracking a similar problem with a Sierra Wireless mobile adapter over at #1497, and we've gotten a [report on Twitter as well](https://twitter.com/majornetwork/status/1146115272039944192). In that case, reinstalling Npcap without the loopback adapter was sufficient to solve the problem. Does this solve it for you as well?

We are investigating alternative methods of providing loopback capture and injection support that do not involve an adapter, since this has been a source of many problems. In the case of mobile adapters, I believe it has to do with routing metrics, but manually setting high metrics for the Npcap Loopback Adapter does not fix the issue; Windows may be doing something "smart" to prefer non-metered connections.

**Comment by sgel83** [comment]
@dmiller-nmap - this is exactly the same problem and the same card.  I will reinstall and get some diagnostics for you.

**Comment by sgel83** [comment]
@dmiller-nmap 

Diags are attached.

The work around does not work, if you just go into the Mobile Adapter Properties and uncheck either or both NCAP drivers the failure still exists.  If you disable the NPCAP Loopback adapter it will work.

[DiagReport-20190704-112136.txt](https://github.com/nmap/nmap/files/3358633/DiagReport-20190704-112136.txt)

Let me know if there is anything else I can do to help you further.

**Comment by monofox** [comment]
Same issue on Windows 10 Enterprise, Version 1903 with a Fibocom L830-EB
[DiagReport-20190720-180825.txt](https://github.com/nmap/nmap/files/3413780/DiagReport-20190720-180825.txt)

Disabling "Npcap Packet Driver (NPCAP)" for the cellular network adapter is not enough. As @sgel83 mentioned, it is necessary to completely disable the loopback adapter.

**Comment by bakadave** [comment]
I second everything @monofox has mentioned before me. Unticking Npcap Packet Driver (NPCAP) on the WWAN adapter does not solve the problem. When disabling Npcap Loopback Adapter WWAN works. Feel free to contact me for details.

config:

- Win10 x64 1903
- Sierra Wireless EM7455

**Comment by dmiller-nmap** [comment]
Thanks everyone who reported this issue. I do not see a clear answer to whether installing without loopback support fixed the connectivity issue, so could someone respond so we know whether this is still a problem?

Npcap 0.9983, released today, does not require the Npcap Loopback Adapter in order to do loopback packet capture and injection. Be sure to deselect (un-check) the "Legacy loopback support" and let us know if that solves this problem.

**Comment by bakadave** [comment]
based on cursory test it seems to be working

I still can't sniff data on WWAN interface but since that was never really my goal, I am satisfied with the new version.

**Comment by sgel83** [comment]
@dmiller-nmap 

As per your instructions and as @bakadave has stated, it works but there is no possibility to capture on the mobile adapter.

**Comment by dmiller-nmap** [comment]
Glad to hear it! I think we have described the capture problems at #1573 , so you can track the progress there.
