### ISSUE TITLE
No flow preview in Wireshark 3.0.3 after install npcap 09981

### ISSUE THREAD

**Issue by tan-wei** [nmap/nmap#1668]
As the image shown below, the flow preview curve is flat after install npcap 09981 intead of npcap 0995. It's not correct, because many packets are sent and received now.
![图片](https://user-images.githubusercontent.com/28227509/61888544-414a6480-af36-11e9-8741-35556f277052.png)
It's quite wired that I try to uninstall npcap 09981 and install npcap 0995, no interfaces are shown in wireshark.

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. I believe there may be a regression in packet statistics reporting, so I will be looking into that, assuming that is how these flow curves are generated.

**Comment by dmiller-nmap** [comment]
Additionally, if this is important enough of an issue that you wish to install an older version of Npcap, please use Npcap 0.996, since there is a significant bug in 0.995 that can crash Windows. Older versions are available at https://nmap.org/npcap/dist/?C=M;O=D

**Comment by dmiller-nmap** [comment]
Thanks so much for the fast report! Since we changed IOCTL codes in 0.9981, the IOCTL for getting packet statistics was using the wrong I/O method. This will be fixed in the next release. We will be adding additional tests to ensure packet stats functionality works correctly in all future releases. Thanks again!

**Comment by tan-wei** [comment]
Thanks for the quick reply. I think I can wait for the new release which can fix this bug. :-)
