### ISSUE TITLE
npcap creates same mac address (loopback device) on every computer

### ISSUE THREAD

**Issue by jszabo98** [nmap/nmap#1679]
npcap seems to create the same mac address for the loopback device on every computer it's installed on.

**Comment by jr0792** [comment]
This is not an issue with Nmap, it is just how the OSI layers work. What you are seeing is the MAC address of the router that the computers are plugged into. Look into the Data Link (Frames) layer vs the Network (Packets) layer. There is a ton of information online available that explains it.

**Comment by jszabo98** [comment]
The thing is, in the management software that I use for computers at a school, with Wireshark with Npcap installed, the computers overlap with each other in the console.  Not installing the loopback device resolves the issue.

**Comment by xautshuanglong** [comment]
I also have the same doubt about whether the MAC address is fixed at 02-00-4C-4F-4F-50

**Comment by jszabo98** [comment]
Hmm, 02-00-4C-4F-4F-50 is the mac address of the loopback device on my computer.  I also found this in npcap-master\docs\npcap-devguide.xml:      

> The MAC address of <quote>Npcap Loopback Adapter</quote> is usually like 02:00:4C:4F:4F:50.

**Comment by dmiller-nmap** [comment]
@jszabo98 This is a flaw in your management software, then. MAC addresses are not globally unique, though they are unique enough that there is basically no chance of a conflict on any given Ethernet link. Since the Npcap Loopback Adapter is not able to connect to any network link, it does not need a unique MAC address.

We are currently testing some different schemes that may allow loopback traffic capture without an OS-managed virtual network adapter, so that will hopefully solve this and several other issues that have been reported surrounding the Npcap Loopback Adapter.
