### ISSUE TITLE
Npcap Bug Report

### ISSUE THREAD

**Issue by bilgini** [nmap/nmap#1698]
Npcap loopback adapter is blocking my wifi adapter. You can find the diag report as attached. 

Kind regards,

[DiagReport-20190819-093221.txt](https://github.com/nmap/nmap/files/3514510/DiagReport-20190819-093221.txt)

**Comment by dmiller-nmap** [comment]
Thanks for reporting this. We have known for a while that the Npcap Loopback Adapter conflicts with certain network management software, which is why Npcap 0.9983, released today, no longer requires it to be installed. Loopback capture and injection are supported natively, with only a few changes being necessary for most software. Nmap 7.80 still requires the legacy loopback adapter, but Wireshark does not.

Please upgrade to Npcap 0.9983 and un-check (deselect) the "Legacy loopback support" option in order to fix your WiFi connection.
