### ISSUE TITLE
Npcap 0.995 fails 3G internet connectivity on  Huawei E367 3G Modem

### ISSUE THREAD

**Issue by 0802gielo** [nmap/nmap#1703]
I have installed Npcap version 0.995 as part of the Wireshark Bundle version 3.0.3. With Npcap installed my Huawei 3G modem will connect to the service provider, but no data will be exchanged in any direction. I tried Opera, Mozilla, Chrome which all gave the save behavior. When I uninstalled Npcap everything was fine. As a workaround I had to instal Winpcap which works fine.
The PC I am using is a Dell 5590, Windows 10 (1803)

**Comment by dmiller-nmap** [comment]
Thanks for the report. Does the problem persist with Npcap 0.9983, released today? Be sure to deselect (un-check) the "Legacy loopback support" unless you know that you need it, since it has been linked to connectivity problems with certain network management software.

This may be the same issue as #1651, since it affects a 3G wireless card.

**Comment by 0802gielo** [comment]
Thanks for the feedback, I appreciate it. Will test

**Comment by 0802gielo** [comment]
Hi Daniel

I have downloaded the suggested version of Npcap 0.9983 and tested it with
the E367 -3G card and can confirm that the problem is resolved. Thanks a
lot for the response. You can close the case now.

Kind Regards
Giel Oberholster

**Comment by fyodor** [comment]
Thanks for the update, Giel.  That's great news!
