### ISSUE TITLE
Npcap Bug Report: Cannot use enforced option in installer

### ISSUE THREAD

**Issue by declanmarks** [nmap/nmap#1719]
When trying to install npcap from command line, when I use the enforced option, it doesn't do anything. When the installer runs the check boxes are unchecked. I am trying to set admin only to enforced.  All the options disabled, yes and no all work fine. 

This issue has been present in 0.995, 0.996 and 0.9982. I haven't tried earlier versions. I am trying to deploy this software in SCCM as part of wireshark.

**Comment by dmiller-nmap** [comment]
Thanks a lot for this bug report! I reviewed the installer code and it doesn't look like this intended feature was ever functional. I'm adding it to the release planned for later today, so it should work fine for future releases.

As a side note, we're hoping in upcoming releases to improve access control for capture and injection to avoid needing a separate "admin only" installation option. Users often complain, especially with Wireshark, that the UAC prompts required for Builtin Administrator elevation are excessive, since Wireshark launches a separate `dumpcap.exe` process for each traffic graph in the interface listing when it starts up.

**Comment by dmiller-nmap** [comment]
Please try Npcap 0.9983, which now support the "enforced" installer options.
