### ISSUE TITLE
Can't resume scan from big file

### ISSUE THREAD

**Issue by kxmp** [nmap/nmap#1742]
File size is 2.1GB (2154678107b)
I'm using nmap v7.70 on debian. 
It's installed on apt.
If I resume from 2.1g file it show error immediately.

When I resume I just got 
Output file xxx is too short -- no use resuming
QUITTING!

System version Linux VM 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux

I truncated size to 2145678000 then it read for a while then show error.

2019-09-16 12:34:17
OMGOMGOMG It's my disk space is near 100% I'm gotcha test it again.
Disk usage 85% now But still show error immediately. Well I moved file to another drive which is I'v said it before it's "2145678000" size file.(It drive is only 7% used) It read for some time but then show error again.
So it's not the disk space problem.

**Comment by dmiller-nmap** [comment]
We had an integer overflow in the file size, so I just pushed a change to use 64-bit integers instead. This still will have a problem if the file size is greater than 9.22 exabytes, but I think it's probably big enough.

Since I don't have a scan file large enough at the moment to test, please let us know if you run into more problems with the updated code (this issue will be updated when the code is pushed, within an hour).

**Comment by kxmp** [comment]
Problem solved. It works fine now :D

**Comment by kxmp** [comment]
Problem solved. It works fine now :D
