### ISSUE TITLE
npcap documentation has link to missing file

### ISSUE THREAD

**Issue by chmorgan** [nmap/nmap#1747]
https://github.com/nmap/npcap/blob/a7ad0a09f783affcf48f0be5a41383c899886922/docs/npcap-tutorial.xml#L210-L211

<para>The function that opens a capture device is <ulink
        url="wpcap/pcap_open.htl">pcap_open()</ulink>. The parameters,
      <literal>snaplen</literal>, <literal>flags</literal> and
      <literal>to_ms</literal> deserve some explanation.</para>

From this page https://nmap.org/npcap/guide/npcap-tutorial.html, the link in the docs is broken, https://nmap.org/npcap/guide/wpcap/pcap_open.htl

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out!

**Comment by guyharris** [comment]
https://nmap.org/npcap/guide/wpcap/pcap_open.html is also a broken link.

Part of the problem is that there's no libpcap pcap_open() man page; perhaps I should write one.  (Once I add remote capture support to the create/activate API, pcap_open() will be redundant, but a pcap_open() man page might be useful until that happens.)
