### ISSUE TITLE
Random port sequence, -r not honored

### ISSUE THREAD

**Issue by sguillia** [nmap/nmap#1750]
**Issue type: Bug**

Hi

I want to scan several ports in a specific order, so I'm using the `-r` option.

From `man nmap`:
> -r: Scan ports consecutively - don't randomize

Let's try
```
$ strace nmap -Pn --host_timeout 201 --max-retries 0 -r -p 2222,1111,3333 $HOST |& grep connect
...
connect(4, {sa_family=AF_INET, sin_port=htons(1111), sin_addr=inet_addr("34.249.126.183")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(5, {sa_family=AF_INET, sin_port=htons(2222), sin_addr=inet_addr("34.249.126.183")}, 16) = -1 EINPROGRESS (Operation now in progress)
connect(6, {sa_family=AF_INET, sin_port=htons(3333), sin_addr=inet_addr("34.249.126.183")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

I'm using this for SSH port knocking.
When using the command above, I can't connect to my server.
When using the commands below, it works.
```
$ nmap -Pn --host-timeout 201 --max-retries 0 -p 2222 $HOST
$ nmap -Pn --host-timeout 201 --max-retries 0 -p 1111 $HOST
$ nmap -Pn --host-timeout 201 --max-retries 0 -p 3333 $HOST
```

There should be no difference, am I wrong?

**Additional information**

- Sometimes it works because it happens that the random sequence matches my initial sequence.
- nmap just built from this repository
```
$ nmap --version
Nmap version 7.80SVN ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.5 libz-1.2.8 libpcre-8.38 nmap-libpcap-1.9.0 nmap-libdnet-1.12 ipv6
Compiled without: openssl libssh2
Available nsock engines: epoll poll select
```

**Comment by dmiller-nmap** [comment]
The `-r` option is [described in the man page](https://nmap.org/book/man-port-specification.html) (emphasis mine):

>By default, Nmap randomizes the scanned port order (except that certain commonly accessible ports are moved near the beginning for efficiency reasons). This randomization is normally desirable, but you can specify -r for **sequential (sorted from lowest to highest)** port scanning instead. 

Nmap does not have a way to specify a non-random, non-sequential scan order, and will often retry probes that do not get a response. You would be better off scripting with Nping or a similar packet-crafting tool to do port knocking. Alternatively, you could write a NSE script that does this. If it runs in the pre-scan phase (using the `prerule` form), it could do the port knocking so that the main Nmap port scan can detect the newly-opened port.
