### ISSUE TITLE
nmap 7.80 rates TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA as "A"

### ISSUE THREAD

**Issue by huornlmj** [nmap/nmap#1824]
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA is classed as a weak cipher yet nmap is giving it an "A"

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion. What reference are you using for classifying it as a "weak cipher"?

Nmap's `ssl-enum-ciphers` script uses a scoring algorithm based on Qualys's SSL Labs scoring guidance that takes into account the server's certificate length, EC curve choice, DH parameters, etc. in addition to the actual ciphersuite chosen. At a first glance, I would say there is no problem with this particular cipher suite in terms of handshake secrecy (ECDHE provides perfect forward secrecy), or encryption key size (256-bit AES). The only criticism I can find is in using a CBC cipher mode, which is associated with padding oracle attacks on particular server software, and using SHA-1 for message integrity, though it has not been broken for that purpose (we do warn about SHA-1 certificates, which is a different thing).

**Comment by huornlmj** [comment]
I've taken reference from [https://ciphersuite.info/](https://ciphersuite.info/).

There, [TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA is reported as 'weak'](https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/), due to the use of SHA-1.

**Comment by dmiller-nmap** [comment]
I see. That site is naively penalizing the use of SHA-1 for message authentication (MAC algorithm) due to it being broken for file integrity. However, those uses are subject to different attack types, and a cryptographic digest algorithm may be weak against one type of attack but robust against another. SHA-1 is broken with regard to collision avoidance, of which the SHAttered attack they link to is an example. But breaking a message authentication algorithm requires mounting a chosen-plaintext attack, and SHA-1 has not been demonstrated to be weak in this regard. Furthermore, since each message is acknowledged immediately and the key rotated regularly, the timeframe for completing such an attack is much too small to allow even the best known chosen-prefix attack (itself not a complete attack on message authentication) to complete the required 2^68 SHA-1 evaluations.
