### ISSUE TITLE
LGTM.com issues reported against Nmap

### ISSUE THREAD

**Issue by guyharris** [nmap/nmap#1834]
Originally mentioned in passing in #1827, LGTM.com has scanned Nmap and [found some issues](https://lgtm.com/projects/g/nmap/nmap/?mode=list).

(Posted to, among other things, note that LGTM.com exists and is scanning at least some code in Nmap.)

**Comment by cldrn** [comment]
Thanks for the report. I am aware of this and we are working on some patches. We have confirmed the integer overflow in Nping and we will commit a patch soon.

**Comment by dmiller-nmap** [comment]
Related commits:

* f6ab7a8
* 72fba4b

**Comment by dmiller-nmap** [comment]
Since this issue was filed:

* All "Security"-filter issues have been addressed apart from 3 multiplication overflows in Nping. Two of those we believe to be a single false positive, which we have reported as Semmle/ql#2561.
* 31 alerts have been removed, including all "Error"-level alerts.
* Our code quality score has increased from "C" (Python: B, C/C++: C) to "B" (Python: A, C/C++: B)

**Comment by dmiller-nmap** [comment]
Nmap is now at "A+" rating for C/C++ and Python, with only 25 open issues. I have added badges to the README.md that will hopefully serve as a reminder to use LGTM.com to find issues in the future, and I may decide to turn on continuous integration for pull requests, too. For now, I consider this issue resolved.
