### ISSUE TITLE
Nping how to display the domain name

### ISSUE THREAD

**Issue by qiuzi** [nmap/nmap#1836]
nping  --tcp -p 443 github.com
`Starting Nping 0.7.70 ( https://nmap.org/nping )
SENT (0.1539s) TCP 192.168.4.207:46205 > 52.74.223.119:443 S ttl=64 id=3268 iplen=40  seq=2149672591 win=1480
RCVD (0.3581s) TCP 52.74.223.119:443 > 192.168.4.207:46205 SA ttl=64 id=0 iplen=44  seq=2738751373 win=29200 <mss 1460>
SENT (1.1563s) TCP 192.168.4.207:46205 > 52.74.223.119:443 S ttl=64 id=3268 iplen=40  seq=2149672591 win=1480
RCVD (1.1980s) TCP 52.74.223.119:443 > 192.168.4.207:46205 SA ttl=64 id=0 iplen=44  seq=2754412788 win=29200 <mss 1460>
SENT (2.1573s) TCP 192.168.4.207:46205 > 52.74.223.119:443 S ttl=64 id=3268 iplen=40  seq=2149672591 win=1480
RCVD (2.2480s) TCP 52.74.223.119:443 > 192.168.4.207:46205 SA ttl=64 id=0 iplen=44  seq=2770059934 win=29200 <mss 1460>
SENT (3.1612s) TCP 192.168.4.207:46205 > 52.74.223.119:443 S ttl=64 id=3268 iplen=40  seq=2149672591 win=1480
RCVD (3.2980s) TCP 52.74.223.119:443 > 192.168.4.207:46205 SA ttl=64 id=0 iplen=44  seq=2785745309 win=29200 <mss 1460>
SENT (4.1646s) TCP 192.168.4.207:46205 > 52.74.223.119:443 S ttl=64 id=3268 iplen=40  seq=2149672591 win=1480
RCVD (4.3480s) TCP 52.74.223.119:443 > 192.168.4.207:46205 SA ttl=64 id=0 iplen=44  seq=2801424088 win=29200 <mss 1460>

Max rtt: 204.001ms | Min rtt: 41.560ms | Avg rtt: 130.956ms
Raw packets sent: 5 (200B) | Rcvd: 5 (230B) | Lost: 0 (0.00%)
Nping done: 1 IP address pinged in 4.35 seconds
`
I hope to display the domain name instead of the ip address in the output.
thank you all

**Comment by nnposter** [comment]
I would posit that displaying the DNS name, *instead of the IP address*, is counter-productive.

What specifically would such results indicate in your example? That some *unknown and undisclosed* IP address (that happens to be one of GitHub public interfaces) exhibits some particular performance? What conclusions would you draw if you ran the Nping test twice and got different results? That you probably pinged two different IP addresses? Or that the same IP address is suddenly performing differently? You would not know...

In summary, you normally use Nping to measure performance of a particular IP address (or even a specific port on that IP address). If you want to know how a particular DNS name generally performs (from your location) then you would be better off to resolve the DNS name to all the different IP addresses and then ping all of those. (Nping does not have the equivalent to Nmap option `--resolve-all`.)

If for whatever reason you need the DNS name to show up at least once somewhere in the Nping output then you can use option `-d3`, which gets you the following details before commencing the ping:
```
$ nping --tcp -p 443 -d3 github.com
Nping will send packets at raw IP level

Starting Nping 0.7.70SVN ( https://nmap.org/nping ) at 2019-11-21 19:42 MST
Resolving specified targets...
+-----------------TARGET-----------------+
Device Name:            ens33
Device FullName:        ens33
Device Type:            Ethernet
Directly connected?:    no
Address family:         AF_INET
Resolved Hostname:      
Supplied Hostname:      github.com
Target Address:         192.30.253.112
Source Address:         192.168.73.141
Next Hop Address:       192.168.73.2
Target MAC Address:     00:00:00:00:00:00
Source MAC Address:     00:0c:29:7e:7e:4d
Next Hop MAC Address:   00:00:00:00:00:00
1 target IP address determined.
...
```

**Comment by qiuzi** [comment]
@nnposter
 ` nping --tcp -q1 -p443 github.com www.flickr.com up.flickr.com api.flickr.com

Starting Nping 0.7.70 ( https://nmap.org/nping )
Max rtt: 3427.114ms | Min rtt: 458.101ms | Avg rtt: 1942.607ms
Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
Max rtt: N/A | Min rtt: N/A | Avg rtt: N/A
Max rtt: 1001.753ms | Min rtt: 134.369ms | Avg rtt: 424.067ms
Raw packets sent: 20 (800B) | Rcvd: 6 (264B) | Lost: 14 (70.00%)
Nping done: 4 IP addresses pinged in 19.68 seconds
`
Ideally, the domain name should correspond to before or above the "Max rtt"
I just want to easily identify the batch test to get the information.

**Comment by nnposter** [comment]
I agree that with `-q` (decreased verbosity) the output is lacking sufficient context. Do you absolutely have to use this option?

If you drop `-q` and instead pipe the output to something like `sed` then you get only the summary, including the DNS name and the resolved IP address:
```
$ nping --tcp -p443 github.com www.flickr.com up.flickr.com api.flickr.com | sed -nre '/^Statistics/,$p'
Statistics for host github.com (140.82.114.3):
 |  Probes Sent: 5 | Rcvd: 5 | Lost: 0  (0.00%)
 |_ Max rtt: 331.926ms | Min rtt: 172.015ms | Avg rtt: 229.565ms
Statistics for host www.flickr.com (99.84.253.144):
 |  Probes Sent: 5 | Rcvd: 5 | Lost: 0  (0.00%)
 |_ Max rtt: 310.221ms | Min rtt: 107.399ms | Avg rtt: 187.727ms
Statistics for host up.flickr.com (143.204.159.143):
 |  Probes Sent: 5 | Rcvd: 5 | Lost: 0  (0.00%)
 |_ Max rtt: 329.882ms | Min rtt: 154.088ms | Avg rtt: 215.130ms
Statistics for host api.flickr.com (13.249.74.237):
 |  Probes Sent: 5 | Rcvd: 5 | Lost: 0  (0.00%)
 |_ Max rtt: 367.685ms | Min rtt: 118.558ms | Avg rtt: 238.444ms
Raw packets sent: 20 (800B) | Rcvd: 20 (920B) | Lost: 0 (0.00%)
Nping done: 4 IP addresses pinged in 19.78 seconds
```
