### ISSUE TITLE
Question about NSE Timing

### ISSUE THREAD

**Issue by dataarchivist** [nmap/nmap#1852]
It hangs for over 90 mins at the same point, 99,87%. Is this normal?
Tested under Ubuntu 18.04 with latest updates.
Used: nmap --script=default,vuln --stats-every 15 -o nmap-tld.txt xxxxxx.tld

Stats: 1:29:00 elapsed; 0 hosts completed (1 up), 1 undergoing Script Scan
NSE Timing: About 99.87% done; ETC: 12:57 (0:00:07 remaining)

Thanks for helping!

**Comment by dmiller-nmap** [comment]
Thanks for asking. Sometimes a script misbehaves, entering an infinite loop. Other times the loop may have an end condition that is not well defined, depending on a network connection that is no longer available (because the target has gone down or firewalled the scanner). You can use the `--script-timeout` option to prevent any one script from running too long; in Nmap 7.70 and later, the `-T5` option adds a 10-minute timeout, for instance.

To determine what script is running, you can press <kbd>d</kbd> twice to increase debugging to level 2, then press any key to get a traceback of all running script threads. This can be overwhelming output in an ordinary scan, but with a single misbehaving script against a single target, it ought to show which script is causing issues and exactly where it is stuck.

Please note that Ubuntu 18.04 is using Nmap 7.60, which was released over 2 years ago, and we have made 2 new releases since then that may have already addressed the issue you're seeing. If you update to Nmap 7.80 and still experience problems, you may re-open this issue or open a new one with debugging output as described above so we can better diagnose the problem. Thanks!
