### ISSUE TITLE
Installer of npcap 0.9985 always show WinPcapCompatible as enabled

### ISSUE THREAD

**Issue by yyjdelete** [nmap/nmap#1863]
1. install npcap 0.9985 with WinPcapCompatible=off first;(not sure, but maybe need upgrade from 0.9984 or older version with WinPcapCompatible=on)
2. Then install npcap 0.9985/0.9984 again, and see WinPcapCompatible is on by default.

I can found 
`WinPcapCompatible`=0 in
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Npcap` and
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npcap\Parameters`
but `WinPcapCompatible`=1 in
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npf\Parameters`
(It's strange `npcap_wifi`(there is just an `Start=4` in it), `npf` and `npf_wifi` was not removed from `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services`, but I didn't know it was created by which version of npcap)

Updated:
when I reinstall 0.9984 with both `802.11` and `WinPcapCompatible` on, and do an clean uninstall and reinstall, I didn't see `npf` and `npf_wifi` in 0.9985 now(don't know why it used to happen), but `WinPcapCompatible` is still always enabled.

**Comment by dmiller-nmap** [comment]
This is intentional behavior. Npcap 0.9985 introduced a change (#1812) that allows a single driver (npcap.sys) to service requests from the native Npcap DLLs as well as the ones with WinPcap API compatibility shims. The only thing that WinPcap API-compatible mode now does is installs `wpcap.dll` and `Packet.dll` into `%WINDIR%\System32\`. If you need to change the default selections in the installer, you can use [the command-line interface](https://nmap.org/npcap/guide/npcap-users-guide.html#npcap-installation-options) to set or enforce default options.
