### ISSUE TITLE
Npcap Loopback Adapter missing

### ISSUE THREAD

**Issue by fred-cardoso** [nmap/nmap#1886]
I did a fresh install of npcap using Windows latest .exe release and I don't see the Npcap Loopback Adapter on Control Panel's network interfaces.

I am not sure what I can provide to try to debug this situation.

Thanks!

**Comment by djcater** [comment]
I believe that is intentional. Npcap was changed such that it can capture packets on localhost on Windows without needing the separate adapter. The latest stable release of Nmap (7.80) still requires it though.

See the second bulletpoint for Npcap release 0.9983: https://github.com/nmap/npcap/releases/tag/v0.9983

**Comment by dmiller-nmap** [comment]
@djcater is correct. Npcap no longer needs the Npcap Loopback Adapter to do loopback traffic capture. If you really need it, it can be enabled with the "Legacy loopback support" option.

**Comment by fred-cardoso** [comment]
Thanks!
