### ISSUE TITLE
VMware Workstations中的虚拟机使用桥接网络时，本地物理机调用npcap组件抓包有问题

### ISSUE THREAD

**Issue by l1TTss** [nmap/nmap#1923]
我的Windows 10 1909系统安装了VMware Workstations，虚拟机使用桥接网络时，本地物理机网络流量处理分析发送的相关软件调用npcap组件有问题，相关软件无法识别正确的本地网络网卡实现发包探测之类的操作，并产生了无法识别本机网络网卡的提示报错。还请开发人员仔细研究分析更新优化解决这个问题，谢谢。（本人仔细测试了，应该几乎包括所有的npcap的版本，同时，现最新版本的npcap version 0.9987也有这个问题的。）

**Comment by fyodor** [comment]
I'm closing this because it isn't in English and it's now a fairly old version of Npcap (version 0.9991 might have this resolved) and nobody has commented in the months since this was filed so it isn't getting attention anyway.  If you still encounter the problem with Npcap version 0.9991, please refile in English if possible.
