### ISSUE TITLE
Service detection nsock_read() timeout value unnecessarily large for local targets

### ISSUE THREAD

**Issue by davidreis97** [nmap/nmap#1957]
I'm using nmap's service detection to discover which services are running on a Docker container running in my local machine. Due to the nature of the application I'm developing (a [live programming environment for Dockerfiles](https://github.com/davidreis97/Dockerlive)) I need the scan to be as fast as possible (less than 3 seconds ideally). 

However, in the current version of nmap, scanning on a single port (e.g. `nmap localhost -p 32771 -sV --version-intensity 1`) results in an execution time of around 11 seconds. After using the `--version-trace` option I noticed that this was due to two `nsock_read()` calls taking more than 5 seconds each to timeout. Since I'm running the test on a local port and I need the scan to take no more than 3 seconds, I would like to be able to reduce this timeout value. 

After reading through your documentation and searching through the codebase, I realized that this value is not changeable through any command-line option, and is defined through a hardcoded value in the constructor of the ServiceProbe class, as seen below.

https://github.com/nmap/nmap/blob/4097f390900567e978b3b8aa233764d4e8572d1c/service_scan.cc#L1138-L1139

After changing this value on the source code from the default 6000ms to just 300ms and compiling nmap, the same nmap scan mentioned above now returns in around 1.5s instead of 11s, outputting the same results. For now, in my project, I plan to use my modified version of nmap, but I think that allowing nmap users to customize this value through a command-line argument would be a valuable addition to nmap.

**Operating System**: Only tested on mac but expect other platforms to also behave as described.

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion! This timeout has nothing to do with the latency of the connection, but is based on empirical evidence that many services wait for a predetermined period after accepting a connection before returning a banner. This is frequently the case with SMTP mailservers trying to slow down spam attempts as well as the curious case of `sshttp`, which will respond with an HTTP response if a GET request is presented, but after a short timeout will return a SSH banner. If the service produces a banner without a delay, then this timeout has no slowing effect. Nmap parallelizes scan probes, so the cost is borne only at the beginning of the scan phase, since other probes can be launched while the first ones are waiting for a banner.

There is a way to control this timeout without recompiling: the [`totalwaitms` directive](https://nmap.org/book/vscan-fileformat.html#vscan-db-totalwaitms) in the `nmap-service-probes` file. We do not feel this warrants a command-line option.
