### ISSUE TITLE
Can't verify publisher for Npcap 0.9990 on Windows 7

### ISSUE THREAD

**Issue by paolodm** [nmap/nmap#1991]
Getting this error message when I try to install Npcap 0.9990 onto a Windows 7 box:

![image](https://user-images.githubusercontent.com/247525/78723436-68e13180-78f9-11ea-8e6c-675ecd91e376.png)

The release notes for Npcap 0.9988 stated that deprecating the old SHA-128 drivers would only affect Windows Server 2008 and Vista and not Windows 7/2008 R2. However, this seems to not be the case. 

From https://github.com/nmap/npcap/releases/tag/v0.9988:

Formally removed support for Windows Vista and Server 2008 r1, which are no longer supported by Microsoft either. This allows us to support newer Windows WFP and NDIS features for better performance and compatibility. Folks who must still run these ancient Windows releases should use Npcap version 0.9984 from https://nmap.org/npcap/dist/?C=M;O=D. That was the last Npcap release to support the old (and less secure) SHA-128 driver signatures required by these Windows Vista/2008. **Please note that Windows Server 2008 r2 and Windows 7 are still supported in this release even though they have also passed their Microsoft end-of-life dates.**

So either the release notes for Npcap 0.9988 are inaccurate or there is a bug that is manifesting when installing on Win7.

**Comment by nnposter** [comment]
FWIW, I have run the 0.9990 installer with all defaults on fully patched but otherwise reasonably pristine Windows 7 Enterprise, both x86 and x64, without seeing this error.

The only prompt I got was the following:

![Npcap-0 9990](https://user-images.githubusercontent.com/10360850/78731594-641e7c80-78fd-11ea-977c-8b5e3360eb92.png)

The release note comment about Vista and Win7 is is likely meant to convey that Vista cannot support SHA-2 signatures but Win7 can. Note that the support for SHA-2 is not there out of the box. It requires an update. See https://support.microsoft.com/en-us/help/4472027/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus for details.

**Comment by paolodm** [comment]
Hey @nnposter, thanks for the update. I verified that the update fixed the issue on my box. Thanks!
