### ISSUE TITLE
Npcap 0.9990: npf.sys missing

### ISSUE THREAD

**Issue by MatLcq** [nmap/nmap#1993]
Hello, 

I need npf.sys driver for a piece of software that needs it. After installing Npcap 0.9990 in WinPcap compatibility-mode, the npf.sys still doesn't exists in the C:\Windows\System32\driver folder (altough npcap.sys exists and runs well).

My version of windows is Windows 10 Entreprise LTSC (10.0.17763.1131) and it runs on VMware Workstation Player 15 (15.5.2 build-15785246). It is a fresh install (no AV, just Defender, no group policies configured)

Is there something I'm missing?
Thank you for your help.

EDIT: I've tried uninstalling-installing it multiple times, with/without Defender running.

[install.log](https://github.com/nmap/nmap/files/4449355/install.log)
[NPFInstall.log](https://github.com/nmap/nmap/files/4449356/NPFInstall.log)
[DiagReport-20200408-105222.txt](https://github.com/nmap/nmap/files/4449357/DiagReport-20200408-105222.txt)

**Comment by mmueller-projektantrieb** [comment]
We are having the same problem with the missing npf service in compatibility mode.
We are detecting whether the service npf is running for backward compatibility in a software.
Uninstall showed, that it deletes npf.sys even though it doesn't exist in the driver directory.

Tested systems:
Win 10 Enterprise 10.0.17134.1098
Win 10 Business 10.0.18362.628
In VirtualBox: Win 8.1 Pro 6.3.9600.18969

**Comment by dmiller-nmap** [comment]
This is not a bug: Npcap 0.9985 and later provides WinPcap-compatible API without the need for an additional filter driver. This makes Npcap more efficient and avoids problems with earlier Windows versions that set a hard limit on the number of NDIS filter drivers that could be installed.

Software that needs to test for the `npf` service when running under WinPcap can determine first if it is using Npcap by calling `pcap_lib_version()` and checking that the string begins with "Npcap". If it is Npcap, no further checks are needed for the following reasons:

1. Npcap is intended to start at boot time. The installer does not offer any other option. As a LWF driver, Npcap must be present when the network stack starts, or Windows may delay startup for up to 90 seconds.
2. If the driver services is not started, any of the Packet.dll functions that wpcap.dll calls internally will attempt to start it anyway. If it is unable to do so, no adapters will be returned by `pcap_findalldevs()` or `PacketGetAdapterNames()`. Note that there is no UAC prompt, so most processes do not have sufficient privilege to start the service.

A suitable replacement for code that elevates via UAC and attempts to start the service would be to elevate in the same way and attempt to list adapters via `pcap_findalldevs()`, which would in turn attempt to start the driver service via Packet.dll. This should also work with WinPcap, since the code to start the driver service is a remnant of the original WinPcap code.

**Comment by mmueller-projektantrieb** [comment]
Might be a good idea to mention it here that npf is not available anymore or remove the mention of possible start of npf in compatible mode.
https://nmap.org/npcap/guide/npcap-devguide.html#npcap-detect-run-time

**Comment by MatLcq** [comment]
Ok, thanks.
Since DiagReport still shows that the NPF service is missing I was under the impression that it was still needed.
For further reference, below the change log of 0.9985 mentioning the removal of the NPF service and the link to the repository where 0.9984 can still be use:
https://github.com/nmap/npcap/blob/master/CHANGELOG.md#npcap-09985-2019-12-13
https://nmap.org/npcap/dist/?C=M;O=D

Thank you for the reply.
