### ISSUE TITLE
Npcap should maybe uses NULL/Loopback encapsulation rather than fake ethernet headers for received packets

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#200]
Our latest Npcap can now capture from localhost (unlike WinPcap), but captured packets are given a fake ethernet header with the MAC addresses all zeros.  It might be better to use the NULL/Loopback encapsulation type.  The downside is that Nmap and other tools might not be able to recognize this without new code.  Anyway, a relevant mail from Jim Young is at: https://www.wireshark.org/lists/wireshark-dev/201508/msg00097.html

**Comment by hsluoyz** [comment]
Added DLT_NULL option in Npcap installer, when Npcap is installed with DLT_NULL option checked, the driver will capture and send loopback packets using DLT_NULL protocol instead of Ethernet II, by default this option is not checked.
https://github.com/nmap/npcap/commit/7519b4d9ddfe74a0b3e3bb15d19483e1cfa45a47
