### ISSUE TITLE
An error in PostgreSQL password brute forcing

### ISSUE THREAD

**Issue by kemanik** [nmap/nmap#2009]
Correct logins and passwords are in files and result should be successful.
nmap -sT -p 5432 -d -Pn --script pgsql-brute --script-args "unpwdb.timelimit=3h,userdb=C:\\logins2.txt,passdb=C:\\passwords2.txt" 192.168.1.133

NSE: pgsql-brute against 192.168.1.133:5432 threw an error!
С:\Program Files (x86)\Nmap/nselib/pgsql.lua:432: bad argument #2 to 'unpack' (string expected, got nil)
stack traceback:
	[C]: in function 'unpack'
	C:\Program Files (x86)\Nmap/nselib/pgsql.lua:432: in function 'decodeHeader'
	C:\Program Files (x86)\Nmap/nselib/pgsql.lua:448: in function 'processResponse'
	C:\Program Files (x86)\Nmap/nselib/pgsql.lua:498: in function 'loginRequest'
	C:\Program Files (x86)\Nmap/scripts\pgsql-brute.nse:140: in function <C:\Program Files (x86)\Nmap/scripts\pgsql-brute.nse:72>
	(...tail calls...)
[nmap_output.txt](https://github.com/nmap/nmap/files/4492653/nmap_output.txt)

**Comment by nnposter** [comment]
This could be just a communication breakdown. Is the script failing consistently with the same stack trace and for the same credential combo?

If yes, there appear to be a few code issues in the vicinity of the reported stack trace.  Please apply the following patch and try to recreate the issue:
https://gist.github.com/nnposter/808a2a3f3e3158a32e21f3f4fb2b92ad

**Comment by kemanik** [comment]
It doesn't help, the error is still at place.

**Comment by nnposter** [comment]
Are you sure that it is the same combo? From your first report:
```
NSE: [pgsql-brute 192.168.1.133:5432] Trying test/p@ssword123456 ...
NSE: [pgsql-brute 192.168.1.133:5432] Trying test/test$pWd1 ...
NSE: pgsql-brute against 192.168.1.133:5432 threw an error!
```
So `test/test$pWd1` appears where the error was encountered.

And from the current one:
```
NSE: [pgsql-brute 192.168.100.133:5432] Trying sys/p@ssword123456 ...
NSE: [pgsql-brute 192.168.100.133:5432] Not enough data to cover PGSQL message header
NSE: pgsql-brute against 192.168.100.133:5432 threw an error!
```
This time the failing combo appears to be `sys/p@ssword123456`. Note that it is also present in your first report, where it did not cause an error.

To minimize any possible variability and overlapping network traffic in the execution, please make sure that you are running the attack single-threaded. Use `-ddd` so nmap dumps the traffic, and also run a simultaneous packet capture. Hopefully we will be able to determine if the server stops responding or if the protocol parser gets somehow out of sync.

**Comment by kemanik** [comment]
Here is results with -ddd settings
[nmap_res2.txt](https://github.com/nmap/nmap/files/4758070/nmap_res2.txt)

**Comment by nnposter** [comment]
As far as I can tell, the server has killed the connection.

For the sake of it I have tested the script against v3 of the database protocol (same as yours) and it worked as expected.

**Comment by rag-altx** [comment]
Hi @nnposter! I added this code to pgsql.lua, 443 (_processResponse_ function) this solve the problem, what do you think? [pgsql.zip](https://github.com/nmap/nmap/files/4785260/pgsql.zip)
`    
if(data == nil) then
      return -1, "Header data is nil"
    end
`

**Comment by nnposter** [comment]
IMHO `v3.readPacket()` should be strengthened to guarantee that the returned data covers the entire message. `v3.processResponse()` could then implement your early bailout `if not data then...` but change the error string to "*Not enough response data*" (because it is not just about the 5-byte header).

I have tried to clean up the error handling in this section of the library. It is not likely going to help with the original error itself but the code should be failing more gracefully.

https://gist.github.com/nnposter/5df4352afd9f54c76d32e0123915a137

**Comment by rag-altx** [comment]
Hi @nnposter! Your last changes helped. Instead error now this message repated: "Not enough data for PGSQL message header" see [Nmaplog.txt](https://github.com/nmap/nmap/files/4813101/Nmaplog.txt) and bruteforce continue.

**Comment by nnposter** [comment]
I am not sure that it really helped. Based on the output you have shared, I do see that it found one set of valid credentials but most of the passwords for `sys` did not get tested because of this issue.

It would be nice to know the root cause of this. Namely, does the error in event ID 82 of `nmap_res2.txt` represent expected behavior by the target PostgreSQL server (perhaps under some specific circumstances) or is this just a result of a poor connection? If it is the former then the NSE script could be perhaps updated to make it more reliable.

**Comment by rag-altx** [comment]
Sorry for misleading i reduced file with interactive output this is full version
[results-brute_2020_06_22_03_10_05.txt](https://github.com/nmap/nmap/files/4817671/results-brute_2020_06_22_03_10_05.txt)

**Comment by nnposter** [comment]
OK, understood. Are you both (@rag-altx, @kemanik) then fine with the code I have shared or do you see some new misbehavior introduced by this patch?
