### ISSUE TITLE
Cannot Uninstall Software - Bluescreen of Death - DRIVER_POWER_STATE_FAILURE

### ISSUE THREAD

**Issue by bretie** [nmap/nmap#2025]
Solved?

**Comment by dmiller-nmap** [comment]
Thanks for this bug report. To debug the BSOD crash, please look for a kernel minidump file in `C:\Windows\Minidump\` and send it to us at dmiller@nmap.com.

The uninstallation was aborted because a process was using `wpcap.dll` at the time of uninstall and could not be stopped successfully. We have made significant improvements to the uninstaller to address issues like these (#2015) which will be available in future releases. In the meantime, stop all processes which may be using Npcap/WinPcap and reattempt the uninstallation. If the system was left in a partially-installed state without an uninstaller present, you may need to reinstall Npcap and then uninstall it immediately.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
