### ISSUE TITLE
Npcap 0.9990 not working anymore with XLink Kai

### ISSUE THREAD

**Issue by Jacksoft** [nmap/nmap#2031]
After upgrading to v0.9990 XLink Kai does not recognize "WinPCap" anymore, also if the check about compatibility is active.
The very fun thing, after uninstalling NPcap, is that now WinPCap 4.1.3 works with XLink Kai and on Windows 10!

**Comment by dmiller-nmap** [comment]
This is likely due to XLink Kai being written for WinPcap. We recently made a change that broke some WinPcap-only software that expects to find a driver service called `npf`. This is not part of the official WinPcap API, but only a workaround for the case where the driver service was not started at boot time. Npcap always starts at boot time, so the workaround is not needed. Updating to support Npcap is fairly simple. You can file a request with the developers of XLink Kai to support Npcap in native mode or remove the check for the `npf` driver service.

**Comment by CrunchBite** [comment]
As of release 7.4.38 XLink Kai now has native support for both NPcap and WinPcap. Please reach out if you have any issues.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
