### ISSUE TITLE
Appimage and flatpak packages

### ISSUE THREAD

**Issue by sallywoog** [nmap/nmap#2076]
Appimage and flatpak packages requested since it is now dropped from distro repos

or host your own upstream to distribute it we can use as an alternative source

**Comment by fyodor** [comment]
Thanks for your suggestion. This is not a bad idea, but our higher priority is the Python3 Zenmap port (issue #1176 ), which will allow the distros that dropped Python2 to ship Zenmap again.  In the meantime, you can usually just run a couple commands on these distros to install Python2 and Zenmap.  We should better document those commands but, for now, several are listed in issue #1176 .  I'm closing this issue since we already are working to address this in a different way.  But we can re-open if we reconsider using these package formats instead.

**Comment by sallywoog** [comment]
Python 2 is dead, it won't be on my machines again

**Comment by fyodor** [comment]
Thanks for your suggestion.  I've consolidated several similar issues into a new #2275 for discussing the benefits of supplying Nmap as an AppImage, Snap, or Flatpak.  These might have benefits beyond just the Python2 issue.
