### ISSUE TITLE
Can Ncat connect to a server that uses a self-signed certificate?

### ISSUE THREAD

**Issue by mb720** [nmap/nmap#2101]
Hi and thanks a lot for Ncat!

I have a custom server running locally. The server uses a self-signed certificate for TLS.

I tried requesting a file from the local server with:

    printf "GET / HTTP/1.1\r\nHost:localhost\r\n" | ncat --ssl -v localhost 8443

but I can see from Ncat's output that it rejected the connection:

>Ncat: Certificate verification failed (self signed certificate).

Is there a way to make Ncat accept that certificate?

I'm looking for something like curl's `--insecure` option.

---

Ncat: Version 7.80
Arch Linux 5.7.7

**Comment by nnposter** [comment]
There is no need for anything like `--insecure` because certificate validation is off by default. You need to use `--ssl-verify` if you do want to validate the certificate. The error message will get generated either way but it is not a fatal error in the first case.

Here is an example with a self-signed certificate:
```
pavel@armchair:~$ printf "GET / HTTP/1.1\r\nHost:localhost\r\n" | ncat --ssl -v 192.168.1.100 443
Ncat: Version 7.80SVN ( https://nmap.org/ncat )
Ncat: Subject: C=US, ST=Maine, L=Portsmouth, O=Nmap Lab, OU=Test1, CN=whatever.org98346923.net
Ncat: Issuer: C=US, ST=Maine, L=Portsmouth, O=Nmap Lab, OU=Test1, CN=whatever.org98346923.net
Ncat: SHA-1 fingerprint: D6D7 CE2A C65B 93D2 5D2B C577 F6B1 26D9 426A 9B35
Ncat: Certificate verification failed (self signed certificate).
Ncat: SSL connection to 192.168.1.100:443. Nmap Lab
Ncat: SHA-1 fingerprint: D6D7 CE2A C65B 93D2 5D2B C577 F6B1 26D9 426A 9B35
HTTP/1.0 200 ok
Content-type: text/html

<HTML><BODY BGCOLOR="#ffffff">
<pre>
... 
```
You should look for other explanations if the command does not work as expected.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
