### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by Janvvier9999** [nmap/nmap#2121]
Scanning the Windows executable of nmap 7.80 on Virustotal says it has a Trojan?
https://nmap.org/dist/nmap-7.80-setup.exe
https://www.virustotal.com/gui/file/b4c380b046c8a4ebffb2f827afae338e1fbeb052064cea4ac6a9c34d35750145/detection

**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including command-line options.

**Expected behavior**

**Version info (please complete the following information):**
 - OS: [e.g. Linux 4.15, Windows 10 1909]
 - Output of `nmap --version`:
 - Output of `nmap --iflist`

**Additional context**
Add any other context about the problem here, such as special network type.

**Comment by dmiller-nmap** [comment]
Nmap includes Ncat, which is a re-implementation of the basic networking utility Netcat. Antivirus companies often detect this utility as a "trojan" because it can be used to create a TCP channel to a shell. There is nothing we can do to prevent this besides suggesting that you view it as a false positive. I have commented on the virustotal page you linked.
