### ISSUE TITLE
EXCLUDE SOME NOTIFICATIONS

### ISSUE THREAD

**Issue by francoataffarel** [nmap/nmap#2166]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

**Expected behavior**
Describe what you would like to happen instead.

HOW CAN I EXCLUDE THIS MESSAGE? 

Host discovery disabled (-Pn). All addresses will be marked 'up' and scan times will be slower.

**Comment by dmiller-nmap** [comment]
Thanks for this report. The best way to avoid this warning is to avoid using the `-Pn` option. If you are sure that you need to skip host discovery and are OK with longer scan times, the warning can be safely ignored.

This warning message was added because we see a large number of instructional material and advice from users to use `-Pn` all the time, but Nmap relies greatly on the timing information it gathers during the host discovery phase. There is also a pervasive misunderstanding that `-Pn` only affects ICMP Echo Request or that Nmap should somehow know if a target is up even when it has been explicitly told via `-Pn` to treat every target as up. This warning was added in a commit that also improved our documentation surrounding host discovery in general.

I have added a check for `-v` before showing this warning, so it will be hidden in the default scan.
