### ISSUE TITLE
pjl script status command missing \r

### ISSUE THREAD

**Issue by mojtaba-akbari** [nmap/nmap#2182]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the bug**
using script pjl-ready-message for port 9100/jetdirect, should cause [timeout] and script closed by nmap without any effect in scanning.

**To Reproduce**

nmap --script "pjl*" --script-trace -p 9100 10.10.10.201

**Expected behavior**

PORT     STATE SERVICE
9100/tcp open  jetdirect
|_pjl-ready-message: "LaserCorp supply in use"

**Version info (please complete the following information):**

Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.3 openssl-1.1.1g libssh2-1.8.0 libz-1.2.11 libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

**Additional context**

problem can solve with adding one \r at script line:
statusmsg="@PJL INFO STATUS\n" -------> statusmsg="@PJL INFO STATUS\r\n"

**Comment by nnposter** [comment]
Thank you for reporting the issue. The PJL specification, [HP publication 5021-0380](https://developers.hp.com/system/files/PJL_Technical_Reference_Manual.pdf), allows command termination with either `LF` or `CR`/`LF`, hence your target appears to be non-compliant.

In commit 38141 I did add `CR` to the command as you have suggested but if it turns out there are more implementations that only allow `LF` then we might have to take it out again.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
