### ISSUE TITLE
netcat : add a zero-byte option

### ISSUE THREAD

**Issue by NoSuchCommand** [nmap/nmap#22]
In my personal usage, a very useful option of the traditional netcat is the zero-byte connection (-z) : this is intended to just test the connectivity to a remote port, not sending any data. Unfortunately, this is not yet implemented into your version of netcat which apparently is the only one distributed by some Linux distributions (i.e. RedHat).

Would it be possible to add this option please ?
Thank you

**Comment by bonsaiviking** [comment]
For the reasons described above, this enhancement is a wont-fix. However, if folks have a good argument for it or really need such a feature for some reason, they're welcome to add comments here or on the mailing list

**Comment by NoSuchCommand** [comment]
I did not know about this workaround with `nmap`. Thank you.

However, the fact is that `nmap` is often forbidden in companies, be it its use or its installation. In addition, some Linux distributions (like RedHat) only ship with your version of `netcat`, not the traditional one. Even if you judge the functionality "weak", it could be useful to many of your users who still use this awful (and interactive) `telnet` command to test access to port because of the lack of this option on their version of `netcat`. Don't you think this might be something to reconsider ?

**Comment by p-l-** [comment]
I might be wrong here, but it seems to me that it is possible to mimic the behavior of `netcat -z [target] [port]` with Nmap's `ncat` by running `ncat [target] [port] < /dev/null`.

**Comment by NoSuchCommand** [comment]
You are perfectly right. What a shame I did not think of this solution ! It is really elegant. Thank you.

**Comment by mickrussom** [comment]
Can someone suggest a way with the new nc without the -z option how to make this work: 

while [ ! -f ~/stopssh ]; do ssh -o TCPKeepAlive=yes -o ExitOnForwardFailure=yes -p 22 22222:localhost:22 user@foo.bar.baz.com "while nc -zv localhost 22222 ; do sleep 5 ; done" ; sleep 5 ; done

Whatever needs to change for netcat from nmap for this to work. If you decide to kindly work on feel free to use any binary from the nmap-ncat (6.40 and above) package. 

(Note: please consider implementing "-z"  because it requires that I re-write a lot of scripts that I use please , as an aside - the general philosophy of *nix has always been keep options to prevent issues with old scripts, I currently work around by getting a netcat 1.84 based nc. Thanks for reading this far :)

**Comment by tremblerz** [comment]
I have linked a small proposal for this issue, it would be great to hear from you people. [LINK](https://docs.google.com/document/d/1hGZytzvJ7OdBATXcq0JOo0_q8OKlE-D0Sgb2eok6Jhw/edit?usp=sharing)

cc @bonsaiviking
