### ISSUE TITLE
Virustotal flags nmap-7.91-setup.exe as malware

### ISSUE THREAD

**Issue by ghnm15** [nmap/nmap#2253]
Virustotal flags nmap-7.91-setup.exe as malware:https://www.virustotal.com/gui/file/c4683097a2615252eeddab06c54872efb14c2ee2da8997b1c73844e582081a79/detection
  
Is this to be expected?

JoeSandbox also detects hints to malware:
https://www.joesandbox.com/analysis/334989/0/html 

Some of them are to be expected, but this is maybe not obious
to all users.

How can I be sure to install a benign version of nmap?
(apart from verifying the checksum of course)

Chris

**Comment by DamieFC** [comment]
I think it's just because it's a .exe file, and a lot of malware is in executable files. I am not completely sure though :disappointed:.

**Comment by dmiller-nmap** [comment]
The Relations tab under "Bundled Files" shows that the detections are for ncat.exe. This is typical antivirus behavior; we have to deal constantly with Google de-listing us and antivirus software flagging Ncat because it has the ability to create a reverse shell. Nobody flags bash or Powershell for the same reason, though. I have put in a "safe" vote and commented on both files, but there's not much else we can do.

@ghnm15 to answer your question, you can verify the embedded signature of the files as well as the published GPG signature and file integrity hashes from nmap.org. We sign all our installers and EXEs with our EV codesigning certificate issued by DigiCert, CN=Insecure.Com LLC.

**Comment by fyodor** [comment]
Let's keep this open for now since it's not resolved yet.  Of the 68 AV engines used by VirusTotal, only 2 (ESET-NOD32 from the Slovak Republic and Yandex from Russia) are wrongly flagging Nmap as problematic.  I have some ideas for contacting them to fix this, but what helps the most is if users of these packages report the error directly.  AV companies are more likely to listen to their customers than third party vendors.

**Comment by dmiller-nmap** [comment]
Closing this issue: Nmap 7.92 has superseded 7.91, and the 7.91 installer now has a Trusted Source Project designation from Microsoft on VT, so there are no "red checks" even though the AV vendors are still flagging Ncat.

**Comment by fyodor** [comment]
It's nice to hear about that Trusted Source Project aspect.  Also I'm happy to see that [no vendors currently flag the Nmap 7.92 Windows self-installer as malicious](https://www.virustotal.com/gui/file/b2400db1a4af9607fdd6ee50e0f5926d8b9272f89eec93d4c30b56dc854afb7a/detection)

**Comment by goarblt** [comment]
hello
https://www.evil.com/
