### ISSUE TITLE
SNI (Server Name Indication) support ?

### ISSUE THREAD

**Issue by macruspareto** [nmap/nmap#2290]
I'm trying to scan a list of hostnames with 'http-screenshot.nse' script but Nmap would always resolve it to IP and end up on the default frontpage.

Is there any option to supply the SNI / virtual host name ?

**Comment by nnposter** [comment]
Nmap supports both SNI and HTTP Host header out of the box by just specifying the target with a hostname, instead of its IP address.

Script `http-screenshot.nse` is not part of Nmap. If you are running the version from SpiderLabs then the problem is that the script is using the target IP address, not hostname, when [assembling the URL](https://github.com/SpiderLabs/Nmap-Tools/blob/d6e655a59240d76838928f75ed718775f19548f7/NSE/http-screenshot.nse#L51).

You can try to edit the script, replacing all instances of `host.ip` with expression `(host.targetname or host.ip)`.

**Comment by macruspareto** [comment]
SOLVED!

It worked. Thanks!

**Comment by goarblt** [comment]
hello
https://www.evil.com/
