### ISSUE TITLE
Ncat issues with /dev/stdin in Bash

### ISSUE THREAD

**Issue by hwittenborn** [nmap/nmap#2319]
I'm trying to implement `ncat` into a Bash script for webserver functions, but `/dev/stdin` is behaving oddly.

More specifically, my issue is with the `cat` command. Whenever I attempt to run `cat /dev/stdin` in my script, it hangs indefinitely, as if it's waiting for more input. The [nmap docs](https://nmap.org/ncat/guide/ncat-exec.html) and [an article on secwiki.org](https://secwiki.org/w/Ncat/EOF_behavior) both seem to be pointing to that `ncat` does this as well.

Question is: Is there any reason that it does this? At the very least, is there a way I can end the `cat` stream on the server side?

---
OS: Ubuntu 20.04.2 LTS
Version: Ncat 7.80

**Comment by nnposter** [comment]
If you are trying to use ncat as a simple web application then your problem is that the slurping of stdin will not complete until the cat-like command inside the script sees EOF, which happens when ncat sees EOF on the socket. With a web client, this will not happen because it waits for the HTTP response before closing the connection. Hence you have a deadlock where both ends wait for each other.

> At the very least, is there a way I can end the cat stream on the server side?

What you generally need to do is to read the input one line at a time and quit the loop on your own once you detect logical end of the input, instead of waiting on EOF.

**Comment by hwittenborn** [comment]
Yep - everything I've read seemed to be pointing to that, I just wasn't able to figure out what I should do.

Anyway, for reference, the following solution (which uses a timeout with read), appears to be working for me. I haven't tested it within the actual project, but it's working by itself just fine:

```sh
while read -t 1 i; do
echo "${i}"
done < /dev/stdin
```

**Comment by goarblt** [comment]
hello
https://www.evil.com/
