### ISSUE TITLE
--quiet or --silent option to remove stdout output

### ISSUE THREAD

**Issue by xanview** [nmap/nmap#236]
This is related to this issue: https://github.com/sophsec/ruby-nmap/issues/38

Can a --quiet or --silent option be added to nmap?

When nmap is used to output to XML in a library like ruby-nmap, it also outputs to that application's standard output making it difficult to diagnose and see desired output.

**Comment by dmiller-nmap** [comment]
This shouldn't be tough to implement, but the generally accepted way to do it is to redirect output to /dev/null or similar. That's all that we'd be doing internally, reopening `o.nmap_stdout` to `DEVNULL` like in `log_open` in `output.cc`. Also, we might not be able to use the short option `-q` because that previously was the "quash argv" option.

**Comment by cldrn** [comment]
Perhaps we can use the verbose flag? -v0? Although allowing interactive mode to set verbose to that level may confuse users a bit.
