### ISSUE TITLE
zenmap python issue

### ISSUE THREAD

**Issue by AliyevH** [nmap/nmap#2446]
Hi. I saw some people create issue with python.
As most of distros changed default installed python version to 3
 suggest to migrate to python3 or for now change header of `/usr/bin/zenmap`
`#!/usr/bin/env python` to `#!/usr/bin/env python2`

**Describe the bug**

```File "/usr/bin/zenmap", line 114
    except ImportError, e:
           ^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

**To Reproduce**
After fresh installation of fedora 35. install nmap and run.

 - Output of `nmap --version`: 7.92-1

**Comment by orgcontrib** [comment]
Let's be clear, nmap package alone works fine (as expected).
The problem is with the FlatHub distributed package (official GUI).

################################################################################

[tux@dactuxone ~]$ dnf info nmap
Last metadata expiration check: 0:00:11 ago on Sun 03 Apr 2022 04:02:45 PM CEST.
Installed Packages
Name         : nmap
Epoch        : 3
Version      : 7.92
Release      : 1.fc36
Architecture : x86_64
Size         : 24 M
Source       : nmap-7.92-1.fc36.src.rpm
Repository   : @System
From repo    : updates-testing
Summary      : Network exploration tool and security scanner
URL          : http://nmap.org/
License      : Nmap
Description  : Nmap is a utility for network exploration or security auditing.  It supports
             : ping scanning (determine which hosts are up), many port scanning techniques
             : (determine what services the hosts are offering), and TCP/IP fingerprinting
             : (remote host operating system identification). Nmap also offers flexible target
             : and port specification, decoy scanning, determination of TCP sequence
             : predictability characteristics, reverse-identd scanning, and more. In addition
             : to the classic command-line nmap executable, the Nmap suite includes a flexible
             : data transfer, redirection, and debugging tool (netcat utility ncat), a utility
             : for comparing scan results (ndiff), and a packet generation and response
             : analysis tool (nping).

[tux@dactuxone ~]$ man nmap
[tux@dactuxone ~]$ nmap -A -T4 scanme.nmap.org
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-03 16:03 CEST
Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.17s latency).
Other addresses for scanme.nmap.org (not scanned): 2600:3c01::f03c:91ff:fe18:bb2f
Not shown: 995 closed tcp ports (conn-refused)
PORT      STATE    SERVICE     VERSION
22/tcp    open     ssh         OpenSSH 6.6.1p1 Ubuntu 2ubuntu2.13 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   1024 ac:00:a0:1a:82:ff:cc:55:99:dc:67:2b:34:97:6b:75 (DSA)
|   2048 20:3d:2d:44:62:2a:b0:5a:9d:b5:b3:05:14:c2:a6:b2 (RSA)
|   256 96:02:bb:5e:57:54:1c:4e:45:2f:56:4c:4a:24:b2:57 (ECDSA)
|_  256 33:fa:91:0f:e0:e1:7b:1f:6d:05:a2:b0:f1:54:41:56 (ED25519)
80/tcp    open     http        Apache httpd 2.4.7 ((Ubuntu))
|_http-favicon: Nmap Project
|_http-server-header: Apache/2.4.7 (Ubuntu)
|_http-title: Go ahead and ScanMe!
1068/tcp  filtered instl_bootc
9929/tcp  open     nping-echo  Nping echo
31337/tcp open     tcpwrapped
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 29.26 seconds
[tux@dactuxone ~]$ 

################################################################################

[tux@dactuxone ~]$ hostnamectl |grep -vw Hardware
 Static hostname: dactuxone
       Icon name: computer-laptop
         Chassis: laptop 💻
      Machine ID: c0f598781dd345c8a149cf92eb2a470b
         Boot ID: 65763ea8f21a4462885a37347ef4167a
Operating System: Fedora Linux 36 (Workstation Edition Prerelease)
     CPE OS Name: cpe:/o:fedoraproject:fedora:36
          Kernel: Linux 5.17.1-300.fc36.x86_64
    Architecture: x86-64
[tux@dactuxone ~]$ 
[tux@dactuxone ~]$ flatpak info org.nmap.Zenmap

Zenmap - A cross-platform GUI for the Nmap Security Scanner

          ID: org.nmap.Zenmap
         Ref: app/org.nmap.Zenmap/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.92
     License: GPL-2.0-only
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 83.9 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: e3ebe485ca764ef11c30eda9908f4738273e8f8ed7df0826feb573d5fb9e5047
      Parent: 4e1591b441ddceafb13b42434eb2acb39c6fb15a3f7fbdee24f2227a4c6feecc
     Subject: Better cleanup for PyGtk modules (9e505d5c)
        Date: 2021-12-28 21:07:36 +0000
[tux@dactuxone ~]$ 
[tux@dactuxone ~]$ flatpak run org.nmap.Zenmap
Traceback (most recent call last):
  File "/app/bin/zenmap", line 113, in <module>
    import zenmapGUI.App
  File "/app/lib/python2.7/site-packages/zenmapGUI/App.py", line 89, in <module>
    import gtk
  File "/app/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 69, in <module>
    _init()
  File "/app/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 57, in _init
    warnings.warn(str(e), _gtk.Warning)
gtk.GtkWarning: could not open display
[tux@dactuxone ~]$ 

################################################################################

[tux@dactuxone ~]$ python2 -V
Python 2.7.18
[tux@dactuxone ~]$ python3 -V
Python 3.10.4
[tux@dactuxone ~]$

**Comment by AliyevH** [comment]
Thank you very much for response.

Yes you are right nmap works as expected. 
But there's a lot of users who are confused with this error. What do you advice to do?
I will look at flatpak too.

**Comment by khaytsus** [comment]
org.nmap.Zenmap installs and runs here on Fedora 35 and Fedora 36, so unclear what @AliyevH is having issues with.

**Comment by goarblt** [comment]
hello
https://www.evil.com/
