### ISSUE TITLE
nmap error script execution file

### ISSUE THREAD

**Issue by iWooglez** [nmap/nmap#2463]
With nmap version 7.92 and using the -sV parameter I get the error Script execution failed in the sslv2, ssl_cert, tls-nextprotoneg, tls-alpn and ssl-date files.
[error.txt](https://github.com/nmap/nmap/files/8457648/error.txt)

**Comment by goarblt** [comment]
hello
https://www.evil.com/

**Comment by dmiller-nmap** [comment]
These are expected errors, of the following format:

```
NSE: <script_name> against <target> threw an error!
TIMEOUT
stack traceback:
	[C]: in local 'try'
	<stack trace continues>
```

This is a result of scripts using the [`nmap.new_try()`](https://nmap.org/nsedoc/lib/nmap.html#new_try) function to stop execution immediately when certain failures (usually connection problems like timeouts) occur. I will be pushing a change shortly to hide this output so that it no longer resembles an error.
