### ISSUE TITLE
XML output contains closed/filtered port information despite passing --open flag

### ISSUE THREAD

**Issue by c-sh0** [nmap/nmap#2478]
**Describe the current behavior**
When passing the `--open`  flag to only show open (or possibly open) ports along with XML output `-oX` flag, The output will still contain closed/filtered port information in the "extrareasons" element. Normally this isn't a big deal however, when running full port range scans (`-p-` option), the file becomes large and cluttered. Specifically in situations when scanning a large number of subnets.

**Expected behavior**
Do not include closed/ignored port information when passing `--open` flag.

**Comment by dmiller-nmap** [comment]
The rationale for this behavior has been that XML output should be consistent, and that Nmap should provide all useful known information in this format regardless of display option, since it is not meant for display, but rather for machine processing. For instance, the `reason_ttl` attribute is included even if the user did not use the `--reason` command-line option. An XML stream processor (e.g. a SAX parser) can easily remove extraneous elements or attributes if needed.

I'll leave this issue open for discussion for a while, but my instinct is to say we will not change this behavior.

**Comment by c-sh0** [comment]
_meh_, It won't hurt my feelings at all if this is closed. Typically when supplying arguments to other programs, the options are also reflected in the output no matter the format. After reading the XML doc a bit more, I can understand the rational. It just threw me off a little bit is all. ;) 

Thanks for the clarification.

**Comment by fyodor** [comment]
Thanks folks.  Yeah, if Nmap already "knows" some information, we generally try to keep it in the XML even if it's not displayed in user output.  Users might like to limit information in the normal output for easy review, but still have it in the XML in case they need it later.  Having too much info in the XML is generally less of a problem (since it's so easy to remove/ignore) than having information unavailable.  Cheers.
