### ISSUE TITLE
nmap reports host down when they are up

### ISSUE THREAD

**Issue by dieguillosavia** [nmap/nmap#2498]
nmap reports host down when they are up.
nmap -sn 192.168.26.2-50 report only 3 host when really is 33
Same problem whith nmap -sP
ping respond ok
![imagen](https://user-images.githubusercontent.com/108895182/177841022-271c77ef-a09a-4d58-96bb-fe01d3bb169a.png)
![nmap fail](https://user-images.githubusercontent.com/108895182/177841155-eaa91043-d645-45e0-80da-8ffcbdc009eb.png)

**Comment by bka-dev** [comment]
The most likely reason for this is, that you run nmap with limited permissions (not running as root, or with CAP_NET_RAW).

Without root privileges and unless configured otherwise, nmap sends TCP-SYN packets to ports 80 and 443 during a Ping-Scan.

If you run nmap as root, it sends out the following probes:

- ARP, if the targets are within the same subnet
- ICMP-Echo Request
- TCP-SYN: 443
- TCP-ACK: 80
- ICMP-Timestamp Request

You should re-scan the targets with proper permissions and compare the results
