### ISSUE TITLE
Make Nmap and Npcap OEM installer options case insensitive

### ISSUE THREAD

**Issue by fyodor** [nmap/nmap#2521]
Given that the Nmap (and Nmap OEM) self-installers don't have many options, we are probably not going to ever want arguments that differ only in case.  So there is probably no reason to require the "correct" case as we do now.  We only need to document /S and /D, for example, but it would be nice if /s and /d work too.  We'll have to figure out if there's an easy way to do this with NSIS.

Related issue for Npcap: https://github.com/nmap/npcap/issues/630

**Comment by dmiller-nmap** [comment]
All our implemented options are case-insensitive due to using the `GetOptions` macro (case insensitive) and LogicLib's `==` comparison operator. Both Nmap and Npcap have additional code now to make the `/S` (silent install) option case-insensitive. The `/D` option (installation directory) is not case-insensitive, but given the special handling NSIS uses for that option, we cannot change it.
