### ISSUE TITLE
nmap throwing script errors on '-sC -sV' options

### ISSUE THREAD

**Issue by PotatoWatch** [nmap/nmap#2590]
**Describe the bug**
NMap throwing errors when using `sudo nmap -sC -sV {ip}`

**To Reproduce**
Sequel activity on HTB.
sudo nmap -sC -sV 10.129.80.164

**Expected behavior**
It is supposed to show open ports protocols and version along with other info. It should contain a MariaDB instance. 

**Version info (please complete the following information):**
 
OS: Parrot HTB 5.1.2 Electro Ara amd64
NMAP v7.92
IFLIST output:
![image](https://user-images.githubusercontent.com/82115501/209199946-b081613d-d646-4e1c-9d91-1a84134a0043.png)

**Additional context**
This is running on an HTB network if that matters (via openvpn).

**Pictures**
Output:
![image](https://user-images.githubusercontent.com/82115501/209199672-fb59a63e-632f-41e9-bc4b-bbf014f249b3.png)

NMAP Version output:
![image](https://user-images.githubusercontent.com/82115501/209199819-2d270d13-332c-4d79-a2a4-85571430074b.png)

**Comment by dmiller-nmap** [comment]
The only errors I see here are related to handled script errors in SSL and TLS scripts running against a MySQL (or MariaDB) service. If the service does not support SSL connections, this is expected behavior. As the script output suggests, you can add the `-d` option to get more detailed information about the behavior and status of these scripts. I'm closing this issue, but if you have particular debug output (with `-d`) showing an unexpected error, you may open a new issue.
