### ISSUE TITLE
`nmap -oX` refuses to write to a pre-existing XML output file owned by a regular user when ran under `sudo`

### ISSUE THREAD

**Issue by postmodern** [nmap/nmap#2621]
When `nmap` is ran under `sudo` with the `-oX` option to write output to an existing file owned by a regular user, `nmap` refuses to open the file for writing even though `nmap` is being ran as root.

### Steps To Reproduce

1. `touch /tmp/scan.xml`
2. `sudo nmap -oX /tmp/scan.xml 127.0.0.1`

### Expected Result

`nmap` opens the existing file for writing, writes to it, closes it, without changing the ownership of the file.

### Actual Result

```
Failed to open XML output file /tmp/scan.xml for writing: Permission denied (13)
```

### Version Information

 - OS: Fedora Linux 36
 - Output of `nmap --version`:
 
 ```
 Nmap version 7.93 ( https://nmap.org )
Platform: x86_64-redhat-linux-gnu
Compiled with: nmap-liblua-5.3.6 openssl-3.0.8 libssh2-1.10.0 libz-1.2.11 libpcre-8.45 libpcap-1.10.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

### Additional Context

It should be possible for a process running as root to open and write to a pre-existing file owned by a regular user.

```
$ touch /tmp/test.txt
$ sudo sh -c "echo test >> /tmp/test.txt"
$ ls -l /tmp/test.txt
-rw-r--r--. 1 postmodern postmodern 5 Mar 12 00:38 /tmp/test.txt
$ cat /tmp/test.txt
test
```

**Comment by fyodor** [comment]
Thanks for your report.  This is caused by a [recent Linux security feature](https://lwn.net/Articles/748141/) which "Disallows open of FIFOs or regular files not owned by the user in world writable sticky directories, unless the owner is the same as that of the directory or the file is opened without the O_CREAT flag."  You can turn this feature off by setting the fs.protected_regular sysctl to 0 [as described here](https://github.com/openzfs/zfs/issues/10742), or just direct your Nmap output to directories without the sticky bit set.  It can even just be in a subdirectory of /tmp.
