### ISSUE TITLE
Why does nmap sweep up lots of ports that don't exist

### ISSUE THREAD

**Issue by pyzhizhuren** [nmap/nmap#2650]
**NOTE: Npcap issues have moved to [the Npcap repository](https://github.com/nmap/npcap/issues/)**

**NOTE: Ncrack issues have moved to [the Ncrack repository](https://github.com/nmap/ncrack/issues/)**

**Describe the current behavior**
A clear and concise description of what the bug or current behavior is.

**Expected behavior**
Describe what you would like to happen instead.

**Comment by dmiller-nmap** [comment]
Thanks for asking your question. Unfortunately, there is not enough information here to understand the issue. Can you provide more information as suggested in the issue template?
* Describe the current behavior: what ports? What do you mean "don't exist"? What do you mean by "sweep up"?
* Expected behavior: What would you like Nmap to do instead?

I am closing this issue for now, but if you respond with more information, I can reopen it.
