### ISSUE TITLE
Segmentation Fault when --top-ports is greater than 4260 (nmap --top-ports 4261 ... Segmentation fault)

### ISSUE THREAD

**Issue by austinzwile** [nmap/nmap#2679]
See the following screenshot:

![image](https://github.com/nmap/nmap/assets/97855595/27746de0-fdaf-4acd-a41f-049292fb6d8c)

As you can see I am trying to do a `--top-ports` scan and I normally do 10,000 (`--top-ports 10000`) which doesn't fail. But today on a new distro upgrade and new nmap upgrade I try to run my normal top 10k port scan but it fails. 

I binary searched my way until I find the exact number at which it's failing, which was 4,261. If I do 4260 it runs the scan fine, but if I do `nmap --top-ports 4261 ...` a segfault is triggered. This is specifically with the `--top-ports` flag. 

If I try running `nmap -p1-65535 ...` it works fine. Same with the `nmap -p- ...` syntax. I'm no code expert but I think I remember seeing that the `--top-ports ...` flag converts into the nmap command into a really long string like this:

`nmap -p 11,21,22,23,25,53,80,88,113,135-139,..` 

which might be causing the buffer overflow. This is just a guess on my part so don't put too much stock into it.

I wasn't sure if this was a weird `zsh` thing so I ran it under the regular shell and got the same result:

![image](https://github.com/nmap/nmap/assets/97855595/f8e2d562-cf69-433f-a6bf-2c4a627340a1)

If any more information is needed please let me know and I'll be happy to provide it. Hopefully we can figure out what's going on. Thanks for your support!

**Comment by TheProdigyLeague** [comment]
Duplicate Lua Issue. See https://github.com/nmap/nmap/issues/2672

Options cause a requested scan (including host discovery scans) to use tiny fragmented IP packets...

This idea is split up between the TCP header and over several packets to make it harder for pkt filters, intrusion detection systems, and other annoyances to detect what you are doing.  
/!\ Some progs have trouble handling these tiny pkts. 
The old-school sniffer (Named: Sniffit) Segmentation Faulted immediately upon receiving the first fragment. (Specify this option once, and Nmap splits the packets into eight bytes or less after the IP header.) 
So, a 20-byte TCP header would be split into three pkts. Two with eight bytes of the TCP header, and one with the final four. Of course each fragment also has an IP header. 
Specifically:
<option>-f</option> 
Again, uses 16 bytes per fragment (reducing the number of fragments.)
<indexterm><primary><option>-f</option></primary>
<secondary>giving twice</secondary></indexterm>

Or you can specify your own offset size with, 

<option>--mtu</option> 
<option>-f</option> 

If you use,

<option>--mtu</option>

The offset must be a multiple of eight. While fragmented packets won't get by packet filters and firewalls that queue all IP fragments, such as,

<varname>CONFIG_IP_ALWAYS_DEFRAG</varname> 

Options in the Linux kernel, some networks can't afford the performance hit this causes and thus leave it disabled. Others can't enable this because fragments may take different routes into their networks.  Some source systems defragment outgoing packets in the kernel. Linux with the iptables,

<indexterm><primary>iptables</primary></indexterm>

Connection tracking module is one such example. Do a scan while a sniffer such as,

<application>Wireshark</application>
<indexterm><primary><application>Wireshark</application></primary></indexterm>

Is running to ensure that sent packets are fragmented.  If your host OS is causing problems, try

<option>--send-eth</option>
<indexterm><primary><option>--send-eth</option></primary></indexterm>

Option to bypass the IP layer and send raw ethernet frames.

</para>

http://bugs.debian.org/cgi-bin/bugreport.cgi

bug=724580

~hope this helps

**Comment by dmiller-nmap** [comment]
The problem was a missing brace around a decrement. Fix incoming.

**Comment by austinzwile** [comment]
Thanks y’all! Preciate the help.

**Comment by talilama** [comment]
Hey Austin, just a heads up you might want to obfuscate your client's company name from public screenshots!
