### ISSUE TITLE
Potential memory leak in NpingOps.cc

### ISSUE THREAD

**Issue by icy17** [nmap/nmap#2722]
In nping/NpingOps.cc: 2801: 
Calling [pcap_findalldevs](https://github.com/nmap/nmap/blob/master/nping/NpingOps.cc#L2801C27-L2801C38) without releasing the parameter 1 cause memory leak.

**Comment by dmiller-nmap** [comment]
Nping calls pcap_findalldevs once at the beginning of its run, and it uses the device name from the results of that call throughout its run time. The memory does not need to be freed explicitly because it is needed until the program terminates. This may not be the best design, but it is not a functional memory leak. We would welcome a patch that fixes the issue.
