### ISSUE TITLE
Script-arg for TLS SNI extension when host.targetname is nil

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#276]
http://seclists.org/nmap-dev/2016/q1/46

Need to decide:
- Which has precedence, `host.targetname` or the script-arg?
- What name and where to implement? Probably `tls.servername` and provide an accessor function in the `tls.lua` library that takes the host and returns the most appropriate name.

**Comment by dmiller-nmap** [comment]
Ran across a local branch I had that had started on a different, related problem. We should check for the `unrecognized_name` alert indicating that we've chosen a bad value for SNI. Probably the accessor function should check the host for each name until it gets one that doesn't generate the alert, then cache that name in the host's registry and return it on subsequent calls. That way all scripts can benefit with minimal work. Would require a mutex to avoid checking multiple times.

**Comment by bbc2** [comment]
As the use of SNI when `host.targetname` is present is implicit, I would say the script-arg should have precedence because it would be explicit.

I've given a go at implementing a simple version on [bbc2/nmap/tls-servername-arg](https://github.com/bbc2/nmap/tree/tls-servername-arg) although I'm not used to developing nmap scripts.  Does it seem mergeable?

The scripts ssl-cert and ssl-known-key seem to send a server name via a regular SSL socket (via `nselib/sslcert.lua` library which uses nmap's nsock library).  Those two should probably take the `tls.servername` script-arg into account but I don't know enough of the codebase to be able to provide a good patch for them.

I'm not sure about the `unrecognized_name` alert because I could not observe one with the clients and servers I tested.  Do you know a setup that triggers this alert and makes it observable?

**Comment by dmiller-nmap** [comment]
Accepted @bbc2's solution at #540, with slight modification.
