### ISSUE TITLE
Add 'newtargets' argument option to broadcast-dhcp-discover script

### ISSUE THREAD

**Issue by grintor** [nmap/nmap#2786]
The broadcast-dhcp-discover script gets a subnet mask where there are probably other hosts. It seems like a great candidate for target discovery. I was surprised it didn't support it already. I think it would be a great feature.

**Comment by nnposter** [comment]
Traditionally, `newtargets` is used to add IP addresses or hostnames for which there is some evidence of their existence, not a bulk inclusion of entire subnets. Since the Nmap host is already sitting on some local subnet with a configured IP address and mask, then I am not sure that pushing all potential local IP addresses to the scan queue via `newtargets` would add any material value over specifying the subnet explicitly. Queuing up the IP address of the DHCP server is already done by `broadcast-listener`.

Can you elaborate further on the use case?

**Comment by nnposter** [comment]
Please feel free to reopen the issue if you have a tangible use case.
