### ISSUE TITLE
help/usage text misinforms about -sn parameter

### ISSUE THREAD

**Issue by crysman** [nmap/nmap#2871]
**Describe the bug**
--help/-h/usage misinforms about `-sn` parameter, twice.

1. It says port scan is not used, which is not true according both to `man` and captured traffic.
2. In case of LAN scan under root, it uses arp-scan, not `ping` (ICMP echo), so naming it "Ping Scan" is misleading.

**To Reproduce**
![image](https://github.com/nmap/nmap/assets/5269350/2f82d22f-69e3-47d8-a4f8-7c18ecc1a9f8)

vs.

![image](https://github.com/nmap/nmap/assets/5269350/4988d851-2db0-4bf2-992c-aa2660c37675)

**Expected behavior**

1. Both usage help and man contain true information, that is, usage text on `-sn` line acknowledges it uses two TCP connections, too, and that in case of LAN under priviledged user performs arp-scan. 
2. Consider change so that `-sn` behaved as if with `-PE`, that is no TCP scans whatsoever, just pure ICMP. (The fact that it uses arp is reasonable).

**Version info (please complete the following information):**
```
$ nmap --version
Nmap version 7.80 ( https://nmap.org )
Platform: x86_64-pc-linux-gnu
Compiled with: liblua-5.3.6 openssl-3.0.2 nmap-libssh2-1.8.2 libz-1.2.11 libpcre-8.39 libpcap-1.10.1 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

**Comment by dksslq** [comment]
icmp-echo is one of the ping methods.

**Comment by nnposter** [comment]
The usage section is meant to be a short and limited overview of the options, mostly captured as one-liners. There is simply no room to explain all the nuances. Limiting the host discovery to ICMP echo request by default is definitely not desirable, as more frequently than not, publicly-facing assets behind corporate firewalls are likely to be discovered by hitting common ports, not by spraying ICMP echo requests. Internal networks are of course a different story, so that's why Nmap does both.

More advanced users are expected to use the numerous Nmap options to tailor their scans to the specific target environment if they want to be less noisy, faster, more accurate, etc.

**Comment by crysman** [comment]
I believe this is very unfortunate, there is so much space left even on the one line:

![image](https://github.com/nmap/nmap/assets/5269350/906d7aa1-afe7-407f-a808-480516bb8d6f)

so **proper and true! explanation would fit without any trouble**:

![image](https://github.com/nmap/nmap/assets/5269350/63b884e2-5844-44a7-a52d-87b5bc095a38)

then - why to lie to users when there is no objective reason to do so (?)
