### ISSUE TITLE
Update Nmap release for OpenSSL 1.0.2f

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#288]
We should do a release so that Windows, OS X, and RPM users can get the latest OpenSSL. For the record, we do not believe any of the tools in the Nmap suite are vulnerable to the security bugs fixed in this release. Analysis follows.

## DH small subgroups (CVE-2016-0701)
This is limited to TLS server processes, so only Ncat could be affected. The flaw affects DH ciphersuites only. Ncat's code currently does not support DH ciphersuites, as evidenced by the lack of any calls to `SSL_CTX_set_tmp_dh`, `SSL_set_tmp_dh`, `SSL_CTX_set_tmp_dh_callback`, or `SSL_set_tmp_dh_callback`. Therefore it is our belief that Ncat is not vulnerable to this CVE.

## SSLv2 doesn't block disabled ciphers (CVE-2015-3197)
This vulnerability is limited to SSLv2 servers. Ncat specifically uses the `SSL_OP_NO_SSLv2` context option, so this vulnerability does not apply.

**Comment by gvanem** [comment]
Could it be possible to use [BoringSSL](https://boringssl.googlesource.com/boringssl/) instead? (as an option). I'm no sure how different OpenSSL and BoringSSL has become (since BoringSSL was forked 12 years ago). It's been done in other projects before (e.g. [*libcurl*](https://github.com/curl/curl)), but it's certainly lot of work...
