### ISSUE TITLE
Finish building and testing installer built with VS2013 on Windows 8.1

### ISSUE THREAD

**Issue by bonsaiviking** [nmap/nmap#29]
The goal is to have the next version of the Nmap installer built on VS2013. It builds just fine, but still need to test the installer build process and make sure the installer works all the way back to Windows Vista -- Windows XP will not be supported, though it may work anyway.

**Comment by dmiller-nmap** [comment]
User Mike reports failure to start due to missing VC++ 2013 Redistributables package: http://seclists.org/nmap-dev/2015/q2/208

I verified that the package is included in the zipfile and that the installer source shows that it should be installed if needed. Maybe it's not being properly bundled in the installer itself, or our detection routines may be incorrect. Need to reproduce.
