### ISSUE TITLE
Winbox Service Probe

### ISSUE THREAD

**Issue by deauther890** [nmap/nmap#2922]
Hello,

I wonder why Nmap doesn't contain Winbox service probe? Is there a certain reason for this?

I think there's a way to identify it by sending a payload that contains a username and password and it follow a certain pattern when the creds are wrong? Maybe this can be an intrusive script or something in Nmap!

Regards,

**Comment by gvanem** [comment]
> I wonder why Nmap doesn't contain Winbox service probe? 

It would help if you explain what it is first.

**Comment by TannicArcher** [comment]
Hello,
Winbox is indeed an important service for managing MikroTik routers, and having a service probe for it in Nmap could be valuable for network administrators.

The reason Nmap might not currently include a specific Winbox service probe could be due to the fact that this service is less commonly encountered or the probe hasn't been contributed by the community yet. Developing an accurate and reliable probe often requires detailed knowledge of the protocol and its behavior, especially under different conditions like incorrect credentials.

Your idea of identifying Winbox by sending a payload with a username and password, and then analyzing the response pattern, sounds promising. If you have more details on the specific behavior of Winbox when credentials are incorrect, it could indeed be a basis for creating an intrusive Nmap script or even a dedicated service probe.

You might consider contributing this as a script or probe to the Nmap project if you're familiar with how Winbox operates. This would certainly enhance Nmap's ability to detect and interact with MikroTik devices.

**Comment by alihadi890** [comment]
@TannicArcher 
Thanks for your reply. I don't have a specific knowledge of the winbox protocol but I built a script that can try login and also in other way can identify a running winbox service at port 8291. I tried few thousands of Mikrotik ips from shodan and I think the success rate is around 90%.
I have sent this on the official nmap email but I didn't get an answer!

**Comment by TannicArcher** [comment]
> @TannicArcher Thanks for your reply. I don't have a specific knowledge of the winbox protocol but I built a script that can try login and also in other way can identify a running winbox service at port 8291. I tried few thousands of Mikrotik ips from shodan and I think the success rate is around 90%. I have sent this to the official nmap email but I didn't get an answer!

You just need to wait, they should answer 100%
