### ISSUE TITLE
npcap uninstall fails if npf driver is in use

### ISSUE THREAD

**Issue by markpizz** [nmap/nmap#296]
If an application has a pcap connection open through the npf driver, an uninstall of the npcap fails ungracefully.

A message box titled "Npcap 0.05 for Nmap (beta) Uninstall" with the text "Failed to stop the npf service, stop uninstallation now.  Please stop using Npcap first" OK.

The Uninstall fails and the user is presented with an option to uninstall in compatibility mode.

This set of behaviors will be, at least, unexpected and certainly somewhat confusing for some users.

If someone attempts to uninstall WinPcap 4.1.3 when the npf service is in use, the user is presented with a dialog titled: "WinPcap 4.1.3 Uninstall", and the text says: "Completing the WinPcap 4.1.3 Uninstall Wizard" "Your computer must be restarted in order to complete the uninstallation of WinPcap 4.1.3.  Do you want to reboot now?" With a couple of radio buttons labeled: "Reboot Now" and "I want to manually reboot later", and a Finish button at the bottom of the dialog.

The WinPcap Reboot Now or Manually Later is what most folks would expect.  Someone who is actively uninstalling npcap may not have any idea which application is actually using the npf service or how to stop it from being used.  If they've engaged the uninstall it should uninstall one way or another.

**Comment by hsluoyz** [comment]
There are three handlings for uninstalling an in-use driver:
1) Finish the uninstalling procedure without affecting the current session. All clean-up will be done in next reboot. (like ``WinPcap``'s way)
2) Wait for a timeout, then prompt the error about uninstallation failure. (like ``Npcap``'s way)
3) Halt the uninstallation infinitely.

In user's view:
I don't think 1) is always the best choice, because after uninstalling Npcap. You may want to reinstall it or upgrade it before the reboot. Then the next reboot will remove the newly installed version. This can be confusing.

In implementation:
At first, Npcap's behavior about uninstalling is the same with WinPcap. Then somehow Npcap turns to the 3) way. It's not good to give the user a permanent halt. Also it causes some kind of crash (see: https://github.com/nmap/npcap/commit/622e1d14505a4cd86735b3cbcc392db84fedd144). So I decided to set a timeout and make Npcap behave in 2) way.

I will see what else I can do to improve this logic.

**Comment by hsluoyz** [comment]
I have fixed this issue in https://github.com/nmap/npcap/commit/61ecc19832c775178f8b32ae0c88ab0b563db3ae
