### ISSUE TITLE
npcap signing fails on some windows

### ISSUE THREAD

**Issue by markpizz** [nmap/nmap#298]
According to the ReadMe at https://github.com/nmap/npcap "Npcap makes use of new LWF driver in Windows Vista and later (the legacy driver is used on XP)"
This suggests that the goal is to be a completely compatible replacement for WinPcap on all platforms WinPcap supports (from XP onward).  The current version of npcap fails to install on some versions of windows due to signature verification issues.

I installed a clean system with Windows 7 SP1 and the first thing I did was install WinPcap.  It installed cleanly and it worked fine.  I uninstalled WinPcap and for good measure I rebooted the system.  I then tried to install npcap and the installation process complained about driver signing issues.

**Comment by hsluoyz** [comment]
The issue has already been talked about in this release: https://github.com/nmap/npcap/releases/tag/v0.05-r8 and these posts in Wireshark forum: https://ask.wireshark.org/tags/npcap/

I also added a description about this issue on the README: https://github.com/nmap/npcap/commit/eb942cc17585e483cb04f3208759d258c6a87821

**Comment by hsluoyz** [comment]
The latest version Npcap 0.05 R12 has resolved the installation failure in Win7 SP1, make sure you installed ``KB3033929`` for Win7 with SP1: https://technet.microsoft.com/en-us/library/security/3033929.aspx.

Latest installer can be found at: https://github.com/nmap/npcap/releases

**Comment by markpizz** [comment]
Hi Yang,

Well, having to install some other thing (KB3033929) before installing npcap would seem to be, at best, a 'work around'.  

If someone was to use WinPcap instead they would not have to install KB3033929 first.  It therefore is certainly not a 'drop in' replacement for WinPcap.

**Comment by hsluoyz** [comment]
The latest version Npcap 0.05 R13 has resolved the installation failure in Vista, 
Latest installer can be found at: https://github.com/nmap/npcap/releases

Personally I think asking the users to install ``KB3033929`` on their Win7 laptop is an acceptable price for better security they can get. And at least by now I didn't receive a report complaining this strategy. Users usually install this patch readily.

**Comment by markpizz** [comment]
Other projects which imbed or otherwise leverage WinPcap will be less likely to include it if it adds other non-obvious external dependencies to their users.  I say non-obvious since one would merely expect the install to work without raising security warnings...

Since you've made a significant effort to include the prior WinPcap pieces to install on platforms which don't have NDIS6 support, it seems the goal is to have as simple as possible a user experience.  Not 'just working' is less than simple.

**Comment by hsluoyz** [comment]
Hi markpizz,

I reconsidered the issue. I think you are right. Npcap should be a **Drop-In** replacement of WinPcap. So it should not assume the users have installed any kinds of patches. 

Now I used the legacy SHA1 code signing cert to sign the Npcap driver in **Win7**, so no need for **Win7** users to install ``KB3033929`` patch any more.

I just released Npcap 0.05 R14.
Latest installer can be found at: https://github.com/nmap/npcap/releases

PS: This version Npcap is supposed to have fixed all signing errors, so it will successfully install on all the platforms: **Vista, Win7, Win8, Win8.1 and Win10** without any prerequisites.

**Comment by markpizz** [comment]
Hi Yang,

Thanks.

Meanwhile, on the subject of "Drop-In replacement of WinPcap".  Is it possible to NOT install the Npcap Loopback driver which creates an additional network interface on the machine.  WinPcap didn't change the set of network interfaces.  

What does the installer checkbox option "Use DLT_NULL protocol as lookback packets' link layer instead of Ethernet II" actually do?  (By the way, I would replace "packets'" with "packet" in that text).

My "WinPcap" application calls pcap_findalldevs and for each device returned it calls pcap_open_live and then calls pcap_datalink to find those with datalink type DLT_EN10MB.  It seems that the npcap interface always returns DLT_EN10MB without regard to the selection of the installer's "Use DLT_NULL" checkbox?

Thanks.

- Mark

**Comment by hsluoyz** [comment]
Hi Mark,

``Meanwhile, on the subject of "Drop-In replacement of WinPcap". Is it possible to NOT install the Npcap Loopback driver which creates an additional network interface on the machine. WinPcap didn't change the set of network interfaces.``

Do you mean making the loopback support of Npcap **optional** in the installer? This is actually possible and won't take many efforts to add it. But do you think this is a good idea? Because what I saw is that everyone loves this function.

``What does the installer checkbox option "Use DLT_NULL protocol as lookback packets' link layer instead of Ethernet II" actually do? (By the way, I would replace "packets'" with "packet" in that text).``

There are two differences if you checked that option:

1. ``pcap_datalink`` function will return ``DLT_NULL`` instead of ``DLT_EN10MB`` for ``Npcap Loopback Adapter``.
2. The **data link layer** in your packet bytes captured from ``Npcap Loopback Adapter`` will be ``DLT_NULL`` protocol instead of ``Ethernet`` protocol, which you can easily see in Wireshark.

The above effects involve modifications in all modules: ``wpcap.dll, Packet.dll and the driver``.

If you ask what the **installer** particularly does, it just set a registry key ``DltNull`` in ``HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\npf``. It's a ``REG_DWORD`` type. If the option in the installer is checked, then ``DltNull``=1, if not checked, ``DltNull``=0. The driver will read this registry key to decide whether ``NdisMediumNull`` or ``NdisMedium802_3`` is returned to ``Packet.dll``. See details in https://github.com/nmap/npcap/commit/edb4f4c5be222981b9747c39cd2b9f92b540505c

``My "WinPcap" application calls pcap_findalldevs and for each device returned it calls pcap_open_live and then calls pcap_datalink to find those with datalink type DLT_EN10MB. It seems that the npcap interface always returns DLT_EN10MB without regard to the selection of the installer's "Use DLT_NULL" checkbox?``

If you have "Use DLT_NULL" checked in the installer, then you will get ``DLT_NULL`` by calling pcap_datalink on ``Npcap Loopback Adapter``. If you don't check it, you will just get the same ``DLT_EN10MB`` on ``Npcap Loopback Adapter`` like other adapters. I think this is the correct behavior. Because for all these years, nearly all softwares assume all the adapters should be Ethernet type. So allowing not checking "Use DLT_NULL" option will provide better compatibility for those softwares.

Cheers,
Yang

**Comment by hsluoyz** [comment]
Hi Mark,

BTW, why do you want to replace "packets'" with "packet" in the option text ``Use DLT_NULL protocol as lookback packets' link layer instead of Ethernet II``? I thought the wording should be **plural** because it should take effect on all the packets, not a single packet, right?

**Comment by markpizz** [comment]
Hi Yang,

First, I misspelled "loopback" when I transcribed the text of that message (my fault please fix).
Next..., yes, there are many packets flowing through the interface, but this selection is an attribute of "THE" interface (there is only one interface).  It is not as if you could allow provide a way for some packets to have DLT_NULL and others to have DLT_EN10MB.  So I suggest the string should say: :"Use DLT_NULL vs DLT_EN10MB (Ethernet II) as the loopback interface link layer protocol type"

Thanks,

- Mark

**Comment by hsluoyz** [comment]
Hi Mark,

I have improved the wording of this option. See: https://github.com/nmap/npcap/commit/efe72381efcaaa017af7786a762385620a99da0a

**Comment by markpizz** [comment]
Hi Yang,

That looks better.  The ' character isn't necessary though.
