### ISSUE TITLE
OS X installer: Have graphical installation instructions in the .dmg file

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#299]
I have no idea how they do this, but it'd be cool to have: Oracle VirtualBox's .dmg installer shows step-by-step instructions on installation when you open it.

![Image of Oracle VirtualBox's .dmg installer window](https://straymarcs.net/wp-content/uploads/2014/03/mac_virtualbox_dmg_installer.png)

**Comment by W0naN0w** [comment]
Dear Mr Miller,

I came upon your post yesterday, and believe I have a solution for you. I have attached a screenshot of my proposal, and wanted to know if it is similar to what you expected?
If so, I would like to be assigned to this project if possible. 
Also, I am working on a mac os x with all the building tools installed and would be glad to contribute!

<img width="1084" alt="nmap_dmg_design" src="https://cloud.githubusercontent.com/assets/16716213/12914518/f69ddb64-cf24-11e5-8763-4df8d7e01f4b.png">

P.S. Here the .mpkg is selected.

Yours Sincerely,
Vincent Dumont

**Comment by W0naN0w** [comment]
Feel free to download the .dmg package at http://vincentdumont.com/Nmap_template.dmg which is about 33 Mb.

Yours Sincerely,
Vincent Dumont

**Comment by dmiller-nmap** [comment]
@W0naN0w _Merci_, thanks for your interest! Would you be able to explain how this is accomplished? Our build is run by the `macosx/Makefile` in the Nmap source, with the `.dmg` package being built on [lines 73 to 75](https://github.com/nmap/nmap/blob/master/macosx/Makefile#L73-L75). What would we need to change to make this possible?

**Comment by W0naN0w** [comment]
**@dmiller-nmap** Thank you for your feedback! I am actually having a lot of issues while trying to launch the Makefile on my OSX 10.11 with the python path, the openssl libraries issue of the latest OSX versions or the nmap-build path to name a few. I corrected these ones but I am now having problems with the nse_openssl.cc file, as shown below : 
![tty_screenshot](https://cloud.githubusercontent.com/assets/16716213/12957997/a08caef6-d02f-11e5-807d-308bb0d8b659.jpg)

As for the .dmg package I just added a ".background" folder at the root of the virtual disk with a photoshoped background (that I can still adapt through your needs) in it. Then I wrote the path of the file into the virtual disk. To finish, the .dmg has to be converted to a read-only disk (which I did with the "Disk Utility" application, but I am sure this can be done by command line).

Also could you take a look at the screenshot and tell me your opinion about the errors?

Finally, if you want a copy of my current Makefile, just tell me!

**Comment by W0naN0w** [comment]
Hello everyone,

In order to port the customisation of the nmap DMG disk image into the _Makefile_, I wrote a simple shell script (_createdmg.sh_) in which _hdiutil_ is properly used with some applescript commands.
So the _Makefile_ located in the macosx/ folder should call this script instead of the _hdiutil_ line (which is now in the script).
Please not that the script won't work if there are other nmap untitled virtual disk images mounted on your machine.

The zip content (background image and script .sh) should be copied to the macosx/ folder.
[AddToMacosxFolder.zip](https://github.com/nmap/nmap/files/130840/AddToMacosxFolder.zip)

P.S. : here is a capture of my folder organisation (note that build/ is composed of the final content of the .dmg)
<img width="702" alt="tree" src="https://cloud.githubusercontent.com/assets/16716213/13050352/12665326-d3f3-11e5-90ca-9652111c8d51.png">


I am waiting for your feedback,
Yours Sincerely

Vincent Dumont

**Comment by W0naN0w** [comment]
Dear Nmap community,

Here is the updated Makefile, I will pull a request on it, but I need you to tell me what you think about it, and most importantly, if it works on your machines! 
I put it in a .zip along with nmap.png (the .dmg background) and the createdmg.sh script mentioned earlier.
[AddTheContentToMacosxFolder.zip](https://github.com/nmap/nmap/files/139719/AddTheContentToMacosxFolder.zip)

I am waiting for your feedback,
Yours Sincerely

Vincent Dumont

**Comment by W0naN0w** [comment]
Pull request #310 posted!
Always a pleasure to contribute to Nmap.

Have a good day,

Vincent Dumont

**Comment by sharad1126** [comment]
HI @W0naN0w . I am Sharad Agarwal, a sophomore at VIT University. I would like to know what is this issue all about .

**Comment by W0naN0w** [comment]
Hello @sharad1126, thank you for your interest but this issue is nearly fixed.

**Comment by dmiller-nmap** [comment]
Closed in efae235cc5.
