### ISSUE TITLE
Npcap github repository was rehashed

### ISSUE THREAD

**Issue by Komosa** [nmap/nmap#305]
Hi,
Some time ago (13rd of Jan) I recognized that whole npcap repository on github was somehow rewritten - actual code meaning is the same, but things like formatting and contextual information were changed.
**Each commit get new hash** (!).
Old hash of commit tagged as v0.05-r4 https://github.com/nmap/npcap/commit/fc6bcd7bfedcf1fd999a100e9b7e134af654d6aa (cool that github keeps this :))
Hash of _corresponding_ commit in actual history: https://github.com/nmap/npcap/commit/f8646a11de241d798c5e35d84ca1449f8d953515 (note that tag is lost).

After that I switched to "new" version and rebased my local changes on top of it.

Issue above (full rehash) arises again (noticed totady: 17.02.16).
Old hash of commit tagged v05-r6: https://github.com/nmap/npcap/commit/c6ba0dacf17c52eea767686bd6b6a4c38aebf6d9
Hash of _corresponding_ commit in actual history: https://github.com/nmap/npcap/commit/76316432f6ddc3b5e2253bac837fbb4c988b998f

First rehash happens between v05-r4 and v-05-r5.
Second rehash happens between v05-r8 and v05-r9.

---
First time I was thinking, that this was just incident (lets say that it is not that bad, remembering that repo was ported from svn).
Now I think that we must resolve that problem, there are three possibilities:
- rehashes are done by github automatically = configuration error
- it is done intentionally, (eg by rebase), if so, it will be good to stop doing this or at least explain why it is necessary
- unintentionall unknown actions are performed = need to hunt them and prevent.

Or I'm very wrong somewhere.

thanks,
Przemek Komosa

**Comment by hsluoyz** [comment]
Sorry for the inconvenience if you have forked Npcap's repo at that time. I suggest you do a clean re-clone to get the latest consistent code.

Actually this whole rehashing is because I was cleaning up the repo. Some executables remained in the repo accidently long time ago. And I decided to remove them permanently and improve the history's looking by rewriting the history.

I'm aware that this is not a good practice. What's good is that this won't be likely to happen again.
