### ISSUE TITLE
Zenmap on OS X does not pick up user's locale/language preferences

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#340]
Because of the authorization wrapper, Zenmap runs as root, and so does not have access to the user's language/locale preferences. We should find a way to pass these along in the environment so OS X users can take advantage of our translations.

This issue could possibly be solved alongside #73 or #250.

**Comment by W0naN0w** [comment]
Dear Mr. Daniel Miller, 
Dear dev list,

I am writing to you concerning the authorization wrapper used in Zenmap and my first GSOC application.
All the issues you are pointing to in this email are part of my proposal. 

Therefore, I would need feedback before the deadline.
It will be a pleasure for me to have different opinions from this mailing list, but because my proposal is intended to you, it will be the most valuable one.

Thank you in advance for your time,

Vincent Dumont
contact@vincentdumont.com
http://www.vincentdumont.com <http://www.vincentdumont.com/>

**Comment by dmiller-nmap** [comment]
Fixed in 4c1ef96 and e4fcf23
