### ISSUE TITLE
Measuring UDP delay/rtt

### ISSUE THREAD

**Issue by lghamie** [nmap/nmap#398]
Hi! I'm trying to measure UDP delay or rtt.

I'm trying to use echo-server for that. But I always get ICMP's Port unreachable, still cant figure out why.

Running server as: nping --echo-server testing --udp --ep 10000
And client as: nping --echo-client testing <server-ip> -ep 10000 --udp

This is running on Ubuntu14.04 nping version 0.6.47

Any idea of what I might be doing wrong? Thanks!

**Comment by dmiller-nmap** [comment]
You are sending a UDP packet to port 40125 (the [default specified in nping.h here](https://github.com/nmap/nmap/blob/6e33d6ac3c767e8b519818067a94032f3782a72d/nping/nping.h#L377)), and since you don't have a service running on that port, your target responds with ICMP Port Unreachable. If you run a UDP service on that port, then it *may* respond with a UDP packet, but it depends on what data you sent and what the service expects. There's no guarantee with UDP. The ICMP packet should show the same time characteristics as a UDP response, though, so you can use it for RTT measurement.
