### ISSUE TITLE
PATH variable in System variables section was replaced by 'C:\Windows\system32\Npcap' entirely

### ISSUE THREAD

**Issue by yuriy-blinov** [nmap/nmap#404]
Version installed: https://github.com/nmap/npcap/releases/download/v0.07-r10/npcap-0.07-r10.exe 
System version: Windows 7 Prefessional / Service Pack 1

**Comment by hsluoyz** [comment]
Hi @yuriy-blinov ,

This is a known issue for our packaging system, NSIS.

I re-checked that since I used [NSIS large strings build](http://nsis.sourceforge.net/Special_Builds) the ``PATH`` should not be replaced if its length is less than 8192 bytes. Do you have that length ``PATH``?

If yes, then you probably encounter this issue. Here's the solution.

1. Manually add ``C:\Windows\system32\Npcap`` to your PATH
2. Install Npcap, Npcap will find that you already add that path and will not add it again, so no replacement will happen.

**Comment by hsluoyz** [comment]
@yuriy-blinov ,

Please try the latest Npcap 0.07 r12.1, it has guaranteed the use of ``NSIS large strings build``.

I hope this would help:
https://github.com/nmap/npcap/releases
