### ISSUE TITLE
Impose a resource size limit for NSE's http library

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#473]
As noted in #467, NSE has performance problems when a target serves lots of big files. We want to avoid getting bogged down with things like this, so we should impose a 1MB file size limit, with options to increase or remove the limit via script-args. Some specifics:
- We should check the Content-Length header value when possible
- We should check the size of the download regardless of Content-Length.
- Need something in the response to indicate truncated result, and maybe something in the options to indicate maximum expected result?

**Comment by nnposter** [comment]
As a general approach I am proposing the following:

* Newly implemented library parameter `http.max_body_size` defines the maximum response body size the library is willing to receive. The default value would be somewhere between 1 and 5 MB. (These days even non-image resources occasionally exceed 1 MB.)
* This behavior can be overridden by request option `max_body_size`, including disabling the limit altogether.
* This enforcement applies to raw bodies as they are received, regardless of method (`Content-Length`, `Transfer-Encoding`, or connection termination)
* This enforcement also applies when bodies are getting decoded according to `Content-Encoding`. This provides protection against the so-called zip bomb.
* Bodies that exceed the limit are still made available in truncated form through the returned response object.
* The response object would have `status` member equal to `nil`. In other words, the response is composed as a failure, so scripts would *not* use it unless they explicitly want to.
* Just as with the status, member `body` would be `nil` so scripts would *not* accidentally use the truncated body.
* The actual incomplete *response object*, not just the body, would be preserved in member `fragment`, which is currently being used for returning partially received bodies. (We could rename it to be more descriptive, such as `incomplete` or `incomplete_response`, and to avoid potential contextual confusion with URL fragment.)
* This `fragment` re-purposing is generally beneficial because it would also allow scripts to see other response details, such as the original status code and/or headers. There is no change impact because nothing is presently consuming `fragment` in its current form in the first place.
* In summary, the truncated body would be available as `response.incomplete.body` and scripts that do not care about the truncation would go for `response.body or response.incomplete.body`.
* The library would *stop* receiving socket data when the size limit is reached, leaving the open socket in a state unfit for further use. In other words, the library would not try to "suck up" and discard the remainder of the body.
* When encountering such situation, routine `pipeline_go` would have to close the current socket and resubmit the pipeline volley, starting with the next request in line.
* There are some other socket reuse cases related to authentication but they could be possibly left unresolved for now because the bodies should not be oversized in the first place.
* In other cases the connection appears to get closed anyway.

**Comment by cldrn** [comment]
I agree something could be improved here. I often find myself setting the max-cache-size to 0 to disable and stop slowing down scans to web servers.

**Comment by nnposter** [comment]
As far as the code goes, so far I have modified the three key `recv_*` routines and the content decoder to enforce an optional size limit. The key question now is what is the best way to expose the truncated bodies.

I have felt that the truncation should not be transparent but also that it should not result in a complete failure either. The proposal above is a compromise between the two extremes. One additional feature could be that a new option, `truncated_ok`, could turn on the transparency.

**Comment by nnposter** [comment]
Implementation of the body size limit has been proposed in #1571.

**Comment by nnposter** [comment]
Implemented in r37627 (df2693232a629899c8fc9216273978931fbd58ad). See #1571 for details/discussion.
