### ISSUE TITLE
Make Npcap releases built on libpcap release branch, not "PRE-GIT" branch

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#506]
The latest release of Npcap, 0.08-r6, has this version string: "Npcap 0.08, based on libpcap 1.9.0-PRE-GIT". The the-tcpdump-group/libpcap repository has a branch for the 1.8.0 release that we should be using instead of the current development head. It is also tagged "libpcap-1.8.0" if that would be easier.

**Comment by hsluoyz** [comment]
There are some difficulties. There are some cooperation between Npcap and libpcap from 1.8.0 to the 1.9.0-pre-git. Not only Npcap uses libpcap code, but also libpcap is affected by Npcap to do some adaption work. Even some files have been renamed, moved or created. The changes are simultaneous for both repos.

This is a special period. Because Npcap starts the compatible plan with libpcap. libpcap needs some adaption to be able to work with Npcap. libpcap is not a pure "upstream" in this period. Like the monitor support, the automatic version display like ``libpcap 1.9.0-PRE-GIT``.  These functions require both repos' changes. The direct result is that if I revert the libpcap to 1.8.0, the master Npcap won't compile.

The key point is how we view Npcap's master branch? Is it dev or stable? Can it track the libpcap's master? Or we should use another branch like "dev" to track and keep the pace with libpcap's master. And how we release the binaries? If we decide release binaries based on master instead of dev, then our release cycle will be slowed down. This is not good for testing, because we usually build some test versions for each other to try. Maybe we also should separate stable versions and dev versions for Npcap?

**Comment by hsluoyz** [comment]
Npcap is now on ``libpcap 1.8.1`` release: https://github.com/nmap/npcap/commit/46ec77566b409ae642cfbc167bcdc2caf98e97c6
