### ISSUE TITLE
Don't see there the revision of the version installed

### ISSUE THREAD

**Issue by horovitzdan** [nmap/nmap#528]
I did some tests with npcap (installed on WIN8 and SRV2008R2. One thing I noticed that it is not possible to get what version of npcap is installed.
From what I saw npcap writes to the registry key its version:
"HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\NpcapInst" "DisplayVersion"="0.08" 

Unfortunately, I don’t see there the revision of the version. For example I installed version 0.08-r4 and I didn’t see any reference to “r4”. It would be good to add the “r4” too so we can actually know what is the revision installed.

**Comment by hsluoyz** [comment]
We decided not to add the revision number into the version string, because it's "unofficial" as a Nmap product. However, I don't like to bump the version for all releases. This is why we come to this implementation: let revision not show up in the final version string.

You can just view Npcap releases with revisions as "development" or "internal", and the releases without revisions as "stable" or "public". Actually, I provide the revision releases because I want the users to update to the best version without any bugs.

**Comment by hsluoyz** [comment]
What're your opinions? @fyodor @bonsaiviking 

I think we still need the revision shown up in the version string. Because sometimes when we test Nmap or Npcap new builds in our meeting, or fix some severe bugs, we need to frequently make a new release. And it's not light-weight enough to update the main version. Nmap also has its "revision", like the digit ``1`` in ``nmap-7.25BETA1`` or the digit ``3`` in ``6.49BETA3``. It also shows up in the ``nmap -V`` command.

So I suggest we add the revision to the displayed version string. Perhaps the style can be changed to use Nmap's ``XXBETAX`` if you like.

**Comment by hsluoyz** [comment]
This has been fixed in latest Npcap ``0.08 r8``, see installer at: https://github.com/nmap/npcap/releases
