### ISSUE TITLE
Update (telnet-brute) script documentation

### ISSUE THREAD

**Issue by jgeromero** [nmap/nmap#537]
When using 'brute.threads' it looks like it goes up to the value specified and may adjust downwards. Script needs to be looked at more carefully to confirm and update documentation if needed. Thank you!

**Comment by nnposter** [comment]
By design the script will reduce the number of threads if it senses that it maxed out the target connection capacity. (One example where this can happen easily is on Cisco IOS.) There is a documented parameter, `telnet-brute.autosize`, that controls this behavior.

Could you please elaborate further if I misunderstood your concern?

**Comment by jgeromero** [comment]
Ok so it dynamically adjusts and behavior can be controlled by the telnet-brute.autosize paramater. Thanks for confirming. Closing issue.
