### ISSUE TITLE
Zenmap display bug

### ISSUE THREAD

**Issue by nerox8664** [nmap/nmap#556]
When 'address' checkbox in view controls (topology tab) is unchecked, all host information become hidden.

All steps can be seen on screenshots:

![1](https://cloud.githubusercontent.com/assets/3521007/18888685/712e3266-850a-11e6-86f4-e6497a0fbb25.png)
![2](https://cloud.githubusercontent.com/assets/3521007/18888686/71356a4a-850a-11e6-84e5-3c2de15c3bd1.png)
![3](https://cloud.githubusercontent.com/assets/3521007/18888687/713fe6fa-850a-11e6-83ba-1c8d2bcd6729.png)

```
$ zenmap --version
zenmap 7.12
```

```
$ nmap --version

Nmap version 7.12 ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: liblua-5.2.4 openssl-1.0.2h libpcre-8.39 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select
```

**Comment by dmiller-nmap** [comment]
Thanks for the bug report. This appears to be intended behavior, though of course we could change it. The code is in `zenmap/radialnet/gui/RadialNet.py`:

```python
        if not self.__animating and self.__show_address:

            context.set_font_size(8)
            context.move_to(round(xc + x + x_gap),
                                 round(yc - y + y_gap + 4))

            hostname = node.get_info('hostname')

            if hostname is not None and self.__show_hostname:
                context.show_text(hostname)

            elif node.get_info('ip') is not None:
                context.show_text(node.get_info('ip'))
```

This seems to show that the "address" checkbox is whether to show any label at all, and "hostname" is whether to show hostname instead of numeric address when available. The one behavior this does not allow is showing hostnames when available, but never showing a numeric address. Is this the behavior you want?

**Comment by nerox8664** [comment]
I think it would be much more logical if on turn off 'address' checkbox all the other checkboxes become inactive
