### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by sgeto** [nmap/nmap#593]
This is not exactly an issue. I just like to understand something. I been thinking to build it myself when I read this in the readme:

**update:** I'm referring to npcap. Sorry

> The DLLs need to be built using Visual Studio 2013. And the driver needs to be built using Visual Studio 2015 with Windows SDK 10 10586 & Windows Driver Kit 10 10586.

 
Checking the passing appveyor build also seems to support this (Microsoft Visual Studio 12.0)

So...

1. Is this still accurate? Do we have to use both version of VS?

2. If so, why?

Thx

**Comment by hsluoyz** [comment]
> Is this still accurate? Do we have to use both version of VS?

I use VS 2013 to build DLLs because Nmap is also built with VS 2013. So the users only need ``VC++ Redist 2013`` to run both Nmap and Npcap. Building with VS 2015 will cause the users to install ``VC++ Redist 2015`` at the same time.

I use VS 2015 to build the driver, because the drivers target for OS versions instead of Visual Studio versions. So using VS 2013 and VS 2015 would be the same. And I personally want to use a more up-to-date IDE.

> If so, why?

So for your own use, you can either use VS 2013 or VS 2015 to build both the DLLS and drivers. It should has no big difference with the official build.

**Comment by sgeto** [comment]
I guess I will have to patch the batch file(s) for it to build with VS 2015 alone. It probably won't work out of the box.
