### ISSUE TITLE
Windows 10 x64 v1607: no luck with npcap

### ISSUE THREAD

**Issue by BavoB** [nmap/nmap#594]
Hallo,

When I install Wireshark with standard winpcap, everything works.
When I subsequently install nmap and npcap (latest version, but same problem occurs for almost all versions), whether in winpcap compatible mode or not, the following happens:
- Wireshark cannot find any interfaces
- Nmap cannot scan, it usually errors out with "Failed to open device eth0".

When I uninstall npcap, everything starts working, including Nmap (which at that point is using winpcap and not npcap, I suppose).

Is this still a driver signing issue with Win 10 AU?  What is going on?

Thanks,
Bavo

**Comment by hsluoyz** [comment]
> When I uninstall npcap, everything starts working, including Nmap (which at that point is using winpcap and not npcap, I suppose).

Hi @BavoB   , please provide 3 files based on [docs here](https://github.com/nmap/npcap#bug-report):
1. Diagnostic report (DiagReport)
2. install.log
3. NPFInstall.log

You can upload them to this GitHub conversation.

> Is this still a driver signing issue with Win 10 AU? What is going on?

Very possible, because I haven't signed the drivers with the new EV cert. Can you confirm that you encountered this issue: https://github.com/nmap/nmap/issues/492 ?

**Comment by hsluoyz** [comment]
Since there's no feedback in nearly two weeks. I will close this issue for now.
