### ISSUE TITLE
Add [DWORD]*NdisDeviceType=1 to Npcap Loopback Adapter

### ISSUE THREAD

**Issue by segevfiner** [nmap/nmap#653]
Setting [DWORD]*NdisDeviceType=1 in the registry for the "Npcap Loopback Adapter" will remove it from various places in the Windows GUI and will stop Network Location Awareness from considering it.

This was done, for example, in VirtualBox: https://www.virtualbox.org/ticket/9688

And also in VMware products. For the reasons I mentioned previously.

See: https://msdn.microsoft.com/en-us/windows/hardware/drivers/network/keywords-not-displayed-in-the-user-interface

**Comment by Varunram** [comment]
@segevfiner Assuming I read your question correctly, by setting NdisDeviceType to 1 in the registry, we are telling the system to identify the network interface (modem/router/hotspot) as an endpoint device (like a smartphone/tablet). So its no surprise that Windows GUI does not show it among the list of networks because windows only scans for the list of networking interfaces (i.e. devices which can communicate with an external network and not just a local computer/network) nearby.

**Comment by hsluoyz** [comment]
I just don't know why you would set ``NdisDeviceType`` to 1 for ``Npcap Loopback Adapter``?

**Comment by segevfiner** [comment]
The primary reason is that "Network Location Awareness" won't look at this
adapter. This will prevent it from being recognized as being in an
"Unidentified Network", and as such, as a public network.

Being connected to a public network interferes with some things, for
example, it sometimes disables file/printer sharing for me. Meaning that I
can't use any shares in my home without disabling the Npcap Loopback
Adapter.


I hope this clarifies why I think this should be done.

**Comment by dmiller-nmap** [comment]
I concur this looks like a good thing to do. References:

* [MSDN](https://msdn.microsoft.com/en-us/windows/hardware/drivers/network/keywords-not-displayed-in-the-user-interface): "Set *NdisDeviceType to NDIS_DEVICE_TYPE_ENDPOINT (1) if this device is an endpoint device and is not a true network interface that connects to a network."
* [Blog "Fix: VirtualBox causes 'Unidentified' network on Vista and Windows 7"](https://spicliff.blogspot.com/2012/10/fix-virtualbox-causes-network-on-vista.html): 'while this “unidentified” network is present the windows firewall settings will stay on “Public”. This behavior is undesirable because you want to be able to switch your firewall settings based on your location (home/work/public).'

I would not be surprised if this is related to #373 in cases where the windows firewall settings are very restrictive. I'm checking on a fix.

**Comment by segevfiner** [comment]
I noticed that the key has an asterisk in front of it, so it's "*NdisDeviceType". I updated the issue accordingly.

**Comment by dmiller-nmap** [comment]
Did this in nmap/npcap@a9b7f9e

**Comment by CollinChaffin** [comment]
How often does the windows installer get rebuilt?  I ask because I cannot find any nightlies or beta builds for windows.  

These issues that involve killing of wifi, missing ndis keys (this issue) are actually 100% specific to Windows users and they are pretty serious, yet the latest installer I find is still approaching a half year old from December and still does not incorporate the required fixes.

If they don't exist and it is needed, I would even volunteer to help run some builds if there are some detailed docs on the build process through to the windows installer package.

**Comment by gvanem** [comment]
> These issues that involve killing of wifi, missing ndis keys (this issue) are actually 100% specific 
> to Windows users and they are pretty serious, 

Yes, they are. That's why I'm sitting on the fence until Npcap bugs are fixed. I'm really happy with the old WinPcap (npf.sys); I'm in no need to use *loopback adapter* or anything fancy. I'm not sure why/if people think Npcap is so much faster or it's purported features are so nice that they risk a *Blue Screen* now and again. I don't.

**Comment by Varunram** [comment]
@CollinChaffin We currently don't do nightlies or beta builds, but you can download the latest version of the Windows installer <a href="https://nmap.org/npcap/dist/npcap-0.86.exe"> here </a> or view the list of available installers <a href="https://nmap.org/npcap/dist"> here </a>.
