### ISSUE TITLE
[Documentation] Example usage of mysql-info script incomplete

### ISSUE THREAD

**Issue by capt2101akash** [nmap/nmap#703]
There is a missing info on example usage of mysql-info in the documentation.
It needs to address the --script argument to pin point the particular script. It is now just explaining to use     -sC argument which is the default one. So, to give more information to new users I guess we should add the --script=mysql-info also into this.

Any views @dmiller-nmap .

**Comment by dmiller-nmap** [comment]
As I mentioned in #706, the `-sV -sC` usage statement is automatically generated based on the script being in the "default" category. It's always recommended to use `-sV` with NSE scripts since they decide which port to run against based not only on port number but also on service name, which can be discovered via `-sV`. We would be interested in more detailed usage statements or in ideas for better auto-generated ones (how could we make it easy to see what ports and services are scanned by each script, for instance?).
