### ISSUE TITLE
--open should imply --defeat-icmp-ratelimit for UDP scans

### ISSUE THREAD

**Issue by djcater** [nmap/nmap#727]
In the same way that --open now implies --defeat-rst-ratelimit for TCP scans, it would be good if it also implied --defeat-icmp-ratelimit for UDP scans.

**Comment by djcater** [comment]
Also, when using --open with -sU, the following message erroneously appears:

> Some closed ports may be reported as filtered due to --defeat-rst-ratelimit

**Comment by dmiller-nmap** [comment]
Thanks for the suggestion and bug report. I will take care of the erroneous warning message by checking whether a TCP scan has been requested. But I do not think that `--defeat-icmp-ratelimit` can safely be turned on for `--open`.

With TCP and the `--defeat-rst-ratelimit`, the only difference in output is a confusion between `closed` and `filtered` states. With `--open`, both of these states are hidden, so there is no reason not to enable the option.

For UDP and `--defeat-icmp-ratelimit`, on the other hand, there may be confusion between `closed` and `open|filtered`, the latter of which `--open` still allows to show. So there would be a clear difference in output between `--open -sU` scans done both with and without `--defeat-icmp-ratelimit`, and possibly even from one scan to the next because of port scan order and timing differences. In other words, the option sacrifices too much accuracy to be enabled silently along with a widely-used option like `--open`.
