### ISSUE TITLE
Stacktrace for tn3270-info.nse

### ISSUE THREAD

**Issue by leebaird** [nmap/nmap#732]
Starting Nmap 7.40 ( https://nmap.org ) at 2017-03-06 17:25 UTC
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:816: 'tn3270-info' did not match a category, filename, or directory
stack traceback:
	[C]: in function 'error'
	/usr/bin/../share/nmap/nse_main.lua:816: in local 'get_chosen_scripts'
	/usr/bin/../share/nmap/nse_main.lua:1271: in main chunk
	[C]: in ?

QUITTING!

**Comment by Varunram** [comment]
@leebaird NSE seems to give the right output, since there is no script with the name tn3270-info. There is a script with the name tn3270-screen though. If you wrote a new NSE script and want to test it, set NMAPDIR to the directory with the latest nmap build and execute the command. Do put in a PR here if you have a new NSE script.

**Comment by dmiller-nmap** [comment]
This can be caused by syntax problems in a script which cause it to not load properly, or by specifying a script name that does not exist. If you want to run a script that is not distributed with Nmap, you must specify an absolute or relative path to the script, or put it in Nmap's `scripts/` directory or in `$HOME/.nmap/scripts/`.
