### ISSUE TITLE
Wrong endianness in ipOps.fromdword

### ISSUE THREAD

**Issue by emyl** [nmap/nmap#750]
I suspect that 4a5ff0472a06f6fcfac59fd917b5c9ea3cc82545 (or perhaps a2e22523a4949f8a095e29e48169248235ddf463) introduced a bug in ipOps.fromdword.

I've tried to run some scripts and ip addresses are now reversed.

**Comment by Varunram** [comment]
Could you try out the patch proposed in #751 and see if it works?

**Comment by dmiller-nmap** [comment]
@emyl Thanks for bringing this up. I'm guessing you must be on a differently-endian architecture than I am, since all the tests ran safely. Can you run `make check-nse` (or the equivalent Nmap command: `nmap --script=unittest --script-args=unittest.run`) and let us know the output? If it doesn't show any errors, can you tell us which scripts exactly are failing?

**Comment by dmiller-nmap** [comment]
Ok, I confirmed that ipOps.fromdword is doing reverse-endianness from how it used to, but I believe it is more correct than it used to be. The numeric IP `0x7f000001` used to be converted to the string "1.0.0.127" when it should be "127.0.0.1". So we need to find which script is depending on the opposite behavior; that script is probably using incorrect endianness when unpacking some network data.

**Comment by dmiller-nmap** [comment]
haha! We're working on fixing this, but @emyl this is the root cause of why I was so confused over your changes in #574, which are now rolled into #743 . There are a ton of places we were unpacking IP addresses as little-endian simply because `ipOps.fromdword` was doing things backwards. Once those are all fixed, I will revisit your PRs and try to get them integrated. Thanks so much for raising this issue!
