### ISSUE TITLE
XML Output doesn't contain additional verbosity info

### ISSUE THREAD

**Issue by Varunram** [nmap/nmap#805]
Issue reported on <a href= "http://stackoverflow.com/questions/42995420/nmap-verbose-output-to-xml"> Stack Overflow</a>. As verbosity increases, the standard output to command line increases significantly. With XML output however, it doesn't seem to improve (although there are a few additional tags, it is not comparable to standard output).

Related: #71

**Comment by dmiller-nmap** [comment]
XML is not intended for debugging. It is intended as an interface for other programs to more easily parse Nmap scan **results**. It does not change significantly with `-v` because it is intended to be complete in any circumstance: there are many things in XML output that do not show up in Normal output without `-v`, or which do not show at all. E.g. port state reason info is always in XML, but only in Normal with `--reason` or `-vv`.

**Comment by Varunram** [comment]
Thanks! Cleared it up.
