### ISSUE TITLE
Potential crash caused by Npcap 

### ISSUE THREAD

**Issue by lkytal** [nmap/nmap#845]
After updated from npcap 0.84 to 0.86 some random system crash happend. I can't be sure whether this crash is caused by npcap so I attached the dumpfile.

[http://7fvdbv.com1.z0.glb.clouddn.com/041517-10140-01.dmp](http://7fvdbv.com1.z0.glb.clouddn.com/041517-10140-01.dmp)

[http://7fvdbv.com1.z0.glb.clouddn.com/041517-10953-01.dmp](http://7fvdbv.com1.z0.glb.clouddn.com/041517-10953-01.dmp)

**Comment by dmiller-nmap** [comment]
It looks like these are caused by a crash in ntoskrnl, not in npcap, but I haven't been able to make the symbols resolve yet. I'll check again next week to see if I can get it to work. If anyone else can provide output of `!analyze -v` that'd be great; debugging symbols for Npcap 0.86 are available at https://nmap.org/npcap/#download

**Comment by lkytal** [comment]
After several analyze I believe it's not caused by npcap, thx.
