### ISSUE TITLE
script output doesn't go to greppable (-oG) output

### ISSUE THREAD

**Issue by Viss** [nmap/nmap#865]
So I scan the internet for fun.
I use nmap as part of this workflow.
One thing that would make things way way way way way easier for me is to have the script output somehow land in the greppable output. For instance, if I have to scan 5-7 million ips on the internet for the presence of ms17-010, it would be super handy to be able to, in one shot, identify which hosts are vulnerable or infected, with basically one really aggressive cmdline..

nmap -oG <args, etc> | grep VULNERABLE | tee infected.txt

I'm testing this for functionality now and it seems that -oG doesn't put any script results in the output..

I guess this is a feature request? :D

**Comment by dmiller-nmap** [comment]
Grepable output has been deprecated since at least [version 3.30](https://nmap.org/changelog.html#3.30), which means that new features will not be added to it. However, we can definitely make things easier for this common case. b3849c4 adds a new script-arg [vulns.short](https://nmap.org/nsedoc/lib/vulns.html#script-args) that can be used to get all the useful info (host name or IP, vuln status, and CVE or finding title) on one line within Nmap's usual script output.
