### ISSUE TITLE
npcap-0.86.exe installer crashes on vista

### ISSUE THREAD

**Issue by techtonik** [nmap/nmap#886]
During setup, this window pops up several times:

![image](https://cloud.githubusercontent.com/assets/515889/26286046/59589320-3e64-11e7-8ff2-b16100d22ed3.png)

![image](https://cloud.githubusercontent.com/assets/515889/26286049/681d5292-3e64-11e7-9aed-52521f9701b2.png)

Nmap installer for 7.40 also fails while installing npcap.

[install.log.txt](https://github.com/nmap/nmap/files/1017192/install.log.txt)

**Comment by hsluoyz** [comment]
Hi @techtonik , please do two things here:

1. Provide the DiagReport file.
2. Run ``NPFInstall.exe`` in CMD, to see if the crash still happens.

**Comment by techtonik** [comment]
`NPFInstall.exe` crashes if being run from `cmd`.

![image](https://cloud.githubusercontent.com/assets/515889/26289459/f4c829bc-3ea8-11e7-9741-1a8ef5536b96.png)

DiagReport fails to run, because there is no PowerShell on this system.

**Comment by hsluoyz** [comment]
No Powershell, that's quite an antique machine.. I think you can try these:

1. Update to ``Vista Service Pack 1`` if not, because Npcap driver only supports Vista SP1 and later, Vista RTM is not supported and the driver won't function.
2. Install VCRedist 2013 (x86 or x64 based on your OS architecture), because all EXEs in Npcap and Nmap need that run-time. For example, NPFInstall.exe won't run without VCRedist 2013.
3. If the above two methods won't work, then please install a recent Powershell, and provide the DiagReport.

**Comment by techtonik** [comment]
1. It is Vista Home SP2 already. 
2. How to check if VCRedist 2013 is already installed?

**Comment by techtonik** [comment]
2. `Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.30501` is installed with `{f65db027-aff3-4070-886a-0d87064aabb1}` registry key as described in https://stackoverflow.com/questions/12206314/detect-if-visual-c-redistributable-for-visual-studio-2012-is-installed/34209692#34209692

**Comment by hsluoyz** [comment]
I reproduced this bug. It seems that NPFInstall.exe fails to run on Vista starting from ``0.78-r2`` because of the modification of NPFInstall code. As a workaround, you could use ``Npcap 0.78`` for now.

**Comment by hsluoyz** [comment]
Hi @techtonik , I have fixed this issue in: https://github.com/nmap/npcap/commit/16440fe1bd5715c43d143302910e656b9e4b81a0

@bonsaiviking @dmiller-nmap Hi Dan, could you make a release about this to fix Vista's support? A test install on Vista would be better because I can't build the installer. Thanks.

**Comment by techtonik** [comment]
Thanks! I will wait for another version. I might be convenient to setup Appveyor builds if installer is made open source again.

**Comment by hsluoyz** [comment]
Hi @techtonik,

Npcap 0.90 has been released at: https://nmap.org/npcap/. I think it has fixed this issue. Thanks for the report!

**Comment by techtonik** [comment]
Nice. =) Installation worked. WiFi network adapter went dull immediately after installation. but after resetting it started to work ok with Npcap in drivers. Now downloading Wireshark to check if it will pick it,

**Comment by techtonik** [comment]
Wireshark works. So awesome. =)
