### ISSUE TITLE
ssl cert error

### ISSUE THREAD

**Issue by digininja** [nmap/nmap#888]
And another one...

```
NSE: ssl-cert against 192.168.4.102:389 threw an error!
/usr/bin/../share/nmap/nselib/sslcert.lua:299: bad argument #2 to 'format' (number expected, got table)
stack traceback:
        [C]: in function 'string.format'
        /usr/bin/../share/nmap/nselib/sslcert.lua:299: in field '?'
        /usr/bin/../share/nmap/nselib/sslcert.lua:55: in local 'specialized'
        /usr/bin/../share/nmap/nselib/sslcert.lua:912: in function 'sslcert.getCertificate'
        /usr/bin/../share/nmap/scripts/ssl-cert.nse:269: in function </usr/bin/../share/nmap/scripts/ssl-cert.nse:267>
        (...tail calls...)
```

**Comment by dmiller-nmap** [comment]
The line numbers here don't line up with the current `sslcert.lua`, but I think there's still a problem with decoding here. If you can repeat this, please provide output with `--script-trace` so we can diagnose. Otherwise, we will push a change to avoid the crash at least. We'd rather properly handle the error, though.

**Comment by cldrn** [comment]
@digininja Feel free to reopen this issue if you come across it again. I'm closing it for now as a patch to avoid the crash has been pushed almost 4 months ago.
