### ISSUE TITLE
Possible fingerprint typo in nmap-os-db

### ISSUE THREAD

**Issue by protoben** [nmap/nmap#898]
In the `Fingerprint Sony PlayStation 2 game console test kit 2.2.1` entry of `nmap-os-db`, line 93122 reads as follows:
```
T4(R=Y%DF=N%T=FA-104%TG=FF%W=0%S=AO%A=Z%F=R%O=%RD=0%Q=)
```
The value `S=AO` does not appear in the documentation or (as far as I can tell) in `osscan2.cc`, where the permissible values are Z, A, A+ or O.

Is this a typo?

I'm using nmap version 7.40.

**Comment by dmiller-nmap** [comment]
Thanks for pointing this out. Yes, it appears to be a mistake that has been there since 2009 at least. I'm assuming there was a "|" character that was deleted, since this would be the easiest mistake to make. The majority of Linux fingerprints have "A" for this test, but a few have "A|O" so that's what I'm changing it to.
