### ISSUE TITLE
Npcap: chocolatey package marked as unavailable...

### ISSUE THREAD

**Issue by gpotter2** [nmap/nmap#900]
@hsluoyz Chocolatey is currently poorly failing to install npcap:

```
PS C:\WINDOWS\system32> choco install npcap
Chocolatey v0.10.5
Installing the following packages:
npcap
By installing you accept licenses for the packages.
npcap not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - npcap - npcap not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"
```

Seems that your package is marked as unlisted: https://chocolatey.org/packages/npcap

> This package is unlisted and hidden from package listings.

Please try to keep a relieable installer :/ All of our windows builds are failing because of that...

**Comment by fyodor** [comment]
Hi @gpotter2.  I'm afraid that we decided to cease supporting Chocolatey so we could focus on the official Npcap installer instead.  We have had problems recently with companies using Npcap within their commercial products in violation of Npcap's license.  If they have to actually visit the npcap.org web page and download the installer (which shows the license agreement by default when they run it), they are more likely to notice the license terms.  Unfortunately this also removes the Chcolatey convenience from honest users, and we regret that.  But we have worked hard to make our normal installer convenient and easy to use.  And the version 0.90 available from npcap.org is newer and better than the one which was available on Chocolatey anyway.

**Comment by gpotter2** [comment]
@fyodor Ok, thanks for those informations.
Is there a way we could download the latest npcap installer ? We could then use it in our appveyor scripts...

**Comment by fyodor** [comment]
Hi @gpotter2.  I'm not sure that I fully understand what you have in mind with your Appveyor scripts.  Feel free to send me an email with more details about what you're doing.  My address is fyodor at nmap.org.

**Comment by gpotter2** [comment]
Hi @fyodor. Thanks. We have found another solution to get our tests working.
https://github.com/secdev/scapy/blob/master/.appveyor/InstallNpcap.ps1
We needed to install npcap during before performing some tests with appveyor. I had to re-create the script for our own purpose....

**Comment by CollinChaffin** [comment]
@fyodor Hey I'm sure time/cycles wasn't the issue anyway, but wanted to throw out there that there are some additional ways (even some big in your face GUI-like etc.) via the Chocolatey allowed (and supported) Powershell-based boostrap that as a DEV myself with a lot of PS exp just wanted to offer that if at some time you would be willing to revisit the re-listing of nmap/npcap in the Choco directory - I would be willing to work with you to try to address what you saw happening with the violations, etc.

Obviously, anyone who really wants to violate like some of those corps you mentioned are simply just now moving to downloading the exe installer and they will keep violating forever, but it sounded like perhaps at least some of those violations were a result of sheer ignorance and not malice, in which case the additional in-your-face warnings/notifications/etc. I am suggesting would definitely be worth the effort.

I guess I'm just throwing out an olive branch (despite NOT being affiliated with Chocolatey) because as a loyal user/supporter of nMap since it's inception, and also being an avid automation supporter (including Chocolatey for those pesky WIN systems), I was (and am still) pretty darn bummed not having Choco as a deployment option anymore.

**Comment by gpotter2** [comment]
@CollinChaffin I definatly agree with you.
For automated testing, we have been forced to create our own silent installer to be able to install npcap using the command line... https://github.com/secdev/scapy/blob/master/.appveyor/InstallNpcap.ps1

This isn't practical at all, isn't kept up-to-date and is definatly a waste of time...

**Comment by CollinChaffin** [comment]
Wow so I just went to upgrade my systems using the /s switch and was welcomed with a message that the non-oem free version no longer even supports a simple silent install mode in the installer that every other freeware/open source installer has included for the last 30 years?!?  Back to winpcap I agree @gpotter2 this has become FAR FAR too difficult it's like the authors really don't want anyone actually using this dist anymore.

**Comment by gpotter2** [comment]
@CollinChaffin I have recently posted this https://github.com/nmap/nmap/issues/1092, and even sent a mail, a month ago. No answer yet...

It’s sad :(
