### ISSUE TITLE
NPCAP 0.94 - .CAT file SHA-256 digital signature is bad

### ISSUE THREAD

**Issue by SOlsonFAC** [nmap/nmap#994]
I originally added this on to the bottom of issue #875 because I was getting the same "Failed to create the npcap service for Win7, Win8 and Win10" error, but with both 0.93 and 0.94.  However as I was writing that, I happened to check the signatures on the NPCAP.CAT file and saw that the SHA-256 signature is bad (see image), so I thought I'd open a new issue.
![nosignaturepresent](https://user-images.githubusercontent.com/29106208/29890417-2634426e-8d8d-11e7-881b-83c2af096e69.jpg)

**Comment by dmiller-nmap** [comment]
This is because the `.cat` file is not a PE executable, so it cannot have 2 signatures, which is what we are trying to do. We will be changing this in future releases to only have 1 signature (probably the SHA1 signature, since that is most widely supported), but I'm not positive that this will solve the "failed to create service" problem. I'll update this issue when we have a release addressing the 2-signature problem.

**Comment by dmiller-nmap** [comment]
Possible temporary workaround here until we can get the next release done: https://github.com/nmap/nmap/issues/875#issuecomment-333598010

**Comment by dmiller-nmap** [comment]
Please test [Nmap 0.95](https://nmap.org/npcap/#download) and let us know if it solves this problem.

**Comment by SOlsonFAC** [comment]
First attempt failed the same as before (failure installing npcap service and hanging at the end).  I'll look deeper into the logs, etc.   
![image](https://user-images.githubusercontent.com/29106208/31914690-48699114-b811-11e7-8e5c-a6a326188de9.png)

**Comment by dmiller-nmap** [comment]
I am provisionally closing this issue, since there have been many fixes since Npcap 0.95. If you are still having this problem, please reopen or ask us to reopen this issue. If anyone else is newly experiencing this issue, please open a new issue.
